### PR TITLE
[SRVCOM-2370] Update build Go version to 1.19

### PR DESCRIPTION
**Pull request by dsimansk**
Per SIG release call discussion, bumping Go to 1.19.

@ReToCode @matzew @pierDipi @skonto

### CODE REVIEW

**Comment by dsimansk** [comment]
> Looks good so far, but we also need bumps here:
> 
>     * https://github.com/openshift-knative/serverless-operator/blob/main/go.mod#L3?
> 
>     * https://github.com/openshift-knative/serverless-operator/blob/main/hack/update-deps.sh#L57
> 
>     * https://github.com/openshift-knative/serverless-operator/blob/main/hack/update-deps.sh#L64
> 
> 
> and run `./hack/update-deps.sh --upgrade`

The `go.mod` version should be orthogonal to the CI infra version, e.g. for compatibility reason etc. Therefore we can keep the separate if needed. But probably as a rule of thumb, bump every time it's doable?

Strangely the generate check is failing upon .go code formatting being different. However, I can't see any changes locally on 1.19 or 1.20.

**Comment by ReToCode** [comment]
I'd still align those. That does not hurt and does definitely not cause fancy issues with formatting stuff differently on various go versions. This might even be this? Do you run `make generated-files` on the same go version as the GH-action? Looks like the indentation is different.

**Comment by dsimansk** [comment]
@ReToCode figured out the formatting, for some I needed to rerun `gofmt` locally to get the fixed output. Otherwise it's ready.

**Comment by skonto** [comment]
I thoutht we were building with 1.19.x not bumping, this creates issues on midstream repos that are not on 1.19 eg. 1.9.

**Pull request merged**
