### PR TITLE
Revert "Add eventings 0.23 (#1070)"

### PR DESCRIPTION
**Pull request by markusthoemmes**
This reverts commit 78a419de14a1aabf07dc145c77d71f9d6978bc0d.

Introduced (we think at least) quite a bit of instability we want to debug off of the `main` branch to unblock other work.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/hold

For #1089. If that doesn't do anything, we're going ahead here.

**Comment by cardil** [comment]
/test 4.7-operator-e2e-aws-ocp-47

Infra

**Comment by cardil** [comment]
All tests are passing

/lgtm

**Comment by aliok** [comment]
/lgtm
/approve
/unhold

I saw #1089 didn't really help. Let revert as discussed in https://coreos.slack.com/archives/CD87JDUB0/p1625585904264000

**Pull request merged**
