### PR TITLE
Fix lint errors about grpc.Dial

### PR DESCRIPTION
**Pull request by ReToCode**
## Proposed Changes
- Fix lint errors about grpc.Dial
- See CI errors in https://github.com/openshift-knative/serverless-operator/pull/2680 and https://github.com/openshift-knative/serverless-operator/pull/2681

/assign @skonto 
/assign @pierDipi

### CODE REVIEW

**Comment by skonto** [comment]
@ReToCode could you rebase it?

**Comment by ReToCode** [comment]
AFAIK not needed, no conflicts.

**Pull request merged**
