### PR TITLE
Update Exploring serverless apps quickstart text for connecting an event source to a knative service

### PR DESCRIPTION
**Pull request by divyanshiGupta**
**Fixes:** https://issues.redhat.com/browse/ODC-5097

This PR updates the quickstart text to fix issues mentioned in the above ticket. It also updates the text for some incorrect flows.

Screenshot 2021-05-27 at 8 35 47 PM

### CODE REVIEW

**Review by bmignano — APPROVED** [review]
LGTM, thank you @divyanshiGupta !!

**Review by matzew — APPROVED** [review]
/lgtm
/apporve

(based on my reading if the ODC-5097 ticket)

**Pull request merged**
