### PR TITLE
Avoid using head when getting nodes

### PR DESCRIPTION
**Pull request by mgencur**
Prevents errors such as:
```
 06:52:31.692 INFO:    Placing zipkin taint on first worker node
06:52:32.091 ERROR:   🚨 Error (code: 141) occurred at
./hack/lib/tracing.bash:19, with command: zipkin_node=$(oc get node -l
'node-role.kubernetes.io/worker' -oname | head -n 1)
06:52:32.093 ERROR:   Stack trace:
06:52:32.096 ERROR:    1: ./hack/lib/tracing.bash:6
dedicate_node_to_zipkin(...)
06:52:32.099 ERROR:    2: ./hack/tracing.sh:15 install_tracing(...)
make: *** [test-upgrade-with-mesh] Error 141
```
Fixes JIRA #

## Proposed Changes

-
-
-

### CODE REVIEW

**Review by cardil — APPROVED** [review]
/lgtm

Thanks @mgencur

**Comment by mgencur** [comment]
/hold

For upgrade tests to pass

**Pull request merged**
