### PR TITLE
Bumping project.yaml to 1.20, and generating other files

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

As per title: bumping

Need to wait for the 1.19 cut/branch
/hold

### CODE REVIEW

**Comment by matzew** [comment]
Removed the `WIP` state and did a rebase. Keeping the `hold` to see how things are going...

/assign @markusthoemmes

**Comment by markusthoemmes** [comment]
I guess this'll only start working after CI for the 1.19 branch has run once.

**Comment by matzew** [comment]
ah, yeh the "chicken - egg" problemo

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
