### PR TITLE
fix: update source-to-image image

### PR DESCRIPTION
**Pull request by matejvasek**
The previous image hash 8a70f501 contained bugs:
* The binary was at unusual place: https://issues.redhat.com/browse/OCPTOOLS-265.
* The binary did not match architecture -- for all arch the binary was amd64 (jira was not created for this issue).

Fixes JIRA #

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by matejvasek** [comment]
I think this should also be in 1.31.

**Comment by matejvasek** [comment]
Related PR: https://github.com/openshift-knative/kn-plugin-func/pull/725.

**Comment by dsimansk** [comment]
> /override "ci/prow/4.13-osd-images"

It's being removed in openshift/release config PR, until then overriding the check.

**Pull request merged**
