### PR TITLE
Install Serverless using release-next artifacts

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.redhat.com/browse/SRVCOM-2981

## Proposed Changes

- Provide Make target `install-release-next` for installing the current version of Serverless operator from the given branch, but using Knative Serving, Eventing and EKB from release-next branch of respective midstream repos.
- Provide Make target `generated-files-release-next` that generates yamls in the current working dir. It leaves dirty work tree, with changes required for release-next version.

### CODE REVIEW

**Comment by matzew** [comment]
LGTM!

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold
feel free to unhold this

**Comment by creydr** [comment]
Awesome. Thanks a lot @mgencur for working on this :tada:

**Comment by mgencur** [comment]
/unhold

The 414-upstream-e2e-kafka-aws-414 test is not relevant for this PR as the new make targets are not used anyway. It's enough to have the other checks passed, just to see if broke something else.

**Pull request merged**
