### PR TITLE
Set base image ubi-minimal and user for bundle image

### PR DESCRIPTION
**Pull request by mgencur**
Fix for EC failures related to base image and running as root.
Slack thread: https://redhat-internal.slack.com/archives/CKR568L8G/p1731658462179939

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by mgencur** [comment]
The previous failures `RunAsNonRoot` and `BasedOnUbi` are fixed. The only remaining one is `HasLicense` and that is being fixed in a different thread.

**Comment by dsimansk** [comment]
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / pr group bundle_base_image"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-bundle-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-ingress-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-kn-operator-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-metadata-webhook-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-must-gather-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-openshift-kn-operator-135"

**Pull request merged**
