### PR TITLE
[MAIN][SRVKE-838] Delete old broker filter,ingress sm names to avoid alerts during upgrades

### PR DESCRIPTION
**Pull request by skonto**
As in #1008 
/cc @maschmid @matzew

### CODE REVIEW

**Comment by skonto** [comment]
@maschmid finally passed.

**Comment by skonto** [comment]
@matzew could you approve this one?

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
