### PR TITLE
Check in htpasswd file and alias kubectl to drop yum based installs completely.

### PR DESCRIPTION
**Pull request by markusthoemmes**
It'd be neat to not depend on yum installs in our CI builds. This has bitten us more than once already.

### CODE REVIEW

**Comment by mgencur** [comment]
Just FYI: The changes to openshift/ci-operator/build-image/Dockerfile won't take effect until this file is merged. So these changes are not reflected in CI results on this PR.

**Comment by markusthoemmes** [comment]
Indeed, thanks for the reminder. Hmm. Do we want to risk it? 😂

**Comment by mgencur** [comment]
I hope the alias could work but not 100% sure. Would it be possible to test this locally? Worst case we can merge this and immediately send a dummy PR that will just make the tests run and we'll see.

**Comment by markusthoemmes** [comment]
Not following through for now.

**Pull request closed without merging**
