### PR TITLE
Use 1.10 multiarch images in image mapping for e2e tests

### PR DESCRIPTION
**Pull request by creydr**
As per title to address issues from https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-knative-serverless-operator-main-4.10-e2e-aws-ocp-410-continuous/1691238498117357568

### CODE REVIEW

**Comment by creydr** [comment]
/hold
need some testing

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold

since this is easy to forget about: let's update our scripts to get this done automatically, when we actually bump the version.

Does not need to be in this PR, but please let's do it - otherwise we will forget about it

**Comment by creydr** [comment]
> since this is easy to forget about: let's update our scripts to get this done automatically, when we actually bump the version.
> 
> Does not need to be in this PR, but please let's do it - otherwise we will forget about it

Yes. But would do it in a separate PR :+1:

**Comment by matzew** [comment]
> Yes. But would do it in a separate PR +1

I think that is even better. I just wanted to raise it :smile: 

thanks for looking into this

**Comment by matzew** [comment]
looks like a kourier change? (validation) @nak3

**Comment by creydr** [comment]
@matzew since we have some chicken-egg problem with #2236, I updated this PR and run `make generated-files` here in 9a58f3c

**Pull request merged**
