### PR TITLE
[1.12] Some fix for the MT PingSource adapter

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

### CODE REVIEW

**Comment by maschmid** [comment]
Um, what?

>W1207 17:29:57.337470     199 loader.go:223] Config not found: /var/run/secrets/ci.openshift.io/multi-stage/kubeconfig
>Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:ci-op-3si14j63:operator-e2e-aws-ocp-46" cannot create resource "namespaces" in API group "" at the cluster scope
>17:29:57.491 ERROR:   🚨 Error (code: 1) occurred at /go/src/github.com/openshift-knative/serverless-operator/hack/lib/namespaces.bash:7, with command: oc create namespace "${ns}"

**Comment by matzew** [comment]
> Um, what?

:joy_cat:   yeah... looks like broken?!?

**Comment by matzew** [comment]
/hold
let's see what the e2e test reports...

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
