### PR TITLE
Bump kafka 0.26

### PR DESCRIPTION
**Pull request by matzew**
as per title

* adding kafkas 0.26
* adding post-install image for the channel

Note: in 0.27 (or 1.0) we have post install for `KafkaSource` too

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by markusthoemmes** [comment]
Failure looks legit.

**Comment by markusthoemmes** [comment]
/hold

(In case we drop the requiredness of the upgrade test again and to prevent an accidental merge in that case)

**Comment by matzew** [comment]
```
state:
      waiting:
        message: 'Failed to apply default image tag "TO_BE_REPLACED": couldn''t parse
          image reference "TO_BE_REPLACED": invalid reference format: repository name
          must be lowercase'
        reason: InvalidImageName
```

ah...

**Comment by matzew** [comment]
> TestServerlessUpgrade/VerifyContinualTests/AutoscaleSustainingTest

/retest

**Comment by matzew** [comment]
@pierDipi I've updated the PR to just contain the bump.

post-install image will follow in separated PR

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
