### PR TITLE
[TEST] Test #1896 rebased on top of #1888

### PR DESCRIPTION
**Pull request by aliok**
Test #1896 rebased on top of #1888

### CODE REVIEW

**Comment by matzew** [comment]
I guess we can likely close this, since you rebased your other PR, @aliok ?

**Comment by matzew** [comment]
There is something regarding `TestKafkaSourceToKnativeService`
@aliok I recall this was somewhere already mentioned on slack

**Comment by aliok** [comment]
/test 4.11-operator-e2e-aws-ocp-411

KafkaSource times out, irrelevant.

**Comment by aliok** [comment]
> There is something regarding TestKafkaSourceToKnativeService
@aliok I recall this was somewhere already mentioned on slack

https://coreos.slack.com/archives/CD87JDUB0/p1671429538815609

Fix is supposed to be this PR: https://github.com/openshift-knative/serverless-operator/pull/1883, which is already in.

**Pull request closed without merging**
