### PR TITLE
Scale up worker nodes across all available zones

### PR DESCRIPTION
**Pull request by nak3**
When running `make install`, the script scales up 6 replicas. However,
the worker nodes are scald to 6 replicas in only one az and it makes 8
worker nodes in total.

Ths PR changes to scale up worker nodes accross all available zones
and to make total number accurate.

before
```
$ oc get machineset -n openshift-machine-api
NAME                                         DESIRED   CURRENT   READY   AVAILABLE   AGE
knakayam-dev4-q2lxn-worker-ap-southeast-2a   6         6         1       1           19h
knakayam-dev4-q2lxn-worker-ap-southeast-2b   1         1         1       1           19h
knakayam-dev4-q2lxn-worker-ap-southeast-2c   1         1         1       1           19h
```
after
```
$ oc get machineset -n openshift-machine-api
NAME                                         DESIRED   CURRENT   READY   AVAILABLE   AGE
knakayam-dev4-q2lxn-worker-ap-southeast-2a   2         2         2       2           22h
knakayam-dev4-q2lxn-worker-ap-southeast-2b   2         2         2       2           22h
knakayam-dev4-q2lxn-worker-ap-southeast-2c   2         2         2       2           22h
```

### CODE REVIEW

**Comment by mgencur** [comment]
Can you please compare the execution time of the "test" container with test runs in other PRs and see if it's slower now? We're reducing from 8 to 6 workers so if we're slower now it would make sense to increase SCALE_UP variable to 8.

**Comment by nak3** [comment]
/retest

Yes, sure. I will check the execution time.

**Comment by nak3** [comment]
/retest

`TestServiceToServiceCallViaActivator/both-disabled` failed. Not sure, it was due to reducing from 8 to 6 workers. Let's try to test again.

**Comment by nak3** [comment]
/retest

All tests passed successfully but just to check running time.

**Comment by nak3** [comment]
/retest

The always gets warning message `warning: failed to update lease`, though I am wondering that it is harmless.

**Comment by nak3** [comment]
> The log always gets warning message warning: failed to update lease, though I am wondering that it is harmless.

Never mind. Other PR has also this warning. And the runing time is almost same with others.

```
2020/02/25 04:09:40 Container cli in pod e2e-aws-ocp-43 completed successfully
2020/02/25 04:44:05 Container setup in pod e2e-aws-ocp-43 completed successfully
2020/02/25 05:19:16 Container test in pod e2e-aws-ocp-43 completed successfully
```

**Comment by nak3** [comment]
/assign @markusthoemmes @savitaashture @mgencur 

This is ready for review. Would you mind taking a look?

**Comment by mgencur** [comment]
/lgtm

I'm currently testing parallel=10 in the other PR. I'll need to test it with workers=6 and maybe I'll have to increase the workers back to 8 later but for now having just 6 seems good enough.

**Pull request merged**
