### PR TITLE
Move top-level vendor directory into test.

### PR DESCRIPTION
**Pull request by markusthoemmes**
`dep ensure` tries to be smart and tries to vendor things for all of our subdirs, even if they have their own vendor. This properly scopes this vendor dir just to the tests for now.

### CODE REVIEW

**Comment by mgencur** [comment]
Where would I run the `dep ensure` now? in the test directory? Does it make sense to run it in the top-level dir as well?

**Comment by markusthoemmes** [comment]
@mgencur Running it top-level doesn't work really at all. You'll need to run it in the individual subdirectory.

**Comment by mgencur** [comment]
/lgtm

It makes sense to have the `vendor` in the test dir because the dependencies are only related to tests.

**Pull request merged**
