### PR TITLE
Support JobSink

### PR DESCRIPTION
**Pull request by pierDipi**
JobSink will be supported starting from 1.35.

- Inject deployment image env variable
- Support creating monitoring resources for job-sink deployment

### CODE REVIEW

**Comment by pierDipi** [comment]
```
  resources.go:60: Failed to start the recordevent pod 'e2e-kafka-r-no-event-with-text-plain-body-v1beta1': pod "e2e-kafka-r-no-event-with-text-plain-body-v1beta1" did not reach the running state, got : client rate limiter Wait returned an error: context deadline exceeded
```

**Comment by maschmid** [comment]
Failed to pull image "registry.ci.openshift.org/openshift/knative-eventing-kafka-broker-test-recordevents:knative-v1.14": fetching target platform image selected from manifest list: reading manifest sha256:8e3d66a7e9c3a267ad0670b2d06a6fdb0fde818de0ee542a9edd1ddaa809f425 in registry.ci.openshift.org/openshift/knative-eventing-kafka-broker-test-recordevents: manifest unknown

I think the registry.ci.openshift.org/openshift/knative-eventing-kafka-broker-test-recordevents:knative-v1.14 image is broken in the CI registry somehow... We can try merging 

https://github.com/openshift-knative/eventing-kafka-broker/pull/1142

first, that should hopefully build and promote the test images

**Pull request merged**
