### PR TITLE
WIP: Kafka Channel 1.2.1 bump

### PR DESCRIPTION
**Pull request by matzew**
Just the new version of the old/legacy channel

### CODE REVIEW

**Comment by matzew** [comment]
/test 4.10-upstream-e2e-aws-ocp-410

```
FAIL: TestChannelTracingWithReply/InMemoryChannel-messaging.knative.dev/v1
```

not related to _this_ PR bump

**Comment by mgencur** [comment]
The failure with tracing should be fixed once https://github.com/openshift-knative/eventing-kafka/pull/660 is merged and CI images rebuilt.

**Comment by matzew** [comment]
only images...

/retest

**Comment by matzew** [comment]
Let's see what the upgrade does on _this_ version of the channel

**Comment by matzew** [comment]
And, once again:

/test 4.10-upgrade-tests-aws-ocp-410

/cc @mgencur

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
169
Error from server (NotFound): error when creating "STDIN": namespaces "kafka" not found
170
Error

**Comment by matzew** [comment]
/test 4.10-upgrade-tests-aws-ocp-410

`BrokerBackedByChannelContinualTest`

**Comment by matzew** [comment]
again:

/test 4.10-upgrade-tests-aws-ocp-410

**Pull request closed without merging**
