### PR TITLE
Bump Golang version to 1.22 in CI image

### PR DESCRIPTION
**Pull request by dsimansk**
Fixes JIRA #

## Proposed Changes

- Bump Golang version to 1.22 in CI image

/cc @ReToCode @pierDipi @mgencur

### CODE REVIEW

**Comment by ReToCode** [comment]
Probably also need to bump all the GH actions?

**Comment by dsimansk** [comment]
> Probably also need to bump all the GH actions?

Let's try to share that version across repos: https://github.com/openshift-knative/hack/pull/189

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by ReToCode** [comment]
> Successfully set up Go version 1.21.x

There is one more place it seems.

**Comment by ReToCode** [comment]
As per @pierDipi comment, maybe also bump it in the go.mod file?

**Comment by dsimansk** [comment]
> As per @pierDipi comment, maybe also bump it in the go.mod file?

Ahh, to prevent `toolchain` directive addition through Dependabot PRs, right?

**Comment by ReToCode** [comment]
> Ahh, to prevent toolchain directive addition through Dependabot PRs, right?

Yes but also because we read it in hack and use it as the go version (as far as I understood)

**Comment by ReToCode** [comment]
I meant https://github.com/openshift-knative/hack/blob/f2602e4241ac18b3da338788e15701c0610bd413/cmd/generate/generate.go#L160, but probably not relevant for S-O as we generate the Dockerfiles here from the template. But in Serving and Co we should align the go version in go.mod as well.

/lgtm
/approve

**Pull request merged**
