### PR TITLE
WIP: Bump to all Eventings to 1.2.x

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

as per title

Based on:
* https://github.com/openshift-knative/serverless-operator/pull/1490
* https://github.com/openshift-knative/serverless-operator/pull/1497
* https://github.com/openshift-knative/serverless-operator/pull/1486

### CODE REVIEW

**Comment by matzew** [comment]
Not finding the `storage-version-migration-kafka-channel-1.1.0-1.23.0--1-kqxx5` on my branch 

(and yes... that's correct - looking at it)

**Comment by matzew** [comment]
Looks like some of the version / dependencies are wrong:

```
=== Errors
vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/fake/clientset_generated.go:85:4: undefined: testing.FakeClient
vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go:89:4: undefined: testing.FakeClient
```

See for instance in this upstream PR (available on upstream 1.2.x), the `client-go` was bumped to 0.22.5
https://github.com/knative/eventing/pull/6031/files


But in SO repo, we do replace back to 0.21.4

**Comment by skonto** [comment]
> But in SO repo, we do replace back to 0.21.4
I did try to keep this compatible with the specific version we use for K8s in 4.6.

**Pull request closed without merging**
