### PR TITLE
Bump knative operator to version 1.6.1

### PR DESCRIPTION
**Pull request by skonto**
- In 1.25, 1.26 some patches dropping fields were not applied equally to v1alpha1, v1beta1. This PR aligns patches as in [1.24](https://github.com/openshift-knative/serverless-operator/tree/release-1.24/olm-catalog/serverless-operator/hack) when applicable.
- Removes completely v1alpha1 aligning with upstream 1.6.1 (v0.33.1). Migrates all references to v1beta1.
- Removes the conversion patch as 1.6.x has only v1beta1 in the conversion webhook.

Note: requires #1817

### CODE REVIEW

**Comment by skonto** [comment]
```
{  the build serverless-operator-src failed after 2m4s with reason DockerBuildFailed: Dockerfile build strategy has failed.}
```
Seeing this on #1817 too.

**Comment by skonto** [comment]
```
Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"the server could not find the requested resource", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc00035d560), Code:404}}
        	Test:       	TestBrokerNamespaceDefaulting
E1121 10:55:58.792859   94484 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 476 [running]:
```

**Comment by nak3** [comment]
/lgtm
/hold
Please feel free to unhold if we don't need to take care about the CI failure.

**Comment by skonto** [comment]
Eventing 1.6 is not in yet so this still fails. @pierDipi @matzew gentle ping if you have any comments on this one?

**Comment by skonto** [comment]
@pierDipi I think there is no point in re-running the tests unless we get https://github.com/openshift-knative/serverless-operator/pull/1793 in. The fix for the right cr version is in 1.6 branch.

**Review by pierDipi — APPROVED** [review]
/lgtm

/hold 
for tests

**Comment by skonto** [comment]
I am unholding this as we debug in #1824  and #1822

**Pull request merged**
