### PR TITLE
Bumping all core kafka manifests to 1.0.0

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

This should be merged _AFTER_ the `main` is set to `1.21` version.

This PR contains:
* bump of "kafkas" to 1.0.0 (treating legacy and broker repo as one, as that will be just one in a couple of release)
* the `storage migration` images for both, channel and source (and a new job transformer for the `KnativeKafka` enabled jobs). Did :cherries: - pick this migration update from #1350, and merged it here, since _related_ for 1.0 

## Follow up PR

Missing in this PR, and will be done in separate PRs (each):
* separation of a toggle for the `KafkaSink` type (to avoid an auto install, with the broker)

### CODE REVIEW

**Comment by matzew** [comment]
Removing the `WIP:` prefix, since the `main` has been updated to `1.21`

**Comment by matzew** [comment]
/hold
to be safe

**Comment by matzew** [comment]
/unhold
all green (like #1350)

/assign @skonto 
/assign @pierDipi

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
