### PR TITLE
[WIP] Add eventings 0.23 2nd try plus extras

### PR DESCRIPTION
**Pull request by lberk**
similar to #1070 and #1100
adding debug log levels to eventing components to see if we can determine where the event losses in upgrade tests are occuring

### CODE REVIEW

**Comment by cardil** [comment]
Ad [build 1415333499803537408](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1106/pull-ci-openshift-knative-serverless-operator-main-4.7-upgrade-tests-aws-ocp-47/1415333499803537408)

Many missed events (finished event also not transmitted).
```
2021-07-14T16:29:47.021Z	INFO	prober/verify.go:49	Fetched receiver report. Events propagated: 11349. State: active.
2021-07-14T16:29:47.021Z	INFO	prober/verify.go:51	Availability: 41.829%, Requests sent: 27132.
    verify.go:54: report fetched too early, receiver is in active state
```

**Comment by cardil** [comment]
Infra errors

/test 4.7-upgrade-tests-aws-ocp-47

**Comment by cardil** [comment]
Infra errors

/test 4.7-operator-e2e-aws-ocp-47

**Comment by lberk** [comment]
@cardil from the logs it looks like there are several kafka channel dispatchers with no log output.

do the upgrade tests scale the dispatchers or subscriptions?  It looks like even single events have been missed.  Am I understanding the output correctly?

**Comment by cardil** [comment]
In recent [build 1415677475538604032](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1106/pull-ci-openshift-knative-serverless-operator-main-4.7-upgrade-tests-aws-ocp-47/1415677475538604032) we have not missed events in two background probes: 

- `ChannelContinualTest` - testing KafkaChannel as SUT, 26k events propagated well, but no finished event received (no info how many events was sent) [source code](https://github.com/openshift-knative/serverless-operator/blob/fe8d29ddb5d34cd47c352d476f169dcc38c5aa72/vendor/knative.dev/eventing-kafka/test/upgrade/continual/channel.go#L63-L71)
- `BrokerBackedByChannelContinualTest` - testing MT Broker abcked by KafkaChannel, 21k events propagated well, but no finished event received (no info how many events was sent) [source code](https://github.com/openshift-knative/serverless-operator/blob/fe8d29ddb5d34cd47c352d476f169dcc38c5aa72/vendor/knative.dev/eventing-kafka/test/upgrade/continual/channel.go#L76-L84)

Apart from that, there are also failures in smoke tests [source code](https://github.com/openshift-knative/serverless-operator/blob/fe8d29ddb5d34cd47c352d476f169dcc38c5aa72/vendor/knative.dev/eventing-kafka/test/upgrade/postupgrade.go#L32-L37).

**Comment by aliok** [comment]
Rebased here: https://github.com/openshift-knative/serverless-operator/pull/1122

Also gonna try 1-2 things. See the PR desc.

**Comment by matzew** [comment]
/close
b/c of https://github.com/openshift-knative/serverless-operator/pull/1126

**Pull request closed without merging**
