### PR TITLE
Adding CSV bumps for potential 1.7.2 release

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

/assign @warrenvw

### CODE REVIEW

**Comment by matzew** [comment]
```
error: build error: failed to pull image: unexpected EOF
time="2020-06-30T09:55:02Z" level=info msg="Reporting job state \"failed\" with reason \"executing_graph:step_failed:cloning_source\""
```

:man_shrugging: 

Ok....
/retest

**Comment by matzew** [comment]
@markusthoemmes or @nak3 does one of you have an idea of the upgrade failures, e.g.:
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/359/pull-ci-openshift-knative-serverless-operator-release-1.7-4.3-upgrade-tests-aws-ocp-43/1277904367848001536

Thanks!

**Comment by markusthoemmes** [comment]
I think we'll want to hardcode the 1.7.1 references in the CSV.

**Comment by markusthoemmes** [comment]
The upgrade test failure is the good old "we didn't upgrade the knative version but the test expects that" bug :see_no_evil:

**Comment by matzew** [comment]
> I think we'll want to hardcode the 1.7.1 references in the CSV.

what do you mean ?

**Comment by matzew** [comment]
/test 4.4-e2e-aws-ocp-44

@markusthoemmes some AWS issue, but I think this is OK to merge ... see #362 on why the upgrades are failing

**Comment by rhuss** [comment]
obsoleted by #372

**Pull request closed without merging**
