### PR TITLE
Update dependencies to 0.19 versions upstream

### PR DESCRIPTION
**Pull request by markusthoemmes**
This was a little finicky because the operator dep is out of whack (needs fixing upstream) and the eventing-kafka change. Since I had this locally anyway, might as well send it in.

Commits are meaningful.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/test 4.6-operator-e2e-aws-ocp-46

Hrm :thinking:

**Comment by markusthoemmes** [comment]
/assign @matzew @nak3 

This one seems fine now. Wasn't too bad after fixing the operator upstream first.

**Comment by nak3** [comment]
LGTM. defer to @matzew

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
