### PR TITLE
[TEST_ONLY] Enable internal-encryption

### PR DESCRIPTION
**Pull request by nak3**
/cc

### CODE REVIEW

**Comment by nak3** [comment]
/test 4.11-upgrade-tests-aws-ocp-411

Passed once. (The fix should be merged in the upstream regardless of the downstream failure, though...)

**Comment by nak3** [comment]
/test 4.11-upgrade-tests-aws-ocp-411

`TestServerlessUpgradeContinual/UpgradeWith` is a flake even without internal-encryption.

**Comment by nak3** [comment]
Umm... The probe test failed :sweat:

**Comment by nak3** [comment]
https://github.com/knative-sandbox/net-kourier/pull/959 needs to be merged.

**Comment by skonto** [comment]
Approved the net-kourier one.

**Comment by nak3** [comment]
/test all
Passed once.

**Comment by nak3** [comment]
/retest

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1868/pull-ci-openshift-knative-serverless-operator-main-4.12-upgrade-tests-aws-ocp-412/1633102282805481472 AutoscaleSustainingTest is flake but ProbeTest :thinking: 

For the side note, 4.11 is obsoleted test and failed with the super old history. Not sure how to delete it from the CI failure history.

**Comment by nak3** [comment]
Umm... started failing again :disappointed:

**Comment by nak3** [comment]
``VerifyContinualTests/AutoscaleSustainingWithTBCTest` failed which is a flake.

**Comment by nak3** [comment]
/retest

Umm.... `VerifyContinualTests/AutoscaleSustainingWithTBCTest` passed but now `TestServerlessUpgradeContinual/VerifyContinualTests/ProbeTest ` failed :(

**Comment by nak3** [comment]
/test 4.12-upgrade-tests-aws-ocp-412

passed once.

**Comment by nak3** [comment]
/test 4.12-upgrade-tests-aws-ocp-412

getting better, I think. When test fails, it gets `502` a few times.

```
⏳ 2023-04-20T07:05:30.421Z     INFO    test/prober.go:172      "https://upgrade-probe-serving-tests.apps.ci-ocp-4-12-amd64-aws-us-east-1-g2qzf.hive.aws.ci.openshift.org" status = 502, want: 200
⏳ 2023-04-20T07:05:30.421Z     INFO    test/prober.go:173      response: status: 502, body: dial tcp 127.0.0.1:8080: connect: connection refused
  ..
    probe.go:59: CheckSLO() error SLI for "TestServerlessUpgradeContinual/VerifyContinualTests/ProbeTest" = 0.999892, wanted >= 1.000000
```

**Comment by nak3** [comment]
/test 4.12-upgrade-tests-aws-ocp-412

passed.

**Comment by nak3** [comment]
/test 4.12-upgrade-tests-aws-ocp-412

this should not be related to the PR.

**Comment by nak3** [comment]
passed.
will drop b25931345fd0a6b408f582a678eb38eb8bd46be1 as it seems un-related.

**Comment by nak3** [comment]
/test 4.12-upgrade-tests-aws-ocp-412

passed, once more.

**Comment by nak3** [comment]
It started failing a new test `PostUpgradeFromScaleToZeroTest` :cry:

**Comment by nak3** [comment]
I think I understand.

The root cause is [activator log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1868/pull-ci-openshift-knative-serverless-operator-main-4.12-upgrade-tests-aws-ocp-412/1663915465207975936/artifacts/upgrade-tests-aws-ocp-412/gather-extra/artifacts/pods/knative-serving_activator-86886c9d58-frplt_activator_previous.log)

serving 1.9 changed the `key` name https://github.com/knative/serving/commit/bd88e059b9050c49da4a03e0fc2a72d6eedea411 so it fails during the upgrade. It is okay because internal-encryption is still alpha stage.

However, I believe operator has a bug which does not say `NotReady` even if a new upgraded pod is `CrashLoopBackOff` status and old pod is `Running`.

[`oc get pod`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1868/pull-ci-openshift-knative-serverless-operator-main-4.12-upgrade-tests-aws-ocp-412/1663915465207975936/artifacts/upgrade-tests-aws-ocp-412/gather-extra/artifacts/oc_cmds/pods)

```
knative-serving                                    activator-86886c9d58-frplt                                        1/2     CrashLoopBackOff   6 (115s ago)   7m53s   10.128.2.49    ip-10-0-147-240.ec2.internal   <none>           <none>
knative-serving                                    activator-8d67dd8f5-44n4k                                         2/2     Running            0              14m     10.130.2.21    ip-10-0-200-177.ec2.internal   <none>           <none>
knative-serving                                    activator-8d67dd8f5-x77tc                                         2/2     Running            0              14m     10.131.2.16    ip-10-0-191-173.ec2.internal   <none>           <none>
```

**Comment by nak3** [comment]
wll enable this on https://github.com/openshift-knative/serverless-operator/pull/2152

**Pull request closed without merging**
