### PR TITLE
Separately add dditionalPrinterColumns to knativekafkas

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Done for https://issues.redhat.com/browse/SRVKE-569

### CODE REVIEW

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
/hold
Hold for @markusthoemmes

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

/unhold

My permission ain't needed for everything :)

**Comment by matzew** [comment]
/hold

I made updates to #607 

lets see

**Pull request closed without merging**
