### PR TITLE
[knative-client] Update client to 1.8 release

### PR DESCRIPTION
**Pull request by dsimansk**
## Proposed Changes

- 🧹 [knative-client] Update client to 1.8 release

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm

**Comment by ReToCode** [comment]
I'd have re-generating the manifests on my list. But I think we can keep it in here as well.

**Comment by dsimansk** [comment]
> I'd have re-generating the serving manifests on my list. But I think we can keep it in here as well.

The validation was failing without it. But let me know if I should remove it from the PR.

**Pull request merged**
