### PR TITLE
Bump Serving to version 1.6

### PR DESCRIPTION
**Pull request by skonto**
- The usual as in https://github.com/openshift-knative/serverless-operator/pull/1732.

### CODE REVIEW

**Comment by skonto** [comment]
```
  Warning  Failed          13m (x4 over 15m)     kubelet            Error: ErrImagePull
  Normal   BackOff         4m53s (x44 over 15m)  kubelet            Back-off pulling image "registry.ci.openshift.org/openshift/knative-v1.6.0:kourier"
```

**Comment by nak3** [comment]
LGTM except for the eventing test failing...

**Comment by skonto** [comment]
For the eventing test a fix is coming.

**Comment by nak3** [comment]
/lgtm
/hold

Thank you. Please feel free to unhold if we don't need to wait for the Eventing fix.

**Comment by skonto** [comment]
#1811 is merged will rebase

**Comment by skonto** [comment]
```
    - message: 'failed to populate resolver cache from source serverless-operator/openshift-marketplace:
        failed to list bundles: rpc error: code = Unavailable desc = connection error:
        desc = "transport: Error while dialing dial tcp 172.30.227.49:50051: connect:
```

**Pull request merged**
