### PR TITLE
Ensure proper cleanup of kservices in Serving upgrade tests

### PR DESCRIPTION
**Pull request by mgencur**
* The cleanup is now done within Golang tests. No need to remove them after running the test suite.

https://issues.redhat.com/browse/SRVKS-851

### CODE REVIEW

**Comment by nak3** [comment]
/cc @maschmid 

LGTM but sorry I would like someone to double check it. Would you mind @maschmid :pray: ?

**Comment by maschmid** [comment]
/retest 

```NoClusters: No clusters in pool are ready to be claimed```

**Pull request merged**
