### PR TITLE
Override version migration images

### PR DESCRIPTION
**Pull request by mgencur**
Same as https://github.com/openshift-knative/serverless-operator/pull/1594 , applying the same for main branch.

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

/hold
unhold once tests are green.

**Comment by pierDipi** [comment]
```
09:19:34.295 DEBUG:   [[ $(oc get pods -n knative-serving --field-selector=status.phase!=Succeeded -o jsonpath='{.items}') != '[]' ]] : Waiting until non-zero (max 600 sec.)
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
09:31:23.890 ERROR:   Time out of 600 exceeded
09:31:23.891 ERROR:   🚨 Error (code: 71) occurred at ./hack/lib/serverless.bash:23, with command: return 71
09:31:23.894 ERROR:   Stack trace:
09:31:23.895 ERROR:    1: ./hack/teardown.sh:10 teardown_serverless(...)
```
/test 4.10-operator-e2e-aws-ocp-410

**Comment by mgencur** [comment]
@pierDipi It's a real problem:
```
"message": "Back-off pulling image \"quay.io/openshift-knative/knative-serving-storage-version-migration:v1.3.0\"",
```
Looks like the image is not availble yet, I can pull v1.2.0 though.

**Comment by mgencur** [comment]
OK. The image mirroring is not yet set up for Serving/Eventing 1.3.x

**Comment by mgencur** [comment]
@pierDipi Sent https://github.com/openshift/release/pull/29300 to unblock this PR. It's a short one, can you review please?

**Comment by mgencur** [comment]
Images have been mirrored.

/retest

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
