### PR TITLE
Drop markusthoemmes from OWNERS

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title.

/hold

Until Thu or so next week.

### CODE REVIEW

**Comment by matzew** [comment]
is that a 
/joke
?

**Comment by markusthoemmes** [comment]
/unhold

Release and bumps are done :)

**Comment by rhuss** [comment]
/lgtm
/approve

even it does *not* look good to me ...

thanks a ton, @markusthoemmes, it was an absolute pleasure being able to work together with you! All the best for your next rocket stage.

**Comment by skonto** [comment]
Thanks @markusthoemmes it was also a pleasure working with you, really sorry to see you leaving!

**Pull request merged**
