### PR TITLE
Start upgrade sequence with 1.30.1

### PR DESCRIPTION
**Pull request by mgencur**
## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by mgencur** [comment]
Looks like 1.30.1 is not available on OCP 4.10. I don't get it.

**Comment by mgencur** [comment]
> Looks like 1.30.1 is not available on OCP 4.10. I don't get it.

Ah. It's probably caused by the fact that 4.10 is out of support since September 10

**Comment by mgencur** [comment]
/test 4.13-upgrade-kitchensink-ocp-413
/test 4.13-upgrade-tests-aws-ocp-413
/test 4.13-upstream-e2e-kafka-aws-ocp-413

Running on OCP 4.10 is not required. This version is no longer supported (but CI hasn't been updated yet to have 4.11 as the min. version)

**Comment by pierDipi** [comment]
so we can merge this, right @mgencur ?

/lgtm
/hold

**Comment by mgencur** [comment]
@pierDipi Yes. We can merge this.

**Pull request merged**
