### PR TITLE
fix(docs): Update docs links

### PR DESCRIPTION
**Pull request by navidshaikh**
docs.openshift.com based links are replaced by respective docs at access.redhat.com

### CODE REVIEW

**Comment by navidshaikh** [comment]
cc @abrennan89

**Comment by abrennan89** [comment]
@navidshaikh the install docs should also be the customer portal (access.redhat) link: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/serverless_applications/installing-openshift-serverless-1

**Comment by abrennan89** [comment]
LGTM, thanks @navidshaikh :slightly_smiling_face:

**Comment by bbrowning** [comment]
Needs approval from an owner

/assign @jcrossley3

**Pull request merged**
