### PR TITLE
[release-1.27] Update cli & func images

### PR DESCRIPTION
**Pull request by dsimansk**
Per title, add version of CLI and related `func` images.

/cc @Kaustubh-pande @matzew @skonto

### CODE REVIEW

**Comment by skonto** [comment]
For main should not this be 1.7?

**Comment by dsimansk** [comment]
> For main should not this be 1.7?

We don't have setup for 1.7 images yet, I'll bump the version afterwards. I hope that's OK.

**Comment by dsimansk** [comment]
@skonto @matzew or @mgencur can you pls approve the PR? Thanks!

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
