### PR TITLE
[release-1.26] Re-try CRD conversions during downgrades due to object being modified

### PR DESCRIPTION
**Pull request by mgencur**
Seen an error like this downstream:
```
=== RUN   TestServerlessDowngrade/DowngradeWith/DowngradeServerless
    upgrade_test.go:194: Serverless downgrade failed: Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "knativeservings.operator.knative.dev": the object has been modified; please apply your changes to the latest version and try again
        --- FAIL: TestServerlessDowngrade/DowngradeWith/DowngradeServerless (0.55s)
```

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by skonto** [comment]
prober fails? :thinking:

**Comment by mgencur** [comment]
ProbeTest - known issue.

**Comment by mgencur** [comment]
@skonto Internal encryption is still enabled here: https://github.com/openshift-knative/serverless-operator/blob/release-1.26/test/v1alpha1/resources/operator.knative.dev_v1alpha1_knativeserving_cr.yaml#L8

**Comment by skonto** [comment]
@mgencur yeah I was about to check that.

**Comment by mgencur** [comment]
@skonto I think those errors are surely unrelated. Could we merge this?

**Pull request merged**
