### PR TITLE
[WIP] Tests for multitenancy with Service Mesh

### PR DESCRIPTION
**Pull request by mgencur**
Fixes https://issues.redhat.com/browse/SRVCOM-2522

## Proposed Changes

- Rewrite tests from https://github.com/ReToCode/knative-multitenancy in Golang. They're under test/servinge2e/servicemesh/
- Remove TestKnativeVersusKubeServicesInOneNamespace as it's redundant. Having Knative and k8s service in one namespace is tested with all Eventing tests which now include KSVC in the test scenarios.
- Add authorization policies so that Eventing and Eventing Kafka Broker tests pass. But this PR doesn't include any tests for verifying cross-tenant traffic for Eventing. They depend on https://github.com/knative/eventing/pull/7048 to be merged and backported.
- Split the test webhook under serving/metadata-webhook into cluster-resources and namespaced-resources. The second one needs to be applied with `-n <namespace>`. This is to reduce duplication of code because the webhook is now used in two namespaces: serving-tests, serverless-tests.

### CODE REVIEW

**Comment by mgencur** [comment]
/hold
Some fixes are required for authorization policies.

**Comment by ReToCode** [comment]
/hold 

I have some idea on how to fix this. I'm going to update this PR with some changes to see if this helps for all the test cases or not.

**Comment by mgencur** [comment]
Changes from this PR will be integrated in separate PRs.

**Pull request closed without merging**
