### PR TITLE
[RELEASE-1.15] Drop 1.14.1 bundle

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title. Same as main.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/test 4.7-upgrade-tests-aws-ocp-47

Infra.

**Comment by markusthoemmes** [comment]
/test 4.7-upgrade-tests-aws-ocp-47

weird oauth issue.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold 
holding to wait on the last test

**Comment by markusthoemmes** [comment]
/unhold

All green.

**Pull request merged**
