### PR TITLE
Reenable TestNetworkPolicy

### PR DESCRIPTION
**Pull request by markusthoemmes**
Just to give this a couple of runs to see what the current state of this is.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Passed once 

/test 4.7-operator-e2e-aws-ocp-47

**Comment by markusthoemmes** [comment]
Passed twice

/test 4.7-upstream-e2e-aws-ocp-47

**Comment by markusthoemmes** [comment]
oops, meant to kick

/test 4.7-operator-e2e-aws-ocp-47

**Comment by nak3** [comment]
/test 4.7-operator-e2e-aws-ocp-47

operator test failed but kafka test failed not networkpolicy test. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1004/pull-ci-openshift-knative-serverless-operator-main-4.7-operator-e2e-aws-ocp-47/1402266150636621824

**Comment by nak3** [comment]
/lgtm
/hold

Third try also passed. I think it is alright to go?

**Comment by markusthoemmes** [comment]
/test 4.7-operator-e2e-aws-ocp-47

Let's try some more actually :joy:

**Comment by markusthoemmes** [comment]
Still broken.

**Pull request closed without merging**
