### PR TITLE
CI optimizations

### PR DESCRIPTION
**Pull request by mgencur**
Fixes [SRVCOM-2207](https://issues.redhat.com/browse/SRVCOM-2207)

## Proposed Changes

- better logging for Strimzi scripts so that they print timestamps
- install/uninstall KnativeServing/Eventing/Kafka in parallel
- remove duplicate execution of Eventing-kafka upstream test suite
- do not install Strimzi and KnativeKafka in upstream tests where it's not used

### CODE REVIEW

**Comment by mgencur** [comment]
TODO: Do not install KnativeKafka for 4.11-upstream-e2e-aws-ocp-411 as the Kafka-related tests are not run there. Install it only in 4.11-upstream-e2e-kafka-aws-ocp-411 where Kafka-related tests run.

**Comment by mgencur** [comment]
This PR shows the following improvements in execution times compared with another PR that was created recently [pull/1868](https://github.com/openshift-knative/serverless-operator/pull/1868)
```
ci/prow/4.11-operator-e2e-aws-ocp-411:
	- 1m30s by improving install (2m now vs. 3m30s before)
	- 1m by improving uninstall 
ci/prow/4.11-upstream-e2e-aws-ocp-411:
        - 1m30s by improving install
	- 6m improvement by not running eventing-kafka tests
	- 3m + 50s by not installing Strimzi and KnativeKafka
	- Overall: 11m20s
ci/prow/4.11-upgrade-tests-aws-ocp-411:
	- 1m30s by improving install
ci/prow/4.11-upstream-e2e-kafka-aws-ocp-411:
	- 1m30s by improving install
```

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
Awesome @mgencur !

**Pull request merged**
