### PR TITLE
[release-v1.22] SRVKE-1212: disable fips

### PR DESCRIPTION
**Pull request by matzew**
https://issues.redhat.com/browse/SRVKE-1212

NOTE: For the 1.2 I will likely add that to midstream (and for the channel there too)

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

/hold (waiting for optional jobs to pass)

**Comment by pierDipi** [comment]
We need https://github.com/openshift-knative/serverless-operator/pull/1543 in 1.22 too

**Comment by mgencur** [comment]
@pierDipi @matzew Sent https://github.com/openshift-knative/serverless-operator/pull/1545 against release-1.22

**Comment by matzew** [comment]
/unhold
(only one required job is running)

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
