### PR TITLE
 :broom: Drop unnecessary env values

### PR DESCRIPTION
**Pull request by nak3**
As per title, we are always specifying resolvable domain so we can drop.

See also: https://github.com/knative/serving/blob/main/test/README.md#overriding-the-gateway-used-for-spoofing

### CODE REVIEW

**Comment by nak3** [comment]
/test 4.12-upstream-e2e-mesh-aws-ocp-412
/hold

To see testing...

**Review by ReToCode — APPROVED** [review]
/lgtm

**Comment by nak3** [comment]
/test 4.12-upgrade-tests-aws-ocp-412

Unrelated `KafkaSinkSourceContinualTest` failed.

**Pull request merged**
