### PR TITLE
[RELAESE-1.32] Bump min K8s version to 1.25

### PR DESCRIPTION
**Pull request by ReToCode**
As per title.

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by mgencur** [comment]
Looks good.

**Comment by ReToCode** [comment]
@matzew had to regenerate because of https://github.com/openshift-knative/eventing/pull/547.

**Comment by mgencur** [comment]
> @mgencur any way to refresh the prow-jobs here?

Not sure. But we can always merge manually when we're satisfied with the results.

**Comment by ReToCode** [comment]
Probably also need to bump CI for this branch, as 4.11 seems to be really not usable any longer?

**Comment by matzew** [comment]
Is this done manually @ReToCode or via tool? If tool, I am not sure where exactly. I do not see branches listed here:

https://github.com/openshift-knative/hack/blob/main/config/serverless-operator.yaml

**Comment by matzew** [comment]
/hold
I guess since we have 4.11 jobs here, there is no point in merging this, as it targets MIN of 4.12

**Comment by ReToCode** [comment]
> NoClusters: No clusters in pool are ready to be claimed 

/test 414-upstream-e2e-kafka-aws-414

**Comment by matzew** [comment]
> /hold
I guess since we have 4.11 jobs here, there is no point in merging this, as it targets MIN of 4.12

/unhold 
We are now on 4.12 and have executed several tests there already

**Pull request merged**
