### PR TITLE
[1.12] [SRVKE-654] Hacking the manifest

### PR DESCRIPTION
**Pull request by matzew**
@maschmid some hack... and likely not the real solution...

/hold
as this needs a bit more testing ...  

/cc @aliok

### CODE REVIEW

**Comment by maschmid** [comment]
I suspect we may also need to  disable the bits in eventing-controller that scale pingsource-mt-adapter (if it ever scales it to something else than 1 )

**Comment by maschmid** [comment]
actually, it looks like it really only ever scales it to 1 when it is 0, so it should work as is

**Comment by matzew** [comment]
w/ that hack I get:

```
2020/12/04 19:24:12 Error processing env var: envconfig.Process: assigning K_SINK_TIMEOUT to EnvSinkTimeout: converting '' to type int. details: strconv.ParseInt: parsing "": invalid syntax
```

More next week...

**Pull request closed without merging**
