### PR TITLE
Tweak install of generate in Makefile & minor gh action fixes

### PR DESCRIPTION
**Pull request by dsimansk**
Fixes JIRA #

## Proposed Changes

- Use plain go install to get generate 
- Fix Dependabot action name
- Use shared Go setup in validate.yaml

### CODE REVIEW

**Review by creydr — COMMENTED** [review]
/lgtm

**Comment by skonto** [comment]
/override "Red Hat Konflux / serverless-index-main-on-pull-request"

**Comment by pierDipi** [comment]
We're getting this error after this change https://github.com/openshift-knative/eventing-kafka-broker/pull/1256#issuecomment-2352167431

**Comment by pierDipi** [comment]
https://github.com/openshift-knative/serverless-operator/pull/2872

**Pull request merged**
