### PR TITLE
Update client to v1.1.0

### PR DESCRIPTION
**Pull request by dsimansk**
Per title, PTAL.

/cc @rhuss @matzew @nak3

### CODE REVIEW

**Comment by nak3** [comment]
/retest

The image `registry.ci.openshift.org/openshift/knative-v1.1.0:kn-cli-artifacts` was not pushed yet - [log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1457/pull-ci-openshift-knative-serverless-operator-main-4.10-operator-e2e-aws-ocp-410/1508806699538976768/artifacts/operator-e2e-aws-ocp-410/operator-e2e/artifacts/gather-knative/quay-io-openshift-knative-must-gather-sha256-51049ace7b41db7499a225b27bf11492e419245a3c49581020c184d6c816d410/openshift-serverless/pods/knative-openshift-68675466c6-mhnv6-describe.log)
```
  Warning  Failed          3m51s (x4 over 5m21s)  kubelet, ip-10-0-132-99.ec2.internal  Failed to pull image "registry.ci.openshift.org/openshift/knative-v1.1.0:kn-cli-artifacts": rpc error: code = Unknown desc = reading manifest kn-cli-artifacts in registry.ci.openshift.org/openshift/knative-v1.1.0: manifest unknown: manifest unknown
  Warning  Failed          3m51s (x4 over 5m21s)  kubelet, ip-10-0-132-99.ec2.internal  Error: ErrImagePull
```

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
