### PR TITLE
Disable internal-encryption in upgrade tests due to SRVKS-1107

### PR DESCRIPTION
**Pull request by mgencur**
Related slack discussion: https://redhat-internal.slack.com/archives/CD87JDUB0/p1690124372516329

## Proposed Changes

-
-
-

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

/hold for all tests

**Comment by mgencur** [comment]
Regarding https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/2182/pull-ci-openshift-knative-serverless-operator-main-4.10-upgrade-tests-aws-ocp-410/1683394549851885568
internal-encryption is disabled properly in that run. The AutoscaleSustaining sometimes failed in the past, e.g. [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-knative-serverless-operator-main-4.10-upgrade-tests-aws-ocp-410-continuous/1671337341999910912)

**Comment by mgencur** [comment]
The latest failure show that the KafkaSource was not ready and the test timed out. Looking at must-gather logs the KafkaSource becomes ready a little later.

**Comment by matzew** [comment]
All tests are green... merging...

**Pull request merged**
