### PR TITLE
[RELEASE-1.17] Add missing CRDs to migration post install

### PR DESCRIPTION
**Pull request by devguyio**
As per title

### CODE REVIEW

**Comment by maschmid** [comment]
It seems it isn't enough to just serve the versions. The conversion webhook is being invoked, which fails:

`
$ oc logs storage-version-migration-eventing-eventing-0.23.0-4rpkh
{"severity":"INFO","timestamp":"2021-09-01T08:15:09.930828042Z","caller":"logging/config.go:116","message":"Successfully created the logger."}
{"severity":"INFO","timestamp":"2021-09-01T08:15:09.930973553Z","caller":"logging/config.go:117","message":"Logging level set to: info"}
{"severity":"INFO","timestamp":"2021-09-01T08:15:09.930992473Z","caller":"logging/config.go:79","message":"Fetch GitHub commit ID from kodata failed","error":"\"KO_DATA_PATH\" does not exist or is empty"}
{"severity":"INFO","timestamp":"2021-09-01T08:15:09.945062714Z","logger":"storage-migrator","caller":"migrate/main.go:50","message":"Migrating 4 group resources"}
{"severity":"INFO","timestamp":"2021-09-01T08:15:09.945126955Z","logger":"storage-migrator","caller":"migrate/main.go:53","message":"Migrating group resource pingsources.sources.knative.dev"}
{"severity":"EMERGENCY","timestamp":"2021-09-01T08:15:09.98152287Z","logger":"storage-migrator","caller":"migrate/main.go:55","message":"Failed to migrate: conversion webhook for sources.knative.dev/v1beta1, Kind=PingSource failed: conversion not supported for type [kind=PingSource group=sources.knative.dev version=v1beta1]","stacktrace":"main.main\n\t/go/src/knative.dev/eventing/vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go:55\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
`


`
oc logs pingsource-cleanup-eventing-0.23.0-sp2mk
...
[error] failed to list pingsources in namespace "pingsource-v1beta1", conversion webhook for sources.knative.dev/v1beta1, Kind=PingSource failed: conversion not supported for type [kind=PingSource group=sources.knative.dev version=v1beta1]
`


`{"level":"error","ts":"2021-09-01T08:09:43.577Z","logger":"eventing-webhook","caller":"conversion/conversion.go:59","msg":"Conversion failed","knative.dev/pod":"eventing-webhook-d587cd6d8-94q5n","uid":"e14dd822-c4ac-41f9-8bc1-04446e0ab6de","desiredAPIVersion":"sources.knative.dev/v1beta2","error":"conversion not supported for type [kind=PingSource group=sources.knative.dev version=v1beta1]","stacktrace":"knative.dev/pkg/webhook/resourcesemantics/conversion.(*reconciler).Convert\n\t/go/src/knative.dev/eventing/vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go:59\nknative.dev/pkg/webhook.conversionHandler.func1\n\t/go/src/knative.dev/eventing/vendor/knative.dev/pkg/webhook/conversion.go:61\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2069\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2448\nknative.dev/pkg/webhook.(*Webhook).ServeHTTP\n\t/go/src/knative.dev/eventing/vendor/knative.dev/pkg/webhook/webhook.go:257\nknative.dev/pkg/network/handlers.(*Drainer).ServeHTTP\n\t/go/src/knative.dev/eventing/vendor/knative.dev/pkg/network/handlers/drain.go:104\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2887\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1952"}`
```

**Comment by matzew** [comment]
i thinj we need to add apis back snd conversion webhook (to midstream branch) 🙈

**Comment by matzew** [comment]
> i thinj we need to add apis back snd conversion webhook (to midstream branch) :see_no_evil: 

Those were added back by this PR: https://github.com/openshift/knative-eventing/pull/1389


And, looking at the "source" image for knative-eventing, I see the promoted `0.23.0` image contains those APIS:

```bash
➜  serverless-operator git:(eventing_0.24) docker run -it --entrypoint /bin/bash registry.ci.openshift.org/openshift/knative-v0.23.0:knative-eventing-src
[root@3736e8a00d47 eventing]# ls -la pkg/apis/sources
total 40
drwxrwxr-x 8 root root 4096 Sep  3 15:09 .
drwxrwxr-x 8 root root 4096 Sep  3 15:09 ..
drwxrwxr-x 3 root root 4096 Sep  3 15:09 config
-rw-rw-r-- 1 root root 2136 Sep  3 15:09 constants.go
-rw-rw-r-- 1 root root 1750 Sep  3 15:09 register.go
drwxrwxr-x 2 root root 4096 Sep  3 15:09 v1
drwxrwxr-x 2 root root 4096 Sep  3 15:09 v1alpha1
drwxrwxr-x 2 root root 4096 Sep  3 15:09 v1alpha2
drwxrwxr-x 2 root root 4096 Sep  3 15:09 v1beta1
drwxrwxr-x 2 root root 4096 Sep  3 15:09 v1beta2
[root@3736e8a00d47 eventing]# 
```

**Comment by lberk** [comment]
infra failure
/test 4.6-upgrade-tests-aws-ocp-46

**Pull request merged**
