### PR TITLE
Index image use versioned images or fallback to main if it's not there

### PR DESCRIPTION
**Pull request by pierDipi**
See discussion on https://coreos.slack.com/archives/CD87JDUB0/p1663085711980399

The commit https://github.com/openshift-knative/serverless-operator/pull/1702/commits/63515d6da7951f9bcb4adba517877f2acdb17a86 (CI replacement) is testable with:
```
CURRENT_VERSION_MAJOR_MINOR=1.25
OLM_NAMESPACE=olm
index_build_dir=olm-catalog/serverless-operator/index

sed -i "s_\(.*\)\(registry.ci.openshift.org/knative/openshift-serverless-v${CURRENT_VERSION_MAJOR_MINOR}.0:serverless-bundle\)\(.*\)_\1image-registry.openshift-image-registry.svc:5000/$OLM_NAMESPACE/serverless-bundle:latest\3_" "${index_build_dir}/Dockerfile"
```
Output:
```
$ git diff
diff --git a/olm-catalog/serverless-operator/index/Dockerfile b/olm-catalog/serverless-operator/index/Dockerfile
index 9b013ed48..9e86e8c4c 100644
--- a/olm-catalog/serverless-operator/index/Dockerfile
+++ b/olm-catalog/serverless-operator/index/Dockerfile
@@ -9,7 +9,7 @@ COPY configs /configs
 
 RUN /bin/opm init serverless-operator --default-channel=stable --output yaml >> /configs/index.yaml
 RUN /bin/opm render --skip-tls-verify -o yaml registry.ci.openshift.org/knative/openshift-serverless-v1.24.0:serverless-stop-bundle \
-      registry.ci.openshift.org/knative/openshift-serverless-v1.25.0:serverless-bundle >> /configs/index.yaml || \
+      image-registry.openshift-image-registry.svc:5000/olm/serverless-bundle:latest >> /configs/index.yaml || \
     /bin/opm render --skip-tls-verify -o yaml registry.ci.openshift.org/knative/openshift-serverless-v1.24.0:serverless-stop-bundle \
       registry.ci.openshift.org/knative/openshift-serverless-nightly:serverless-bundle >> /configs/index.yaml
```

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by mgencur** [comment]
/lgtm
/hold 
Hold for tests.

**Comment by pierDipi** [comment]
```
Unable to connect to the server: dial tcp: lookup api.ci-ocp-4-11-amd64-aws-us-east-1-jpqb9.hive.aws.ci.openshift.org on 172.30.0.10:53: read udp 10.131.190.100:59267->172.30.0.10:53: i/o timeout
09:11:26.810 ERROR:   🚨 Error (code: 1) occurred at /go/src/github.com/openshift-knative/serverless-operator/test/serving.bash:51, with command: oc -n "${SERVING_NAMESPACE}" patch knativeserving/knative-serving --type=merge --patch='{"spec": {"config": { "features": {"kubernetes.podspec-volumes-emptydir": "enabled"}}}}
```
/test 4.11-upstream-e2e-aws-ocp-411

**Comment by pierDipi** [comment]
```
09:11:50.900 INFO:    Checking Serverless alerts
Unable to connect to the server: dial tcp: lookup api.ci-ocp-4-11-amd64-aws-us-east-1-5fjml.hive.aws.ci.openshift.org: i/o timeout
09:12:20.951 ERROR:   🚨 Error (code: 1) occurred at ./test/lib.bash:293, with command: monitoring_route=$(oc -n openshift-monitoring get routes alertmanager-main -oyaml -ojsonpath='{.spec.host}')
```
/test 4.11-operator-e2e-aws-ocp-411

**Comment by pierDipi** [comment]
`TestAutoscaleSustaining` failed 
```

    autoscale_test.go:118: interim scale didn't fulfill constraints: revision "autoscale-sustaining-aggregatio-zsxpsute-00001" #replicas: 7, want at least: 9
```
/test 4.11-upstream-e2e-mesh-aws-ocp-411

**Comment by pierDipi** [comment]
```
error: error when retrieving current configuration of:
Resource: "kafka.strimzi.io/v1beta2, Resource=kafkas", GroupVersionKind: "kafka.strimzi.io/v1beta2, Kind=Kafka"
Name: "my-cluster", Namespace: "kafka"
from server for: "STDIN": Get "https://api.ci-ocp-4-11-amd64-aws-us-east-1-jpqb9.hive.aws.ci.openshift.org:6443/apis/kafka.strimzi.io/v1beta2/namespaces/kafka/kafkas/my-cluster": dial tcp: lookup api.ci-ocp-4-11-amd64-aws-us-east-1-jpqb9.hive.aws.ci.openshift.org on 172.30.0.10:53: no such host
=====================================================
```
/test 4.11-upstream-e2e-aws-ocp-411

**Pull request merged**
