### PR TITLE
Add Eventing Source resources dashboard

### PR DESCRIPTION
**Pull request by skonto**
- Adds a dashboard for Eventing sources to monitor resource consumption.
- Uses as a contract the following labels:
```
label_eventing_knative_dev_source="apiserver-source-controller",label_eventing_knative_dev_sourceName="testevents",
```
Pingsource does not follow this contract and no deployment is created so we visualize the metrics that come from the ping-adapter in the knative eventing namespace.
- It is not 100% ok as there were as a bug with kafka label, waiting until https://github.com/knative-sandbox/eventing-kafka/pull/242 gets downstream, PR is already out.
- Hides deployment from the Serving resource dashboard.

Examples:
Apiserver source:
image
Ping source:
image
Kafka Source (missing source name due to the bug described above):
image
Serving update:
image

### CODE REVIEW

**Comment by skonto** [comment]
@matzew let me know what you think for this addition.

**Comment by skonto** [comment]
@matzew pls review (is https://github.com/knative-sandbox/eventing-kafka/pull/242 now available downstream).

**Comment by matzew** [comment]
@skonto yes, the fix is available on mistream: 
https://github.com/openshift/knative-eventing-contrib/commits/release-v0.18.0

(see my backport/cherry-pick :cherries: from DEC 1st)

**Comment by matzew** [comment]
Thanks for adding this! I like the new graphs, images look good.
I've quickly checked the code and it does look good to me...

/lgtm

/assign @aliok for another round of reviews

**Pull request merged**
