### PR TITLE
Update metadata for 1.22.1 release.

### PR DESCRIPTION
**Pull request by Kaustubh-pande**
Signed-off-by: Kautsubh pande kpande@redhat.com

### CODE REVIEW

**Comment by Kaustubh-pande** [comment]
/hold
not before [openshift/release#28862](https://github.com/openshift/release/pull/28862)

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by nak3** [comment]
/lgtm
/hold

I added `/hold` for CI but please feel free to drop it once it passed.

**Pull request merged**
