### PR TITLE
Make Serving service mesh tests more stable

### PR DESCRIPTION
**Pull request by ReToCode**
Fixes JIRA https://issues.redhat.com/browse/SRVCOM-2356
Partially fixes JIRA https://issues.redhat.com/browse/SRVKS-1099
Partially fixes JIRA https://issues.redhat.com/browse/SRVCOM-2522

## Proposed Changes
We are trying to do https://github.com/openshift-knative/serverless-operator/pull/2171 in parts now. This PR contains the fixes found in https://issues.redhat.com/browse/SRVKS-1099 to make Serving service-mesh tests more stable

Changes:
- Reduce parallelism of mesh tests to 8 because istio-proxies are to slow otherwise
- Use a specific label for the Knative Gateways to omit issues with conflicting gateways (SRVCOM-2356)
- Drop `TERMINATION_DRAIN_DURATION_SECONDS` from metadata-webhook, as this no longer works
- Add `terminationDrainDuration: 35s` to SMCP to make envoy wait longer with termination

/cc @mgencur , @pierDipi

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
/unhold

Eventing failures are flakes

**Comment by ReToCode** [comment]
👍  I'll add that then, but after 4.13-upstream-e2e-mesh-aws-ocp-413 is hopefully green once :)

**Pull request merged**
