### PR TITLE
Bump Serving manifests to 1.15

### PR DESCRIPTION
**Pull request by skonto**
Fixes JIRA #

## Proposed Changes

- Similar to https://github.com/openshift-knative/serverless-operator/pull/2656
- A secret has been deleted from net-istio 1.14 -> 1.15, see [here](https://github.com/knative-extensions/net-istio/pull/1344). Probably we will need to discuss with @ReToCode if this needs to be deleted after upgrading to 1.35. cc @dsimansk

### CODE REVIEW

**Comment by skonto** [comment]
Waiting for https://github.com/openshift-knative/serverless-operator/pull/2852

**Comment by skonto** [comment]
```
registry.ci.openshift.org/knative/release-1.33.0:serverless-bundle registry.ci.openshift.org/knative/release-1.34.0:serverless-bundle       registry.ci.openshift.org/knative/serverless-bundle:main >> /configs/index.yaml
2024/09/12 15:09:53 render reference "registry.ci.openshift.org/knative/release-1.33.0:serverless-bundle": error resolving name for image ref registry.ci.openshift.org/knative/release-1.33.0:serverless-bundle: failed to do request: Head "https://registry.ci.openshift.org/v2/knative/release-1.33.0/manifests/serverless-bundle": dial tcp: lookup registry.ci.openshift.org on 172.30.0.10:53: dial udp 172.30.0.10:53: connect: network is unreachable
2024/09/12 15:09:54 render reference "registry.ci.openshift.org/knative/release-1.33.0:serverless-bundle": error resolving name for image ref registry.ci.openshift.org/knative/release-1.33.0:serverless-bundle: failed to do request: Head "https://registry.ci.openshift.org/v2/knative/release-1.33.0/manifests/serverless-bundle": dial tcp: lookup registry.ci.openshift.org on 172.30.0.10:53: dial udp 172.30.0.10:53: connect: network is unreachable
```

**Comment by skonto** [comment]
/override "Red Hat Konflux / serverless-index-main-on-pull-request"
/override "serverless-kn-operator-main-on-pull-request"
/override "Red Hat Konflux / serverless-openshift-kn-operator-main-on-pull-request"

**Comment by skonto** [comment]
/override Red Hat Konflux / serverless-index-main-on-pull-request

**Comment by skonto** [comment]
/override "Red Hat Konflux / serverless-index-main-on-pull-request"

**Comment by skonto** [comment]
/override "Red Hat Konflux / serverless-openshift-kn-operator-main-on-pull-request"

**Comment by skonto** [comment]
/override "Red Hat Konflux / serverless-index-main-on-pull-request "

**Comment by skonto** [comment]
```
   triggerv2_downgrade.go:56: failed to downgrade from triggerv2 failed to get deployment: client rate limiter Wait returned an error: context deadline exceeded
--- FAIL: TestServerlessUpgradePrePost/Run/Steps/DowngradeWith/DowngradeServerless (283.58s)
```

**Comment by dsimansk** [comment]
> /override ci/prow/415-test-upgrade-aws-415

I was about to ask if we override? :)

**Pull request merged**
