### PR TITLE
Bump to 1.23

### PR DESCRIPTION
**Pull request by matzew**
let's have these as single, atomic PRs, and not as a big all update shot PR

### CODE REVIEW

**Comment by skonto** [comment]
Usually we do this after https://github.com/openshift/release/pull/27522 is merged. I guess it will not create issues since we dont touch the knative operator version.

**Comment by matzew** [comment]
@skonto usually this was the very first Markus and did in the past 

the version of Serverless Operator is independent of any operands - hence, IMO this is the canonical first shot

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
