### PR TITLE
Run upstream eventing-contrib e2e tests

### PR DESCRIPTION
**Pull request by aliok**
Just trying eventing-contrib tests here.

### CODE REVIEW

**Comment by aliok** [comment]
Now pushed a commit that also enables upstream e2e tests for serving and eventing

**Comment by matzew** [comment]
@aliok needs a rebase

**Comment by aliok** [comment]
Rebased and squashed

**Comment by aliok** [comment]
Was all green, rebased again now

**Comment by aliok** [comment]
Waiting to see if the previous failure persists. Then gonna polish and rebase this to get it actually merged

**Comment by aliok** [comment]
Ok, all green. Rebasing now

**Comment by aliok** [comment]
`tide` is messed up. It shows #617 's info in this PR for required labels

**Comment by aliok** [comment]
/close

Gonna start from scratch. CI stuck

**Pull request closed without merging**
