### PR TITLE
Bump CSV version to 1.14, upgrade from 1.13

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title.

/assign @matzew

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/retest

let's see if this is a persistent issue.

**Review by matzew — APPROVED** [review]
LOL ... was about to do the same, glad I saw yours :smile:   Thanks!

/lgtm
/approve
/hold

Feel free to `unhold` once the test passes

**Comment by markusthoemmes** [comment]
This fails due to a bug in OLM:

```
E0126 16:38:11.083110       1 queueinformer_operator.go:290] sync {"update" "openshift-serverless/install-mxztv"} failed: error updating service: knative-openshift-metrics2: Service "knative-openshift-metrics2" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]
```

See https://bugzilla.redhat.com/show_bug.cgi?id=1898500. This is fixed in 4.7 but has not yet been backported to 4.6. Upon poking a 4.6 backport was initiated, see https://bugzilla.redhat.com/show_bug.cgi?id=1920873.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
