### PR TITLE
Bump deps in test and serving/ingress to knative 0.15

### PR DESCRIPTION
**Pull request by nak3**
This patch bumps up dependencies as mentioned in https://github.com/openshift-knative/serverless-operator/issues/426.

Fixes https://github.com/openshift-knative/serverless-operator/issues/426

### CODE REVIEW

**Comment by nak3** [comment]
/test 4.5-upstream-e2e-aws-ocp-45

CI setup failed.

**Comment by rhuss** [comment]
From my naive perspective that looks good (tests are passing, too), so I'm fine if @markusthoemmes has no objections.

**Comment by rhuss** [comment]
Let's merged that, we already discussed this on the issue
/lgtm

**Review by markusthoemmes — APPROVED** [review]

**Pull request merged**
