### PR TITLE
Using the latest eventing 0.18.6 fork/branch release

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

### CODE REVIEW

**Comment by matzew** [comment]
@cardil any thoughts?

**Comment by cardil** [comment]
https://status.quay.io/incidents/tq5hjzpw3k8t ?

**Comment by matzew** [comment]
thanks, Chris - seems somewhat solved... one more try:

/test 4.6-upgrade-tests-aws-ocp-46

**Review by rhuss — COMMENTED** [review]
If CI passed that looks good to me (as it's apparently just a "simple" patch update, so I let CI judge)

/lgtm
/approve

**Comment by cardil** [comment]
I think it will fail as there is no image for [wathola-fetcher-v0.18.6](https://quay.io/repository/openshift-knative/wathola-fetcher?tag=v0.18.6&tab=tags)

and:

https://github.com/openshift-knative/serverless-operator/blob/6e8003b/test/eventing.bash#L41

and:

https://github.com/openshift-knative/serverless-operator/blob/5c49afd/hack/lib/vars.bash#L16

**Comment by matzew** [comment]
/hold

ah. yep

**Comment by matzew** [comment]
/unhold

... but will likely fail - until the image mirror is there ;-)

**Pull request merged**
