### PR TITLE
[WIP] [DNM] Tests for multitenancy with Service Mesh

### PR DESCRIPTION
**Pull request by pierDipi**
Based on https://github.com/openshift-knative/serverless-operator/pull/2171

### CODE REVIEW

**Comment by pierDipi** [comment]
After skipping the test because of https://github.com/openshift-knative/serverless-operator/pull/2171#issuecomment-1647379199

in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/2183/pull-ci-openshift-knative-serverless-operator-main-4.13-upstream-e2e-mesh-aws-ocp-413/1683446831196934144

I'm getting a serving test failure `TestServiceToServiceCall`, @ReToCode is it a flake?

**Comment by pierDipi** [comment]
We've not seen that one earlier, retesting

/test 4.13-upstream-e2e-mesh-aws-ocp-413

**Comment by ReToCode** [comment]
Let's see with all possible domain names allowed.

/test 4.13-upstream-e2e-mesh-aws-ocp-413

**Comment by pierDipi** [comment]
I'm trying locally, still EOF
```
{"level":"error","ts":"2023-07-26T08:42:03.451Z","logger":"pingsource-mt-adapter","caller":"mtping/runner.go:157","msg":"failed to send cloudevent result: {result 26 0  Post \"http://sink-zygktzib.serverless-tests.svc.cluster.local\": EOF (5x)} {source 15 0 /apis/v1/namespaces/serverless-tests/pingsources/pingsource-zrthsbez <nil>} {target 15 0 http://sink-zygktzib.serverless-tests.svc.cluster.local <nil>} {id 15 0 ce6949f9-14a9-4803-918e-bad99f3d6a98 <nil>}","commit":"bc30bfe-dirty","stacktrace":"knative.dev/eventing/pkg/adapter/mtping.(*cronJobsRunner).cronTick.func1\n\t/go/src/github.com/openshift/origin/pkg/adapter/mtping/runner.go:157\ngithub.com/robfig/cron/v3.FuncJob.Run\n\t/go/src/github.com/openshift/origin/vendor/github.com/robfig/cron/v3/cron.go:136\ngithub.com/robfig/cron/v3.(*Cron).startJob.func1\n\t/go/src/github.com/openshift/origin/vendor/github.com/robfig/cron/v3/cron.go:312"}
```

**Comment by pierDipi** [comment]
what I'm noticing is the same as the old behavior I was getting, client side
```
2023-07-26T08:48:00.727507Z	debug	envoy connection	[C290] connecting to 10.130.2.30:8080
2023-07-26T08:48:00.727595Z	debug	envoy connection	[C290] connection in progress
2023-07-26T08:48:00.727987Z	debug	envoy connection	[C290] connected
2023-07-26T08:48:00.729533Z	debug	envoy pool	[C290] attaching to next stream
2023-07-26T08:48:00.729552Z	debug	envoy pool	[C290] creating stream
2023-07-26T08:48:00.730700Z	debug	envoy connection	[C290] closing data_to_write=0 type=0
2023-07-26T08:48:00.730702Z	debug	envoy connection	[C290] closing socket: 1
2023-07-26T08:48:00.730729Z	debug	envoy connection	[C290] SSL shutdown: rc=1
2023-07-26T08:48:00.730751Z	debug	envoy pool	[C290] client disconnected, failure reason:
2023-07-26T08:48:00.730758Z	debug	envoy pool	invoking idle callbacks - is_draining_for_deletion_=false
2023-07-26T08:48:00.730764Z	debug	envoy pool	[C290] destroying stream: 0 remaining
2023-07-26T08:48:00.730766Z	debug	envoy pool	invoking idle callbacks - is_draining_for_deletion_=false
```

which makes me think that it's not instantiating an mTLS connection

**Pull request closed without merging**
