### PR TITLE
SRVKE-515: Default sinkBindingSelectionMode to 'inclusion', update to 0.17.2

### PR DESCRIPTION
**Pull request by lberk**
Default eventing sinkbinding to inclusion mode.

### CODE REVIEW

**Comment by lberk** [comment]
@matzew @rhuss any idea why the `kn` bits are failing?

**Comment by nak3** [comment]
The unit test is failed because new condition was added to KnativeServing here https://github.com/openshift-knative/serverless-operator/pull/562/files#diff-086c8d678a3a3fdc30923d54f0a6e3cb28ca62fd863a2487799e487a595de3e1R31

I will send the PR to @lberk 's branch.

**Comment by lberk** [comment]
@nak3 thanks for pointing that out! I've added the extra status step and the tests are passing locally now

**Review by nak3 — APPROVED** [review]
Great! LGTM for @lberk 's change.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

thanks @nak3 for the heads up, regarding serving

**Pull request merged**
