### PR TITLE
bump to 1.8.0, but keep images at 0.13

### PR DESCRIPTION
**Pull request by matzew**
as per title. just bump the csv version

/assign @markusthoemmes 
/assign @aliok

### CODE REVIEW

**Comment by aliok** [comment]
> om server (NotFound): knativeeventings.operator.knative.dev "knative-eventing" not found
I don't get why the upgrade test fails :( 
need to debug locally

**Comment by markusthoemmes** [comment]
/hold

We can't actually do it like this. We shouldn't bump the 4.3 and 4.4 channels here.

**Comment by matzew** [comment]
> We can't actually do it like this. We shouldn't bump the 4.3 and 4.4 channels here.

oh - I see ... so  4.5 channel only ?

**Comment by markusthoemmes** [comment]
Not even, I think it'd be preview-4.6.

**Comment by matzew** [comment]
@markusthoemmes I've changed the channels.

1.8.0 is now _only_ on the `preview-4.6` channel.

Feel free to unhold, if that makes sense for you

**Comment by markusthoemmes** [comment]
This looks like a consistent failure between all versions in the upgrade. Let's please take a look at what happened there.

**Comment by aliok** [comment]
I had a look at this. Nothing shoudl happen actually as the new channel is not used in the scripts. Checking it in detail now

**Comment by markusthoemmes** [comment]
We should probably switch the default channel in the same go.

**Comment by markusthoemmes** [comment]
The problem here is

```
DEBUG 14:37:35.336 Execution failed: [[ ! ( $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.version}") != $serving_version && $(oc get knativeserving.operator.knative.dev knative-serving -n $SERVING_NAMESPACE -o=jsonpath="{.status.conditions[?(@.type==\"Ready\")].status}") == True ) ]]. Waiting 5 sec (905/900)...
```

A good old issue with our upgrade test if we don't upgrade serving versions in the same go. See my bootstrap from the 1.7.0 release for what to remove/comment out to make that pass: https://github.com/openshift-knative/serverless-operator/commit/a6f6f11dfbda73cd1451093c647570b5259759a5

@mgencur we should look at fixing this. It's... annoying :joy:

**Comment by aliok** [comment]
/close

I created https://github.com/openshift-knative/serverless-operator/pull/300 because I cannot add commits here w/o bothering matzew

**Pull request closed without merging**
