### PR TITLE
Wait for Kafka broker deletion in tests

### PR DESCRIPTION
**Pull request by pierDipi**
I'm trying to get more information about this failure:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-knative-serverless-operator-main-4.9-e2e-aws-ocp-49-continuous/1495549080242229248

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by pierDipi** [comment]
Worked, retesting
/test 4.9-operator-e2e-aws-ocp-49

**Comment by pierDipi** [comment]
Worked, retesting
/test 4.9-operator-e2e-aws-ocp-49

**Comment by pierDipi** [comment]
Worked again, retesting
/test 4.9-operator-e2e-aws-ocp-49

**Review by matzew — APPROVED** [review]
/lgtm
/approve

feel free to unhold once the test passes again

**Comment by pierDipi** [comment]
cluster claim
/test 4.9-upstream-e2e-aws-ocp-49

**Comment by pierDipi** [comment]
Worked, retesting
/test 4.9-operator-e2e-aws-ocp-49

**Comment by pierDipi** [comment]
Worked again, retesting
/test 4.9-operator-e2e-aws-ocp-49

**Comment by pierDipi** [comment]
Worked again, retesting
/test 4.9-operator-e2e-aws-ocp-49

**Comment by pierDipi** [comment]
Worked again, retesting
/test 4.9-operator-e2e-aws-ocp-49

**Pull request merged**
