### PR TITLE
[RELEASE-1.28] Run pod sec default tests only for 4.11+

### PR DESCRIPTION
**Pull request by skonto**
- See https://github.com/openshift/release/pull/36912#issuecomment-1462052251 for more.

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
```
{Failed  === RUN   TestAutoscalerHA
```

**Comment by skonto** [comment]
ci/prow/4.8-upstream-e2e-mesh-aws-ocp-48is expected to fail due to the incompatible SM version used in tests.

**Comment by skonto** [comment]
```
TestContainerSourceV1
```

**Pull request merged**
