### PR TITLE
Give KafkaChannels time to reconcile before finalizing it

### PR DESCRIPTION
**Pull request by mgencur**
Fixes https://issues.redhat.com/browse/SRVKE-1506

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by mgencur** [comment]
Passed once, re-testing.

/test 4.10-upgrade-kitchensink-ocp-410

**Comment by mgencur** [comment]
Passed twice.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
