### PR TITLE
[SRVKS-985] Enable pod security defaults

### PR DESCRIPTION
**Pull request by skonto**
Fixes JIRA # https://issues.redhat.com/browse/SRVKS-985

## Proposed Changes
- Enables secure pod defaults
- Similar to #1862

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
I am wondering if https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/logs/branch-ci-openshift-knative-serving-release-v1.7-412-images/1633401579824484352 affects us.

**Pull request merged**
