### PR TITLE
Print traces for missed events

### PR DESCRIPTION
**Pull request by mgencur**
* Update dependencies on openshift/knative-eventing to get the functionality for printing traces
* Remove the symlinks to vendored toml files to prevent excessive backporting of dependencies and rather include a copy of those files.
* Increase memory limits for Zipkin

### CODE REVIEW

**Comment by matzew** [comment]
the GHA is complaining about:
`vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go` file :joy_cat:

**Comment by mgencur** [comment]
@matzew Yes. I've included one change in "vendor" which will induce the missed event. I want to verify this completely works as expected. Then I will remove the change and re-run tests to get a clean run.

**Comment by mgencur** [comment]
Collecting traces now works, the trace for event no. 10 from the previous run is available here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1526/pull-ci-openshift-knative-serverless-operator-main-4.10-upgrade-tests-aws-ocp-410/1517461515836329984/artifacts/upgrade-tests-aws-ocp-410/serverless-e2e/artifacts/build-MHs8w3Nu/traces/events/

**Comment by mgencur** [comment]
This one is ready to be reviewed/merged.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by mgencur** [comment]
@matzew Thanks!

**Pull request merged**
