### PR TITLE
Fix set-env GitHub action

### PR DESCRIPTION
**Pull request by ReToCode**
## Proposed Changes
- Fix build issues with new syntax for GitHub actions ::set-env (https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files)

### CODE REVIEW

**Comment by ReToCode** [comment]
The template in `csv.yaml` now contains a variable instead of `nightly`. Should we hard-code the version there or do we expect everyone to set `CURRENT_VERSION_IMAGES` when running `make release-files`?

**Review by pierDipi — APPROVED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
