### PR TITLE
Set Serving previous version to 1.5.0

### PR DESCRIPTION
**Pull request by skonto**
- Accidentally set it to 1.6.0 now reverting back to the correct version.

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

for tests
/hold 

I fear this might fail https://github.com/openshift-knative/serverless-operator/blob/ff8ea160b20e856bb464643d7c6b0dc91a4da84b/test/upgrade/installation/serverless.go#L90-L97 because otherwise I would be surprised it is passing currently

**Comment by skonto** [comment]
I think the crs once converted can be read with the new version.

**Comment by pierDipi** [comment]
/unhold

I'm still confused on why it doesn't fail https://github.com/openshift-knative/serverless-operator/pull/1852#pullrequestreview-1199030577

**Comment by skonto** [comment]
As discussed on slack it exits early if the previous version equals to the one before the downgrade because CR are not reconciled yet.

**Pull request merged**
