### PR TITLE
Delete Triggers manually before deleting namespace

### PR DESCRIPTION
**Pull request by mgencur**
Workaround for https://issues.redhat.com/browse/SRVKE-1636

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by mgencur** [comment]
/hold

For kitchensink upgrades to pass.

**Comment by maschmid** [comment]
/lgtm 

(provided the tests pass a few times... )

**Comment by mgencur** [comment]
This workround doesn't work. I have updated https://issues.redhat.com/browse/SRVKE-1636 and the upstream bug with more precise description. The triggers can't be deleted at all after upgrading to 1.34

**Pull request closed without merging**
