### PR TITLE
[BACKPORT] workloads and probes overrides

### PR DESCRIPTION
**Pull request by skonto**
## Proposed Changes

- Aims to replace #1780 
- Adds readines, liveness probes and workloads.
- Does not add workloads in v1alpha1 to stay compatible. Users can try directly v1beta1.
- Backport of https://github.com/knative/operator/pull/1246 and https://github.com/knative/operator/pull/1247

### CODE REVIEW

**Comment by skonto** [comment]
validation fails due to #1640

**Comment by matzew** [comment]
Thanks @skonto I will check this directly tomorrow morning

**Review by pierDipi — APPROVED** [review]
LGTM

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
