### PR TITLE
Moving a few images from OCP registry to quay.io

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

... and regenerating the actual manifests and related files

/hold

### CODE REVIEW

**Comment by matzew** [comment]
```
INFO[2021-10-14T10:40:08Z] Running root, [input:openshift_release_golang-1.16], [input:base], [input:cli], [input:openshift_knative-v0.25.1_knative-eventing-src], [input:openshift_knative-v0.25.1_knative-serving-src], [input:openshift_knative-v0.25.3_knative-eventing-kafka-src], src, knative-openshift-ingress, knative-operator, openshift-knative-operator, serverless-operator-src, operator-e2e-aws-ocp-48 
```

should we perhaps keep the SRC images as are? :thinking:

**Comment by matzew** [comment]
Looks like some images
```
                        value: "quay.io/openshift-knative/knative-serving-controller"

                        value: "quay.io/openshift-knative/proxyv2-ubi8:2.0.0"
                      - name: "IMAGE_kourier-control"
                        value: "quay.io/openshift-knative/knative-v0.25.0:kourier"
                      - name: "IMAGE_net-kourier-controller__controller"
                        value: "quay.io/openshift-knative/knative-v0.25.0:kourier"
                      - name: "IMAGE_net-istio-controller__controller"
                        value: "quay.io/openshift-knative/knative-v0.25.1:net-istio-controller"
                      - name: "IMAGE_net-istio-webhook__webhook"
                        value: "quay.io/openshift-knative/knative-v0.25.1:net-istio-webhook"
```

are not correct generated ... :joy:

**Comment by matzew** [comment]
@markusthoemmes is 
```
=== FAIL: test/e2e TestAutoscaleSustaining/aggregation-weightedExponential (127.57s)
```

something known - or a flake?

**Comment by markusthoemmes** [comment]
@matzew yeah, it's known.

**Comment by markusthoemmes** [comment]
The test is also not required anymore, so we should be good to go without it.

**Comment by matzew** [comment]
@markusthoemmes mind approvy? :see_no_evil:

**Comment by markusthoemmes** [comment]
Is there a plan for the remaining images? Feels especially weird that the test images (the TEST_IMAGE_TEMPLATE vars) aren't changed.

**Comment by matzew** [comment]
> test images (the TEST_IMAGE_TEMPLATE vars) aren't changed.

I left them out for now. I can see to get them in here too.  Perhaps I need to sync w/ @cardil on this subject.

The PR can still wait

**Comment by matzew** [comment]
https://github.com/openshift-knative/serverless-operator/pull/1252/commits/011372f053f3a16f233844519624419c5b1a3beb

these are not (I think) possible to change :thinking:

**Comment by cardil** [comment]
> @matzew: I left them out for now. I can see to get them in here too. Perhaps I need to sync w/ @cardil on this subject.

I don't see a reason why we shouldn't move test images as well. Only thing that needs to be adjusted is the template string used in test invovation.

**Comment by skonto** [comment]
@matzew @cardil  what is the status of this one? Does this affect productization or is it meant for local development only?
Afaik release images refer to `registry.ci.openshift.org`.

**Comment by cardil** [comment]
I think merging this PR should help address #375, so worth looking into.

**Comment by matzew** [comment]
/close

not doing this now...

**Pull request closed without merging**
