### PR TITLE
SRVCOM-2271 Install distributed tracing after Serverless

### PR DESCRIPTION
**Pull request by mgencur**
This is to verify that order of installation is not important.

Fixes https://issues.redhat.com/browse/SRVCOM-2271

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by mgencur** [comment]
The 4.12-upstream-e2e-kafka-aws-ocp-412 failure is unrelated. In that test suite Zipkin is used, not OpenTelemetryTracing.
/test 4.12-upstream-e2e-kafka-aws-ocp-412

**Comment by maschmid** [comment]
Do we actually want to merge it, or is the PR just to run the tests as a one-off?

**Comment by mgencur** [comment]
> Do we actually want to merge it, or is the PR just to run the tests as a one-off?
Good question. We can probably just close this and not merge.

**Comment by mgencur** [comment]
Tracing was installed after Serverless and the tests passed. Closing as verified.

**Pull request closed without merging**
