### PR TITLE
Use s2i GA image and update buildah image to latest released

### PR DESCRIPTION
**Pull request by Kaustubh-pande**
as per title
cc @mgencur @dsimansk

### CODE REVIEW

**Comment by mgencur** [comment]
Just a note. We don't have any tests in s-o to verify that this new image actually works. I'm not sure if we should merge it now or after verifying (somewhere else) that this stuff works.

**Comment by dsimansk** [comment]
@Kaustubh-pande perhaps we can try to verify it through func midstream rep. @jrangelramos FYI & PTAL.

**Pull request merged**
