### PR TITLE
[SRVKS-786] Custom certificates for custom domains without ServiceMesh

### PR DESCRIPTION
**Pull request by nak3**
This patch changes to create OpenShift Route with passthrough tls mode
when KIngress has `spec.tls`.

KIngress's `spec.tls` was not used on OpenShift as we don't support
autoTLS. But since v0.24, [DomainMapping with BYO cert](https://github.com/knative/serving/commit/f2cb8e542d8a681232b3d9f689b4032b650ad4b3) uses the field
without autoTLS.

No big change is necessary but we create OpenShift Route with
passthrough tls mode for better UX when users use DomainMapping with TLS.

For e2e test, Downstream also can use upstream's `TestBYOCertificate`. 

Fix https://issues.redhat.com/browse/SRVKS-786

### CODE REVIEW

**Comment by nak3** [comment]
Ugh... 
```
    domain_mapping_test.go:166: Service response unavailable: response: <nil> did not pass checks: Get "https://b-y-o-certificate-uayfksml.apps.ci-ocp-4-8-amd64-aws-us-east-1-h6qr7.hive.aws.ci.openshift.org": x509: certificate signed by unknown authority
```

**Comment by nak3** [comment]
/retest

`TestBYOCertificate` passed :tada:  Run the test again.

**Comment by nak3** [comment]
For the proof log - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1177/pull-ci-openshift-knative-serverless-operator-main-4.8-upstream-e2e-aws-ocp-48/1433014560071094272

**Comment by nak3** [comment]
/retest

It started test before https://github.com/openshift/knative-serving/pull/905 push new src image? :thinking:

**Comment by nak3** [comment]
/test 4.8-upstream-e2e-aws-ocp-48

Passed :tada https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1177/pull-ci-openshift-knative-serverless-operator-main-4.8-upstream-e2e-aws-ocp-48/1433702348231806976
One more time.

**Comment by nak3** [comment]
/cc @markusthoemmes @skonto 

Could you please take a look? This is ready for review :pray:

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
