### PR TITLE
[release-1.32] Replaces 1.31.1 on 1.32

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

- :broom: Update the replace for latest 1.31.x release

### CODE REVIEW

**Comment by matzew** [comment]
/hold
lets see

**Comment by mgencur** [comment]
I'm not sure we want to merge this, see [slack discussion](https://redhat-internal.slack.com/archives/CD87JDUB0/p1709651926781839)

**Comment by ReToCode** [comment]
> error: error creating buildah builder: initializing source docker://image-registry.openshift-image-registry.svc:5000/ci-op-m2kwrcx0/pipeline@sha256:a3d9ce9982f6a9b383e0e68e2ee200840a18e2d8a74b7d2ca66fb34b09ecb4b7: Get "https://image-registry.openshift-image-registry.svc:5000/openshift/token?account=serviceaccount&scope=repository%3Aci-op-m2kwrcx0%2Fpipeline%3Apull": dial tcp: lookup image-registry.openshift-image-registry.svc on 172.30.0.10:53: no such host

/retest

**Comment by matzew** [comment]
/close
this should not be needed. as 1.31.x can always come later than 1.32

**Pull request closed without merging**
