### PR TITLE
Prepare for onboarding to automatic CI config generation

### PR DESCRIPTION
**Pull request by mgencur**
Partially fixes https://issues.redhat.com/browse/SRVCOM-2846

## Proposed Changes

* Generate product images from template (this allows replacing the Golang version automatically and also version of base images)
* Replace some images with their registry.ci.openshift.org variant. The tooling in github.com/openshift-knative/hack can   automatically generate "base" images and inputs for ci-operator config when images in dockerfiles start with registry.ci.openshift.org (other images are ignored). Examples: registry.ci.openshift.org/origin/4.13:operator-registry, registry.ci.openshift.org/ocp/4.13:base.
* Make sure that for local builds we replace images that don't exist with "real" images (in CI this is not required because it's done automaticall).

### CODE REVIEW

**Comment by mgencur** [comment]
/hold

I would like to add a few more changes.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve
/hold for tests

**Comment by mgencur** [comment]
/unhold

Tests passed.

**Pull request merged**
