### PR TITLE
Specify the expected version of resources in downgrade error message

### PR DESCRIPTION
**Pull request by mgencur**
[Slack thread](https://redhat-internal.slack.com/archives/CKR568L8G/p1731505239779489?thread_ts=1730948534.333639&cid=CKR568L8G)

## Proposed Changes

-
-
-

### CODE REVIEW

**Review by dsimansk — APPROVED** [review]
/approve
/lgtm

**Comment by matzew** [comment]
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-openshift-kn-operator-135"

**Comment by matzew** [comment]
/override "Red Hat Konflux / serverless-openshift-kn-operator-135-on-pull-request"

**Pull request merged**
