### PR TITLE
Knative Kafka does not ship HPA

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes JIRA #

## Proposed Changes

- removing dead code: since we have no HPAs on Knative Kafka anymore, we do not need to worry about 'em

### CODE REVIEW

**Comment by matzew** [comment]
```
08:40:53.490 ERROR:   🚨 Error (code: 127) occurred at ./test/upstream-e2e-tests.sh:41, with command: upstream_knative_eventing_kafka_broker_e2e
```

@pierDipi hu?

**Comment by pierDipi** [comment]
Yep, still working on it in https://github.com/openshift-knative/serverless-operator/pull/1674

**Pull request merged**
