### PR TITLE
Remove redundant `eventing` suffix from Eventing jobs

### PR DESCRIPTION
**Pull request by pierDipi**
Avoid having Job names longer than 63 chars.

Fixes issue found in https://github.com/openshift-knative/eventing-kafka-broker/pull/1132#issuecomment-2260243019

### CODE REVIEW

**Review by creydr — COMMENTED** [review]
/lgtm

**Comment by pierDipi** [comment]
```
go: modules disabled by GO111MODULE=off; see 'go help modules'
17:17:54.138 ERROR:   🚨 Error (code: 1) occurred at /go/src/github.com/openshift-knative/serverless-operator/hack/lib/testselect.bash:5, with command: GO111MODULE=off go get github.com/openshift-knative/hack/cmd/testselect
```
@mgencur @maschmid do you know what's wrong ?

**Comment by pierDipi** [comment]
Already done https://github.com/openshift-knative/serverless-operator/pull/2805

**Comment by pierDipi** [comment]
```
tracing_test.go:87: Error verifying traces: context deadline exceeded: error getting services: rpc error: code = Internal desc = failed to fetch services: plugin error: rpc error: code = Unknown desc = failed GET to tempo: Get "http://127.0.0.1:3200/api/search/tag/service.name/values?start=1722685572&end=1722944772": dial tcp 127.0.0.1:3200: connect: connection refused
--- FAIL: TestTraceStartedAtActivator (40.66s)
```

**Comment by pierDipi** [comment]
```
This file contained potentially sensitive information and has been removed.
```

**Comment by pierDipi** [comment]
This file contained potentially sensitive information and has been removed.

**Comment by maschmid** [comment]
>  The ImageStreamTag "4-15:operator-registry" is invalid: from: Error resolving ImageStreamTag 4-15:operator-registry in namespace openshift-marketplace: unable to find latest tagged image
> 16:37:14.801 ERROR:   🚨 Error (code: 1) occurred at ./hack/lib/catalogsource.bash:144, with command: oc -n "${OLM_NAMESPACE}" start-build "${name}" --from-dir "${from_dir}" -F 

the imagestream was created from registry.ci.openshift.org/origin/4.15:operator-registry just before and the image does exist in the CI registry. .. Maybe we might need to add a wait for some ImageStreamTag status?  

let's try again... 

/test 415-test-upgrade-aws-415

**Pull request merged**
