### PR TITLE
[main] Add Konflux configurations

### PR DESCRIPTION
**Pull request by serverless-qe**
Add Konflux components and pipelines

### CODE REVIEW

**Comment by mgencur** [comment]
/override serverless-index-135-fbc-418-on-pull-request

The Dockerfile for 4.18 is not present in this PR. But it's alreaydy on main branch. I think Konflux just runs against the test branch and doesn't merge the test branch with main. So the Docker is not there.

**Comment by mgencur** [comment]
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-bundle-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-metadata-webhook-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-must-gather-135"

**Comment by mgencur** [comment]
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-kn-operator-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-ingress-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-openshift-kn-operator-135"

**Comment by mgencur** [comment]
/override 417-test-upgrade-aws-417

This PR only brings updates for Konflux, not tested in upgrade tests.

**Comment by dsimansk** [comment]
/override "Red Hat Konflux / serverless-index-135-fbc-418-on-pull-request"

**Pull request merged**
