### PR TITLE
Remove -rc1 and use replaces 1.7.2

### PR DESCRIPTION
**Pull request by warrenvw**
We will no longer be releasing 1.8.0-rc1, so removing all references to 1.8.0-rc1. Added 1.7.2 directory from release-1.7, and use replaces 1.7.2.

### CODE REVIEW

**Comment by jcrossley3** [comment]
Man, I wish didn't have to manually create these so it'd be easier to see what changed. I'm just gonna trust you...
/lgtm

**Comment by alanfx** [comment]
The changes look ok to me, @warrenvw. Just waiting for answers about the `replaces` and `skips`

**Comment by warrenvw** [comment]
Too many failures. Let's do the new bundle format migration first, and then make any necessary changes.

**Comment by markusthoemmes** [comment]
@warrenvw should we not try to just remove some of the horribly old CSVs to unblock this?

**Comment by warrenvw** [comment]
@markusthoemmes I confirmed with Shawn that we're unable to remove the "horribly old" CSVs w/o breaking the app registry stuff. Thankfully, we won't see this issue after we migrate to the operator-registry bundle format...

**Pull request closed without merging**
