### PR TITLE
Using one common label for knative serving and eventing

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Based on my work for [SRVKS-561](https://issues.redhat.com/browse/SRVKS-561) and updates to @nak3's [draft doc](https://docs.google.com/document/d/1Hsfd-DBrdBuPyzwET32D53Y33xTQ3wzPY_B_0JWnMrk/edit#) 

I am proposing to change the label to a more common one.

/assign @nak3

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm
/hold

Please feel free to unhold (and remoe `WIP`) when you are ready.

**Comment by matzew** [comment]
I feel like @markusthoemmes should do the `/unhold` :smile:

**Pull request merged**
