### PR TITLE
[main] Set KafkaChannel as default if INSTALL_KAFKA is true

### PR DESCRIPTION
**Pull request by mgencur**
This is required for upgrade tests so that Eventing Brokers use the KafkaChannel.

### CODE REVIEW

**Review by matzew — COMMENTED** [review]
/lgtm
/assign @lberk for final review (he recently had to deal with this)

FWIW: upstream doc for that is now also present: https://github.com/knative/docs/pull/3433/files

**Comment by matzew** [comment]
/hold
for @lberk

**Comment by matzew** [comment]
@mgencur do we want this on the 1.14 branch too ?

**Comment by mgencur** [comment]
@matzew yes, I was waiting for a final review before creating the other PR

**Comment by lberk** [comment]
lgtm in principle.  My only question is if we want to set a default `repliactionFactor` or `numPartitions` for testing in the future?
/unhold

**Comment by mgencur** [comment]
@lberk I'm not sure about setting the `replicationFactor` and `numPartitions`. It would be good if the tests used the most common value, perhaps the default. When do you think we'd need to set the two parameters?

**Pull request merged**
