### PR TITLE
Prevent deleting knative-serving NS when uninstalling Service Mesh

### PR DESCRIPTION
**Pull request by mgencur**
Pulling this commit out of https://github.com/openshift-knative/serverless-operator/pull/1453 and sending it separately.

### CODE REVIEW

**Comment by nak3** [comment]
This change is good to me.
But I'm prefer to separating the namespace into a differet yaml like `hack/lib/mesh_resources/namespace.yaml` and update `hack/lib/mesh.bash` as applying `namespace.yaml` but not deleting it.

**Comment by mgencur** [comment]
@nak3 Something like the last commit above?

**Comment by nak3** [comment]
/lgtm
/approve
/hold

Yes, exactly! Thank you so much. (`/hold` for CI.)

**Pull request merged**
