### PR TITLE
Revert "Going with Apache Kafka 3.1 (#1438)"

### PR DESCRIPTION
**Pull request by matzew**
This reverts commit 6e63268ea630d7aec8704b63bfa7bb41adc0d248.

### CODE REVIEW

**Comment by matzew** [comment]
well...

/test 4.10-upgrade-tests-aws-ocp-410

**Comment by pierDipi** [comment]
It panics for timeout `panic: test timed out after 1h0m0s` we should increase that timeout.

**Comment by matzew** [comment]
> we should increase that timeout.

added a little increase:
https://github.com/openshift-knative/serverless-operator/pull/1554/commits/0e5120a5f3ddfc24b4ab74fd80e8ae322ff12e83

**Pull request closed without merging**
