### PR TITLE
[WIP] Test enabling serving and eventing upstream e2e tests

### PR DESCRIPTION
**Pull request by aliok**
Bases https://github.com/openshift-knative/serverless-operator/pull/570

### CODE REVIEW

**Comment by aliok** [comment]
/test 4.5-upstream-e2e-aws-ocp-45

Kube failure in Eventing tests (before Kafka)
```
FailedMount MountVolume.SetUp failed for volume "default-token-hn52z" : failed to sync secret cache: timed out waiting for the condition {kubelet ip-10-0-161-123.us-east-2.compute.internal} 2020-10-15 22:10:47 +0000 UTC 2020-10-15 22:10:47 +0000 UTC 1 Warning 0001-01-01 00:00:00 +0000 UTC nil  nil  }
```

**Comment by matzew** [comment]
/retest

same mount problem

**Comment by aliok** [comment]
/retest

```
FailedMount MountVolume.SetUp failed for volume "default-token-vrt4w" : failed to sync secret cache: timed out waiting for the condition {kubelet ip-10-0-251-156.ec2.internal} 2020-10-16 07:19:58 +0000 UTC 2020-10-16 07:19:58 +0000 UTC 1 Warning 0001-01-01 00:00:00 +0000 UTC nil  nil  }
```

:(

**Comment by matzew** [comment]
because of #581 
/close

**Pull request closed without merging**
