### PR TITLE
[release-v1.20] [SRVKE-1161] change name of eventing/kafka post jobs

### PR DESCRIPTION
**Pull request by matzew**
/hold

First changes.

Not sure yet if the two kafka jobs also need some updates, will check

### CODE REVIEW

**Comment by matzew** [comment]
@mgencur this is ready for testing 

If you decide to not merge it -> ok

**Comment by mgencur** [comment]
I'm testing it now locally. Was able to reproduce the bug and now trying the fix.

**Comment by mgencur** [comment]
Alright, the upgrade works as expected. I tested by:
* install Serverless 1.20.0 from OperatorHub (including KnativeEventing and KnativeKafka)
* deploy CatalogSource from the branch
* change Subscription's source to the new CatalogSource
* approve the upgrade to 1.20.1
* KnativeEventing and KnativeKafka are upgraded successfully

**Pull request merged**
