### PR TITLE
[SRVCOM-1666][RELEASE 1.19] Fix version in csv urls and other broken ones

### PR DESCRIPTION
**Pull request by skonto**
Same as in https://github.com/openshift-knative/serverless-operator/pull/1397

### CODE REVIEW

**Comment by maschmid** [comment]
Do we need to backport https://github.com/openshift-knative/serverless-operator/pull/1399 first?

**Comment by skonto** [comment]
Yes I was about to comment on that :)

**Comment by maschmid** [comment]
io.strimzi.operator.cluster.model.KafkaVersion$UnsupportedKafkaVersionException: Unsupported Kafka.spec.kafka.version: 2.8.0. Supported versions are: [3.0.0, 3.1.0]

the tests seems to assume it has amq-streams 1.x, instead of the new 2.x  which has been released since, I'll try to take a look

**Comment by maschmid** [comment]
Should be fixed by https://github.com/openshift-knative/serverless-operator/pull/1405 , hopefully

**Comment by skonto** [comment]
@maschmid it seems all tests time out while waiting for the strimzi cluster to be up.

**Pull request merged**
