### PR TITLE
[release-1.23] Index image use versioned images or fallback to main if it's not there

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry-pick of https://github.com/openshift-knative/serverless-operator/pull/1702 + `make generated-files`

I tested that it works now:

```shell
$ docker build -t index-v1.23 -f olm-catalog/serverless-operator/index/Dockerfile olm-catalog/serverless-operator/index
$ docker run -ti --rm --entrypoint="/bin/opm" index-v1.23 validate /configs
```

### CODE REVIEW

**Comment by pierDipi** [comment]
Lint job fix in https://github.com/openshift-knative/serverless-operator/pull/1707

**Comment by mgencur** [comment]
Maybe this just needs a rebase. The lint fails for some strange reason. 
The other failure on OCP 4.6 is the known KafkaSinkSourceContinualTest

**Comment by pierDipi** [comment]
Closed, since 1.23 is EOL

**Pull request closed without merging**
