### PR TITLE
Fix code-generation

### PR DESCRIPTION
**Pull request by ReToCode**
## Proposed Changes
- Pins `k8s.io/kube-openapi` to avoid the following errors:

```bash
# k8s.io/code-generator/cmd/openapi-gen
cmd/openapi-gen/main.go:37:43: undefined: generatorargs.NewDefaults
cmd/openapi-gen/main.go:45:26: undefined: generatorargs.Validate
cmd/openapi-gen/main.go:53:14: undefined: generators.Packages
```

- This can be removed once we bump to K8s 1.30.
- See separated commits for easier review

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
Prow seems stuck

**Comment by pierDipi** [comment]
It's back again :)

**Comment by skonto** [comment]
Let's see.

**Pull request merged**
