### PR TITLE
[SRVKS-397] Remove broken APIService and add a test so we don't regress.

### PR DESCRIPTION
**Pull request by markusthoemmes**
**Note:** This'll break until we actually update the knative-serving-operator image.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Failed as expected

```
 --- FAIL: TestKnativeServing (627.79s)
    --- PASS: TestKnativeServing/create_subscription_and_wait_for_CSV_to_succeed (70.95s)
    --- PASS: TestKnativeServing/deploy_knativeserving_cr_and_wait_for_it_to_be_ready (180.71s)
    --- FAIL: TestKnativeServing/verify_correct_deployment_shape (0.09s)
        knative_serving_test.go:54: Found an custom-metrics API registered at the autoscaler 
```

Gonna supplement the proper image now.

**Comment by markusthoemmes** [comment]
/test 4.3-upgrade-tests-aws-ocp-43

Setup issue.

**Comment by markusthoemmes** [comment]
/test 4.2-upgrade-tests-aws-ocp-42

Unrelated.

**Comment by markusthoemmes** [comment]
/test 4.2-e2e-aws-ocp-42

Setup error.

**Comment by markusthoemmes** [comment]
Failed in teardown with a network issue. That's a new one 😂 

/test 4.3-upgrade-tests-aws-ocp-43

**Comment by mgencur** [comment]
This looks good to me. I'm just curious why we're changing the image to `registry.svc.ci.openshift.org/openshift/knative-v0.11.1:knative-serving-operator` now and didn't change it earlier. Is this a temporary change that we want here just to test the API services or is this something that we should have done earlier?

**Comment by markusthoemmes** [comment]
@mgencur we punted on actually building our own image earlier. @warrenvw productized straight from upstream code previously. Because we **need** the changes now, we had to bite the bullet and create the fork, setup image propagation and whatnot.

**Pull request merged**
