### PR TITLE
Update CSV for 1.10.1

### PR DESCRIPTION
**Pull request by warrenvw**
Updated CSV template to reference 1.10.1, and executed `make csv` to render `olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml`.

### CODE REVIEW

**Comment by maschmid** [comment]
``` time="2021-02-10T05:12:25Z" level=error msg="permissive mode disabled" bundles="[quay.io/openshift-knative/serverless-bundle:1.7.2 registry.svc.ci.openshift.org/openshift/openshift-serverless-v1.8.0:serverless-bundle registry.svc.ci.openshift.org/openshift/openshift-serverless-v1.9.0:serverless-bundle image-registry.openshift-image-registry.svc:5000/openshift-marketplace/serverless-bundle]" error="Invalid bundle serverless-operator.v1.10.1, bundle specifies a non-existent replacement serverless-operator.v1.10.0" ```  

I guess we need to add v1.10.0 to the list..

**Comment by mgencur** [comment]
Yeah, here we need to add 1.10.0: https://github.com/openshift-knative/serverless-operator/blob/release-1.10/hack/lib/catalogsource.bash#L84 (similar to other older versions)

**Comment by warrenvw** [comment]
I'll make the necessary changes tomorrow.

**Pull request merged**
