### PR TITLE
Add certs to knative-operator sa

### PR DESCRIPTION
**Pull request by skonto**
## Proposed Changes

- See error https://github.com/openshift-knative/serving/pull/603#issuecomment-1911799511.

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
Given the error I think it needs to be added to `knative-operator` SA, it is now added to `knative-openshift-ingress`

**Comment by ReToCode** [comment]
LGTM, but needs https://github.com/openshift-knative/serverless-operator/pull/2471 first.

**Comment by skonto** [comment]
@ReToCode I think we can stamp it now.

**Pull request merged**
