### PR TITLE
Update kn-cli-artifacts image to v0.14.0

### PR DESCRIPTION
**Pull request by navidshaikh**

### CODE REVIEW

**Comment by markusthoemmes** [comment]
TestConsoleCLIDownloadAndDeploymentResources is failing @navidshaikh

**Comment by navidshaikh** [comment]
/retest

@markusthoemmes : yup, thank you!

Updated `kn-cli-artifacts image` at release promotion.

```
$ docker run registry.svc.ci.openshift.org/openshift/knative-v0.14.0:kn-cli-artifacts rpm -q python36
python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64
```

**Comment by navidshaikh** [comment]
tests passed! conflicts in CSV though, rebasing..

**Comment by navidshaikh** [comment]
/retest

   seeing `TestTriggerDependencyAnnotation` test failure in 43 44 45

**Comment by navidshaikh** [comment]
/retest

Failing at aforementioned tests.
The relevant test (`TestConsoleCLIDownloadAndDeploymentResources`) for the changes in PR is passing and I've verified locally as well.

**Comment by navidshaikh** [comment]
/test 4.4-e2e-aws-ocp-44
/test 4.4-e2e-aws-ocp-45
/test 4.4-upgrade-tests-aws-ocp-44
/test 4.4-upgrade-tests-aws-ocp-45

43 set passed

**Comment by navidshaikh** [comment]
The relevant test for changes passed (+ full test suite for 4.3 ) and others are flaking. Can we get this in ? @matzew @markusthoemmes

**Pull request merged**
