### PR TITLE
Trying eventing 0.20.0

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

* Updated `project.yaml`
* Updated the patches to 0.20.0 version/folder path
* run `make generated-files`

/hold

let's see ...

### CODE REVIEW

**Comment by matzew** [comment]
/cc @lberk  I think this is something to consider for the "automation" we have talked.

Once we have all "ready" for a certain release....  we need to update this.

Usually it is just:
* update the project
* update the path of the patch (sure.... a bit of knowledge here is needed: like do we still need the patch... :thinking: )
* run the make target

**Comment by matzew** [comment]
FYI: @markusthoemmes 
looks like you also "just" updated the patches and the project file (but I added a comment for serving adding the HPA stuff)

**Comment by matzew** [comment]
Related comment from @mgencur: https://github.com/openshift-knative/serverless-operator/pull/803#discussion_r574275404

**Comment by mgencur** [comment]
Superseded by #819

**Pull request closed without merging**
