### PR TITLE
SRVCOM-2051 Update links in CSV to point to OCP 4.11 docs

### PR DESCRIPTION
**Pull request by mgencur**
Fixes JIRA https://issues.redhat.com/browse/SRVCOM-2051

### CODE REVIEW

**Comment by mgencur** [comment]
Ok. The failing test is `KafkaSinkSourceContinualTest`. It has nothing in common with this PR.

**Comment by skonto** [comment]
@mgencur what about the rest of the links eg. serverless-application-quickstart.yaml?

**Comment by mgencur** [comment]
Good point. I was not aware of this file. It's not even generated so the links needs to be updated manually (vs. templates). Let me add a template for this one so that we don't miss it next time.

**Comment by skonto** [comment]
```AutoscaleSustainingWithTBCTest``` seems a bit flaky, we need to take a look at some point.

**Comment by skonto** [comment]
@mgencur feel free to unhold.

**Pull request merged**
