### PR TITLE
Use knative-serving-src image for running tests

### PR DESCRIPTION
**Pull request by mgencur**
* this image is used to run tests

Used in: https://github.com/openshift/release/pull/9143 (the PRs depends on each other so thay should be merged together)
Depends on: 
https://github.com/openshift/knative-serving/pull/474
https://github.com/openshift/release/pull/9141

### CODE REVIEW

**Comment by mgencur** [comment]
/hold

I'll run this 2-3 times to see how quick it is.

**Comment by mgencur** [comment]
/hold cancel

The CI has been a little slower recently. This PR is ready to be merged. /cc @markusthoemmes

**Comment by mgencur** [comment]
/retest

@markusthoemmes I'm rerunning this for 12th time now. If the failure is cluster setup issue, a random failure in Probe or another random failure in Serving E2E test suite, please merge this manually.

**Comment by cardil** [comment]
This have broke CVP.

**Comment by mgencur** [comment]
@cardil in what sense? If the CVP was relying on checking out the knative-serving and other repos by the serverless-operator scripts it should be changed and check out the repos by itself. The rest of the test scripts should work.

**Pull request merged**
