### PR TITLE
Add golangci-lint to our components and fix all existing issues

### PR DESCRIPTION
**Pull request by markusthoemmes**
We're using this upstream to catch a multitude of bugs and issues with the code. The config is checked in, so running it locally should be fairly painless.

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
Looks good, but same concerns/suggestion as in #600 : Do we have a way to easily run the validation locally so that we do not need the CI for reporting things back which should be part of the initial development workflow ?

**Comment by markusthoemmes** [comment]
/hold

Until we decide as a team we want this.

@rhuss yeah, since the linting configuration is checked in, we "just" need to install `golangci-lint` and run it respectively. I can add a README section about that.

**Comment by markusthoemmes** [comment]
Rebased on #600, will rebase again once that merges. Only the last commit is significant.

**Comment by markusthoemmes** [comment]
/test 4.5-upgrade-tests-aws-ocp-45

Infra, failing to create namespaces...

**Review by aliok — APPROVED** [review]
/lgtm
/approve
/unhold

**Pull request merged**
