### PR TITLE
[SRVKE-1286] Restart Kafka data planes when logging or tracing config change

### PR DESCRIPTION
**Pull request by pierDipi**
- Add an annotation to data plane pods for restarting data plane pods
  when logging and tracing config change

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

Fixes JIRA #SRVKE-1286

### CODE REVIEW

**Comment by pierDipi** [comment]
The annotation is [injected](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1676/pull-ci-openshift-knative-serverless-operator-main-4.10-upstream-e2e-aws-ocp-410/1560575128486547456/artifacts/upstream-e2e-aws-ocp-410/serverless-e2e/artifacts/gather-knative/quay-io-openshift-knative-must-gather-sha256-f1cd829ea23838ac3e9b7e3a42269ea34a32e7af6a5465f9d5d21a3caf3ce446/knative-eventing/pods/describe.log) :tada: 
```
              operator.knative.openshift.io/configmap-volume-checksum: 4b55ca95
```

**Comment by matzew** [comment]
I've rebased this PR

**Comment by matzew** [comment]
Updating `tracing` on the `KnativeEventing`'s `spec.config` section to:

```yaml
    tracing:
      backend: zipkin
      debug: 'false'
      enable: 'false'
      sample-rate: '0.5'
      zipkin-endpoint: >-
        http://cluster-collector-collector-headless.istio-system.svc:9411/api/v2/spans
```

I do see that the Kafka DP pods get restarted:

```
...
kafka-broker-dispatcher-5f5f5955d5-mqstp                          2/2     Running     0          45s
kafka-broker-receiver-747b89d596-4fls6                            2/2     Running     0          45s
kafka-channel-dispatcher-97b645d7d-9kggr                          2/2     Running     0          46s
kafka-channel-receiver-66c79d8b67-svzlr                           2/2     Running     0          46s
kafka-controller-55577d9465-zczs9                                 2/2     Running     0          5m7s
kafka-controller-post-install-1.25.0--1-wc9ws                     1/1     Running     0          5m6s
kafka-sink-receiver-f5757c568-wrfnk                               2/2     Running     0          45s
kafka-source-dispatcher-5445f57fc9-mxbwl                          2/2     Running     0          46s
kafka-webhook-eventing-66ddcb7b5b-fhxp8                           2/2     Running     0          5m7s
...
```

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
