### PR TITLE
Doing a bump of Strimzi to 0.30, from 0.29

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes JIRA #

## Proposed Changes

- Going to the latest version of the upstream Strimzi Operator

### CODE REVIEW

**Comment by matzew** [comment]
`TestAutoscaleSustaining` and `TestAutoscalerHA` test issues...

/retest

**Comment by matzew** [comment]
```
FAIL test/e2e.TestKnativeEventing/verify_health_metrics_work_correctly (1200.60s)
```

/retest

**Comment by matzew** [comment]
Looks like some flake with the `TestAutoscalerHA`

**Comment by skonto** [comment]
@matzew feel free to unhold

**Pull request merged**
