### PR TITLE
Allow openshift-ingress to reconcile ingress by istio ingressclass

### PR DESCRIPTION
**Pull request by nak3**
This patch allows openshift-ingress to reconcile ingress
by istio ingressclass.

/cc @markusthoemmes

### CODE REVIEW

**Comment by nak3** [comment]
Docker's rate limit :disappointed: 

```
Error reading manifest golang-1.14 in docker.io/openshift/origin-release: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
