### PR TITLE
Without service mesh, no scaling is the reasonable default

### PR DESCRIPTION
**Pull request by jcrossley3**
Should result in a friendlier user experience

### CODE REVIEW

**Comment by markusthoemmes** [comment]
So the results kinda look like we don't need the scaling at all anymore? That'd be awesome!

**Comment by nak3** [comment]
It seems running upstream tests need some nodes :crying_cat_face: . The log says, for example in `TestContainerExitingMsg/tcp`,:

```
Message="Revision \"container-exiting-ms-djwyhrxb-ccjkr\" failed with message: 0/6 nodes are available: 3 Insufficient cpu, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate..", Status="False")
```

**Comment by jcrossley3** [comment]
Can someone point to where I would override the SCALE_UP value in the CI configuration to account for the upstream tests that @nak3 mentioned?

**Comment by mgencur** [comment]
@jcrossley3 I'd say here: https://github.com/openshift-knative/serverless-operator/blob/master/Makefile#L32 and here: https://github.com/openshift-knative/serverless-operator/blob/master/Makefile#L36
Like this: `SCALE_UP=6 ./test/...`

**Comment by jcrossley3** [comment]
> @jcrossley3 I'd say here: https://github.com/openshift-knative/serverless-operator/blob/master/Makefile#L32 and here: https://github.com/openshift-knative/serverless-operator/blob/master/Makefile#L36
> Like this: `SCALE_UP=6 ./test/...`

For all three upstream targets? How can I tell which make targets CI runs?

**Comment by mgencur** [comment]
It's defined here: https://github.com/openshift/release/blob/master/ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5.yaml (for AWS). And the parent folder has other files for "master" branch which run on GCP, Azure, vSphere (the files always have "master" in the name. Which reminds me that vSphere defines it's own scale: https://github.com/openshift/release/blob/master/ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5-vsphere.yaml#L45

**Comment by jcrossley3** [comment]
Sorry, I can't tell what's wrong from the logs. I thought this would be a simple change. Feel free to close if this one fails...
/retest

**Comment by mgencur** [comment]
I've found this among the gathered artifacts, maybe it's related? https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/405/pull-ci-openshift-knative-serverless-operator-master-4.5-upgrade-tests-aws-ocp-45/1291117350745018368/artifacts/upgrade-tests-aws-ocp-45/serverless-e2e/gather-knative/quay-io-openshift-knative-must-gather-sha256-51049ace7b41db7499a225b27bf11492e419245a3c49581020c184d6c816d410/openshift-serverless/pods/knative-openshift-5dcbc4d457-r7tmm.log

**Comment by mgencur** [comment]
It took me a few attempts but it appears that the SCALE_UP is not passed properly in the Makefile and the following works: (double dollar sign):
```
SCALE_UP=$${SCALE_UP:-6} TEST_KNATIVE_E2E=true TEST_KNATIVE_UPGRADE=false ./test/upstream-e2e-tests.sh
```

**Comment by nak3** [comment]
/test 4.5-operator-e2e-aws-ocp-45

CI setup issue.

**Pull request merged**
