### PR TITLE
Bump operator CRD to v1.9.0

### PR DESCRIPTION
**Pull request by nak3**
As `olm-catalog/serverless-operator/project.yaml` still sets `v1.6.0` for operator, downstream cannot use some API update of upstream.
This patch bumps the CRD.

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
Nice, thank you!

/lgtm
/approve

/hold for others to chime in

**Comment by nak3** [comment]
/test 4.12-upstream-e2e-aws-ocp-412

TestPersistentVolumeClaims failed.

```
"RevisionFailed", Message:"Revision \"persistent-volume-claims-cxbvzfyo-00001\" failed with message: Initial scale was never achieved."
```

Let's see if the failure is persistent.

**Comment by nak3** [comment]
/test 4.12-upstream-e2e-aws-ocp-412

Hmm... It worked when `skip-on-fail` falg :sweat_smile: 
One more time just in case.

**Comment by nak3** [comment]
/cc @ReToCode @skonto 

It passed three times in a raw without fail. It seems the failure of `TestPersistentVolumeClaims` is just a temporary issue.

**Pull request merged**
