### PR TITLE
Separate upgrade and downgrade tests

### PR DESCRIPTION
**Pull request by mgencur**
Fixes https://issues.redhat.com/browse/SRVCOM-2125

## Proposed Changes

- run upgrade tests, then restart Zipkin, then run downgrade tests
- continual tests will be started/stopped for each phase separately

### CODE REVIEW

**Comment by mgencur** [comment]
For 4.11-upstream-e2e-kafka-aws-ocp-411, I'm getting `./test/upstream-e2e-tests.sh: line 41: upstream_knative_eventing_kafka_broker_e2e: command not found` . Unrelated to this PR.

**Review by pierDipi — APPROVED** [review]
/

**Pull request merged**
