### PR TITLE
Fixing the hardcoded version name

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

For a little while (until the new channel lands) we go back to a versioned-name, rather than generated name...

/hold
(to see all checks really pass before mergers)

### CODE REVIEW

**Comment by pierDipi** [comment]
Since this is passing https://github.com/openshift-knative/serverless-operator/pull/1492, why do we need this PR?

**Comment by matzew** [comment]
b/c that image is not installed/applied. Let me check again, if that now actually has changed.

**Comment by matzew** [comment]
@pierDipi 

```
oc get jobs -nknative-eventing
NAME                                                      COMPLETIONS   DURATION   AGE
kafka-controller-post-install-1.23.0                      1/1           16s        36s
knative-kafka-storage-version-migrator-1.23.0             1/1           6s         36s
storage-version-migration-eventing-eventing-1.1.0         1/1           13s        89s
storage-version-migration-eventing-kafka-channel-1.23.0   0/1                      37s
```

can we get this patch in? once we have swapped the channel IMPL, this image is gone anyways ....   

but, as said before we need this PR to be merged

**Comment by matzew** [comment]
name of job is a problem:

```
Warning  FailedCreate  4m42s (x2 over 7m48s)  job-controller  (combined from similar events): Error creating: Pod "storage-version-migration-eventing-kafka-channel-1.23.--1-r89vv" is invalid: [metadata.generateName: Invalid value: "storage-version-migration-eventing-kafka-channel-1.23.--1-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "storage-version-migration-eventing-kafka-channel-1.23.--1-r89vv": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

this PR does address the naming issue

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
