### PR TITLE
Provide spec.registry like other operator CRs

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

- Like upstream adding `registry` field from its `base` for providing image overrides

### CODE REVIEW

**Comment by matzew** [comment]
/hold

let's see if we really want this

**Comment by dsimansk** [comment]
Isn't that an override we don't want to change downstream in the product?

**Comment by matzew** [comment]
> Isn't that an override we don't want to change downstream in the product?

That said, overriding the images on `KnativeServing` and `KnativeEventing` types is a supported feature.  However missing on the `KnativeKafka` CR. FWIW, I guess we are _not_ actually documenting that. I guess for a reason :sweat_smile: 

FWIW, the PR is on hold for now.

**Comment by matzew** [comment]
/close

we are actually removing that filed from upstream:
https://github.com/openshift-knative/serverless-operator/blob/main/olm-catalog/serverless-operator/hack/002-serving-drop-unsupported-fields.patch

**Pull request closed without merging**
