### PR TITLE
[WIP] Drop seccompProfile from net-istio deployments

### PR DESCRIPTION
**Pull request by nak3**
testing, need to patch to net-istio repo.

### CODE REVIEW

**Comment by nak3** [comment]
Record the [logs](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-knative-serverless-operator-main-4.10-e2e-mesh-ocp-410-continuous/1637665444447916032):

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-knative-serverless-operator-main-4.10-e2e-mesh-ocp-410-continuous/1637665444447916032/artifacts/e2e-mesh-ocp-410-continuous/gather-extra/artifacts/oc_cmds/events

```
knative-serving                        17m         Warning   FailedCreate                   replicaset/net-istio-controller-5c46976c8d                            Error creating: pods "net-istio-controller-5c46976c8d-9kbzx" is forbidden: unable to validate against any security context constraint: [pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/controller: Forbidden: seccomp may not be set provider "anyuid": Forbidden: not usable by user or serviceaccount provider "nonroot": Forbidden: not usable by user or serviceaccount provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount provider "hostnetwork": Forbidden: not usable by user or serviceaccount provider "hostaccess": Forbidden: not usable by user or serviceaccount provider "node-exporter": Forbidden: not usable by user or serviceaccount provider "privileged": Forbidden: not usable by user or serviceaccount]
```

**Comment by skonto** [comment]
Yes we should not set this in <4.11.

**Pull request closed without merging**
