### PR TITLE
Refactor monitoring files and dirs

### PR DESCRIPTION
**Pull request by skonto**
- re-organizes the code under knative-operator dir to follow the same structure as in the openshift-knative-operator dir.
- removes redundant test files
- renames files to better match their content

### CODE REVIEW

**Comment by skonto** [comment]
gentle ping @markusthoemmes @nak3 for review and approval

**Comment by markusthoemmes** [comment]
I'm fine but would like for somebody from Eventing to review the Kafka related bits.

**Comment by skonto** [comment]
@aliok could you take a look?

**Comment by skonto** [comment]
@markusthoemmes in general the kafka bits affect only the monitoring part but let's get some extra feedback.

**Review by aliok — APPROVED** [review]
/lgtm
/approve

Looks good to me. I don't see any actual logic changes.

Thanks for the reorganization.

**Pull request merged**
