### PR TITLE
Use `mtls: true` in SMCP

### PR DESCRIPTION
**Pull request by ReToCode**
Fixes JIRA https://issues.redhat.com/browse/SRVKS-1099

## Proposed Changes
- Use `mtls: true` in SMCP
- Enable the generation of YAML manifests in `make generated-files`

/assign @mgencur , @pierDipi 

/hold

### CODE REVIEW

**Comment by ReToCode** [comment]
This finally works out 🎉  PR upstream to add the annotation permanently: https://github.com/knative-extensions/reconciler-test/pull/576.

**Comment by mgencur** [comment]
Nice! Looks good. I have two questions:
1) The JIRA mentiones "Solution part 3: Disable IOR until it is fully removed from OSSM or annotate our gateways" I couldn't find this anywhere. How was this problem resolved?
2) Shall we wait until https://github.com/knative-extensions/reconciler-test/pull/576 is merged, backported to release-1.10 and dependencies in this PR updated? The "Validate" check fails.

**Comment by ReToCode** [comment]
> The JIRA mentiones "Solution part 3: Disable IOR until it is fully removed from OSSM or annotate our gateways" I couldn't find this anywhere. How was this problem resolved?
We solved this in net-istio with an annotation: https://github.com/openshift-knative/net-istio/blob/main/openshift/patches/002-add-maistra-annotation.patch

> Shall we wait until https://github.com/knative-extensions/reconciler-test/pull/576 is merged, backported to release-1.10 and dependencies in this PR updated? The "Validate" check fails.
Yeah I think so. I just added it here directly for the tests. I'll update it as soon as the other PRs are merged.

**Comment by ReToCode** [comment]
Fix is in upstream, this is ready for review and should fix all the mesh tests.
@pierDipi , @mgencur

**Review by pierDipi — APPROVED** [review]
Nice, looks good, thanks!

/lgtm
/approve
/hold for tests and Martin review

**Comment by pierDipi** [comment]
It seems unrelated error, I think we can merge

**Comment by ReToCode** [comment]
> It seems unrelated error, 4.10 passes, I think we can merge

As there is no hurry, let's retry once.

**Comment by ReToCode** [comment]
> * 2023-08-22T06:14:53Z 136x default-scheduler: 0/22 nodes are available: 1 Insufficient cpu, 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 10 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: ci-tests-worker}, 2 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 4 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}. preemption: 0/22 nodes are available: 1 No preemption victims found for incoming pod, 21 Preemption is not helpful for scheduling..

**Pull request merged**
