### PR TITLE
Add openshift-cherrypick-robot to approvers

### PR DESCRIPTION
**Pull request by cardil**
As title says

### CODE REVIEW

**Comment by cardil** [comment]
Adding @openshift-cherrypick-robot to approvers allow us to utilize the `cherrypick` chatops command. The cherrypick robot will create already approved PR, that the author could LGTM to get it fixed.

That allows for faster merging of already reviewed changesets.

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
