### PR TITLE
[TEST ONLY] [WIP] Kafka sink source continual test traces

### PR DESCRIPTION
**Pull request by mgencur**
Only for testing purposes to get traces for the failing KafkaSinkSourceContinualTest

Fixes JIRA #

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by pierDipi** [comment]
worked, retesting
/test 4.6-upgrade-tests-aws-ocp-46
/test 4.11-upgrade-tests-aws-ocp-411

**Comment by pierDipi** [comment]
Worked, retesting
/test 4.11-upgrade-tests-aws-ocp-411

**Comment by pierDipi** [comment]
worked, retesting
/test 4.6-upgrade-tests-aws-ocp-46

**Comment by pierDipi** [comment]
worked, retesting
/test 4.6-upgrade-tests-aws-ocp-46
/test 4.11-upgrade-tests-aws-ocp-411

**Comment by pierDipi** [comment]
Unrelated:
```
16:03:49.709 ERROR:   🚨 Error (code: 141) occurred at ./hack/lib/tracing.bash:20, with command: zipkin_node=$(oc get node -l 'node-role.kubernetes.io/worker' -oname | head -1)
16:03:49.710 ERROR:   Stack trace:
16:03:49.715 ERROR:    1: ./hack/lib/tracing.bash:6 dedicate_node_to_zipkin(...)
16:03:49.720 ERROR:    2: ./hack/tracing.sh:15 install_tracing(...)
make: *** [test-upstream-upgrade] Error 141
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-09-26T16:03:49Z"}
error: failed to execute wrapped command: exit status 2 
INFO[2022-09-26T16:03:51Z] Step upgrade-tests-aws-ocp-46-serverless-e2e failed after 40s. 
INFO[2022-09-26T16:03:51Z] Step phase test failed after 40s.            
INFO[2022-09-26T16:03:51Z] Running multi-stage phase post  
```

**Comment by pierDipi** [comment]
Worked, retesting
/test 4.11-upgrade-tests-aws-ocp-411

**Comment by mgencur** [comment]
@pierDipi We're hitting the bug pretty consistently in other PRs where all tests run in parallel (for example: https://github.com/openshift-knative/serverless-operator/pull/1734) But here we cannot reproduce. Sounds like it's related to overloaded Kafka Cluster. I'm trying one more run and then will enable other Kafka tests as well but remove "downgrades" to shorten the test, and possibly prevent OOM issues in Zipkin.

**Comment by pierDipi** [comment]
@mgencur I sent 2 PRs to increase Kafka stability:
- https://github.com/openshift-knative/serverless-operator/pull/1736
- https://github.com/openshift-knative/serverless-operator/pull/1737

**Comment by mgencur** [comment]
Now a different test fails, I just looked at event traces
step-6530.json - this trace ends at the dispatcher, with no additional error
step-6427.json - this trace is complete from sender to receiver, even though the event is reported as missed

/test 4.11-upgrade-tests-aws-ocp-411

**Pull request closed without merging**
