### PR TITLE
kafkachannel-v0.20.0.yaml resources update

### PR DESCRIPTION
**Pull request by maschmid**
manually updated based on https://github.com/openshift-knative/eventing-kafka/commit/b4b19340399f61cb36a19b0f41e0e585e9736fbf

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
Is this something we should "patch" in the future?  When updating the resources?

Or will 0.21 have those already, when we do next update?

**Comment by maschmid** [comment]
There is a PR to automate it for 0.21  https://github.com/openshift-knative/serverless-operator/pull/831/

**Pull request merged**
