### PR TITLE
Try to enable conformance tests for eventing

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

as per title

/assign @mgencur

### CODE REVIEW

**Comment by markusthoemmes** [comment]
upgrade test had the issue I pinged about.  A rebase should fix that.

**Comment by matzew** [comment]
ah, the tracing tests fail :-)

**Comment by matzew** [comment]
updated eventing src image https://github.com/openshift/knative-eventing/pull/1240/files

**Pull request merged**
