### PR TITLE
[main][SRVKS-1286] Override activator termination grace perio…

### PR DESCRIPTION
**Pull request by skonto**
Fixes JIRA #

## Proposed Changes

- Similar to https://github.com/openshift-knative/serverless-operator/pull/3011

### CODE REVIEW

**Comment by dsimansk** [comment]
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / pr group cherry-pick-3013-to-main"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-bundle-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-ingress-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-kn-operator-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-metadata-webhook-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-must-gather-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-openshift-kn-operator-135"

**Comment by dsimansk** [comment]
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / pr group fix_override_act_tgp_main"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-ingress-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-kn-operator-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-metadata-webhook-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-must-gather-135"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-openshift-kn-operator-135"

**Comment by skonto** [comment]
```
Message:Waiting on StatefulSets} {Type:StatefulSetsAvailable Status:False Severity: LastTransitionTime:{Inner:2024-11-14 15:17:27 +0000 UTC} Reason:NotReady Message:Waiting on StatefulSets}] Annotations:map[]} Version:1.15}}: context deadline exceeded
```

**Comment by skonto** [comment]
Accidently re-run the job. It has passed [here](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-knative_serverless-operator/3017/pull-ci-openshift-knative-serverless-operator-main-417-test-upgrade-aws-417/1856995652349726720)

**Pull request merged**
