### PR TITLE
Update client to v1.10.0

### PR DESCRIPTION
**Pull request by dsimansk**
Per title. Serverless 1.31.0 release preps.

/cc @rhuss @ReToCode @skonto

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

depends on https://github.com/openshift-knative/serverless-operator/pull/2291

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by dsimansk** [comment]
@ReToCode thanks for a quick rebase! 🤞

**Pull request merged**
