### PR TITLE
[SRVKS-911] Deploy config-network configmap into knative-serving-ingress namespace

### PR DESCRIPTION
**Pull request by nak3**
This patch is an alternative solution for SRVKS-911.

Since upstream net-kourier controller starts watching config-network
configmap. The configmap and controller must be deploeyd in the same
namespace.

Initially I tried to move net-kourier into knative-serving namespace
as https://github.com/openshift-knative/serverless-operator/pull/1483 but deploy config-network in the ingress namespace is much simpler.

### CODE REVIEW

**Comment by nak3** [comment]
/retest

Eventing error [log](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1495/pull-ci-openshift-knative-serverless-operator-main-4.10-upgrade-tests-aws-ocp-410/1514053853140488192)

**Comment by nak3** [comment]
@skonto @rhuss Would you mind taking a look? This change needs the future version (Knative 1.25) but no harm to merge beforehand.

**Comment by skonto** [comment]
@nak3 
> This change needs the future version (Knative 1.25) but no harm to merge beforehand.
Do you mean 1.2.5?

**Comment by nak3** [comment]
> Do you mean 1.2.5?

Ah sorry, it means Serverless 1.25 (Knative 1.4).

**Comment by skonto** [comment]
```
Failed  === RUN   TestServerlessUpgrade/VerifyContinualTests/KafkaSinkSourceContinualTest
2022-05-12T13:38:42.651Z	INFO	upgrade/steps.go:95	8.7) Verifying "KafkaSinkSourceContinualTest".
2022-05-12T13:38:42.670Z	INFO	upgrade/functions.go:110	KafkaSinkSourceContinualTest have received a stop event: Stop of KafkaSinkSourceContinualTest
2022-05-12T13:38:42.671Z	INFO	prober/sender.go:95	Remove of sender deployment: wathola-sender
2022-05-12T13:38:48.710Z	INFO	prober/verify.go:64	Waiting for complete report from receiver...
2022-05-12T13:38:48.710Z	INFO	prober/verify.go:231	Deploying
```
@nak3 needs rebasing? @pierDipi seen this before?

**Comment by nak3** [comment]
(Just Rebased)

**Pull request merged**
