### PR TITLE
Update assorted dependencies

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title, keeping a few dependencies recent. Gonna look at bumping logr in a separate PR potentially.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/retest

Infra

**Comment by markusthoemmes** [comment]
/retest

Alert for EventingKafka. Informed the eventing team.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

the upstream-e2e has a fixing PR already attached... so here we go

**Pull request merged**
