### PR TITLE
Use knative-main as tag for webhook

### PR DESCRIPTION
**Pull request by ReToCode**
## Proposed Changes
- Use knative-main as tag for webhook
- Fixes the failing mesh tests

/assign @skonto

### CODE REVIEW

**Comment by ReToCode** [comment]
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / pr group fix-metadata-webhook"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / serverless-must-gather-135"

**Comment by skonto** [comment]
Eventing tests failed. @ReToCode should we re-run or just override?

**Comment by ReToCode** [comment]
> Eventing tests failed. @ReToCode should we re-run or just override?

I'm fine with both

**Pull request merged**
