### PR TITLE
SRVCOM-2642 Include must-gather image in CSV relatedImages

### PR DESCRIPTION
**Pull request by mgencur**
Fixes https://issues.redhat.com/browse/SRVCOM-2642

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by Kaustubh-pande** [comment]
I think we can cherry pick in 1.32 as well, with 1.32.1 it should get resolved.
/lgtm

**Comment by mgencur** [comment]
Let's minimize the payload for 1.32.1. We can include this in 1.33. The fix is only required for OCP 4.16 and 1.32.1 is not supported there yet.

**Pull request merged**
