### PR TITLE
Add eventings 0.23 2nd try

### PR DESCRIPTION
**Pull request by aliok**
Redoing https://github.com/openshift-knative/serverless-operator/pull/1070

### CODE REVIEW

**Comment by aliok** [comment]
/test 4.7-upgrade-tests-aws-ocp-47

Upgrade tests fail:
```
TestServerlessUpgrade
TestServerlessUpgrade/VerifyContinualTests
```

**Comment by aliok** [comment]
/test 4.7-upgrade-tests-aws-ocp-47

Again upgrade tests failed

**Comment by aliok** [comment]
@cardil any idea about this failure?
```
Run multi-stage test upgrade-tests-aws-ocp-47 - upgrade-tests-aws-ocp-47-ipi-deprovision-deprovision container test 
```

**Comment by markusthoemmes** [comment]
It's an infra failure

**Comment by cardil** [comment]
But, previous build failed with missed events 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1100/pull-ci-openshift-knative-serverless-operator-main-4.7-upgrade-tests-aws-ocp-47/1415249101880037376

I vote not to merge without fixing the issue.

/hold

**Comment by lberk** [comment]
thanks for the pointer @cardil 
I'm having trouble figuring out which logs to look at to diagnose the failed upgrade tests
in: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1100/pull-ci-openshift-knative-serverless-operator-main-4.7-upgrade-tests-aws-ocp-47/1415249101880037376/artifacts/upgrade-tests-aws-ocp-47/serverless-e2e/artifacts/build-2okftYL3/pod-logs/
should I be looking in:

`test-serverless-upgrade-post-upgrade-tests-eventing-post-u6jwvd/`

or

`test-serverless-upgrade-post-upgrade-tests-eventing-post-umnm4q/`

I'm not sure I can diagnose the issue from the logs from either artifact direction, do you have any suggestions? thanks for the help!

**Comment by cardil** [comment]
I don't think you will find something useful in any of those.

I think to lookup where do the events are being dropped we need to set log level to debug for eventing components and look at eventing components logs to see what is happening.

**Comment by matzew** [comment]
/close
b/c of https://github.com/openshift-knative/serverless-operator/pull/1126

**Pull request closed without merging**
