### PR TITLE
Add infrastructure-features disconnected

### PR DESCRIPTION
**Pull request by warrenvw**
For more information, see https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Duplicate of https://github.com/openshift-knative/serverless-operator/pull/1136?

**Review by rhuss — COMMENTED** [review]
/approve
/lgtm

According to https://docs.openshift.com/container-platform/4.6/operators/operator_sdk/osdk-generating-csvs.html there is also a "proxy-aware" which I wonder whether could add it too ?

**Comment by markusthoemmes** [comment]
#1136 sets proxy-aware and fips as well.

/hold

**Comment by warrenvw** [comment]
Yes, thanks @markusthoemmes. We can close this PR and go with #1136.

**Pull request closed without merging**
