### PR TITLE
[release-1.31] Ignore no match errors on deleting obsolete resources

### PR DESCRIPTION
**Pull request by pierDipi**
Patch related https://github.com/knative/operator/pull/1749/files

This issue is not affecting functionality, it's a warning, so we can include it in a future 1.31.x release

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
```
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: www.gtlib.gatech.edu
 * epel: dl.fedoraproject.org
 * extras: mirror.ette.biz
 * updates: mirror.pit.teraswitch.com
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 
```

**Comment by ReToCode** [comment]
I don't think we have back-ported https://github.com/openshift-knative/serving/pull/644 to 1.10. Did you do that for Eventing?

**Comment by ReToCode** [comment]
And also [this](https://github.com/openshift-knative/serverless-operator/pull/2534) I think?

**Comment by pierDipi** [comment]
> I don't think we have back-ported [openshift-knative/serving#644](https://github.com/openshift-knative/serving/pull/644) to 1.10. Did you do that for Eventing?

@creydr you know?

**Comment by creydr** [comment]
> > I don't think we have back-ported [openshift-knative/serving#644](https://github.com/openshift-knative/serving/pull/644) to 1.10. Did you do that for Eventing?
> 
> @creydr do you know?

No only back to 1.11 yet: https://github.com/openshift-knative/eventing/pull/553#issuecomment-1976647779

**Comment by ReToCode** [comment]
> This issue is not affecting functionality, it's a warning, so we can include it in a future 1.31.x release

So we can either back-port all the fixes to 1.10 as well, or hold this PR until we actually do 1.31.x? WDYT?

**Comment by pierDipi** [comment]
```
package slices: unrecognized import path "slices": import path does not begin with hostname
09:30:22.144 ERROR:   🚨 Error (code: 1) occurred at /go/src/github.com/openshift-knative/serverless-operator/hack/lib/testselect.bash:5, with command: GO111MODULE=off go get github.com/openshift-knative/hack/cmd/testselect
```

**Pull request closed without merging**
