### PR TITLE
Eventing core 1.10 bump

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

- as per title

### CODE REVIEW

**Comment by ReToCode** [comment]
You'll probably also need https://github.com/openshift-knative/serverless-operator/pull/2182 to make upgrade tests pass.

**Comment by matzew** [comment]
Thanks for the heads, up @ReToCode

**Comment by matzew** [comment]
Rebased this PR

**Comment by matzew** [comment]
```
    user_permissions.go:51: Unexpected error creating eventing.knative.dev/v1, Resource=brokers, allowed = false, err = <nil>

```

that does not make sense. Or was there some change I am not aware of?

**Comment by pierDipi** [comment]
On https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/2181/pull-ci-openshift-knative-serverless-operator-main-4.13-operator-e2e-aws-ocp-413/1686087370740338688/artifacts/operator-e2e-aws-ocp-413/gather-extra/artifacts/pods.json

```
                "containerStatuses": [
                    {
                        "image": "quay.io/openshift-knative/knative-eventing-storage-version-migration:knative-v1.10",
                        "imageID": "",
                        "lastState": {},
                        "name": "migrate",
                        "ready": false,
                        "restartCount": 0,
                        "started": false,
                        "state": {
                            "waiting": {
                                "message": "Back-off pulling image \"quay.io/openshift-knative/knative-eventing-storage-version-migration:knative-v1.10\"",
                                "reason": "ImagePullBackOff"
                            }
                        }
                    }
                ],
```

1.10 image is not mirrored https://quay.io/repository/openshift-knative/knative-eventing-storage-version-migration?tab=tags&tag=knative-v1.10

**Comment by matzew** [comment]
this fails:

```
podman pull registry.ci.openshift.org/openshift/knative-eventing-storage-version-migration:knative-v1.10
Trying to pull registry.ci.openshift.org/openshift/knative-eventing-storage-version-migration:knative-v1.10...
Error: initializing source docker://registry.ci.openshift.org/openshift/knative-eventing-storage-version-migration:knative-v1.10: reading manifest knative-v1.10 in registry.ci.openshift.org/openshift/knative-eventing-storage-version-migration: manifest unknown
➜  ~ 
```

**Comment by matzew** [comment]
/close

let's do it via #2192

**Pull request closed without merging**
