### PR TITLE
[WIP]  Run Knative Kafka upstream e2e tests first and then serving and eventing

### PR DESCRIPTION
**Pull request by aliok**
Bases https://github.com/openshift-knative/serverless-operator/pull/579

### CODE REVIEW

**Comment by aliok** [comment]
/test 4.5-upstream-e2e-aws-ocp-45

Serving and eventing tests fail now, when we execute the Kafka tests first.

OR, maybe it is just bad luck (races + flakes)

```
[scaling/autoscaler.go:230] [serving-tests/autoscale-up-down-up-clwvywdp-gh9mf] Operating in panic mode.
...
...
Pod test-event-transformation-for-subscription-in-memory-chann4x54c e2e-eventtransformation-transformation-pod 5be9685c-ad22-43dd-9929-67fc945de474 v1 255232 } FailedMount MountVolume.SetUp failed for volume "default-token-cg5v2" : failed to sync secret cache: timed out
...
...
=== FAIL: test/conformance TestChannelStatus/InMemoryChannel-messaging.knative.dev/v1 (3.16s)
    test_runner.go:148: namespace is : "test-channel-status-in-memory-channel-messaging-knative-de5gtsd"
    channel_status_test_helper.go:46: Running channel status conformance test with channel {"InMemoryChannel" "messaging.knative.dev/v1"}
    channel_status_test_helper.go:50: Creating channel {Kind:InMemoryChannel APIVersion:messaging.knative.dev/v1}-channel-req-status
    creation.go:77: Creating channel &TypeMeta{Kind:InMemoryChannel,APIVersion:messaging.knative.dev/v1,}-channel-req-status
    channel_status_test_helper.go:87: {"InMemoryChannel" "messaging.knative.dev/v1"} does not have status.address
skipped 55 lines unfold_more
            ],
            "observedGeneration": 1
          }
        }
```

**Comment by matzew** [comment]
all green

/test all

to do it again

**Comment by aliok** [comment]
/test 4.5-upstream-e2e-aws-ocp-45

Failed

**Comment by matzew** [comment]
/close 
because of #581

**Pull request closed without merging**
