### PR TITLE
Issues/srvke 1290

### PR DESCRIPTION
**Pull request by matzew**
Fixes [SRVKE-1290](https://issues.redhat.com/browse/SRVKE-1290)

## Proposed Changes

- exclude those pods that are not considered HA/production, since we now ship Kafka for actual prod.

### CODE REVIEW

**Comment by matzew** [comment]
/hold
we do this _after_ we have cut for 1.28, so that this will land in 1.29

/cc @maschmid

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
