### PR TITLE
SRVKE-1065 Add Broker post-upgrade test

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.redhat.com/browse/SRVKE-1065

Including only the post-upgrade test now because we're currently upgrading from a version that doesn't have the Kafka broker functionality. For the next release, we should also include the pre-upgrade and continual upgrade test.

### CODE REVIEW

**Comment by pierDipi** [comment]
`Validate / Generated files are commited (pull_request) ` failed https://github.com/openshift-knative/serverless-operator/runs/4503327670?check_suite_focus=true

**Comment by mgencur** [comment]
/hold
There are vendored changes which need to be removed when https://github.com/knative-sandbox/eventing-kafka-broker/pull/1591 is properly backported.

**Comment by mgencur** [comment]
/hold cancel
The vendor directory has been fixed as well as https://issues.redhat.com/browse/SRVKE-1087 (upgrade tests now passing)

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
