### PR TITLE
Refactor patch response from raw

### PR DESCRIPTION
**Pull request by aliok**
Bases on https://github.com/openshift-knative/serverless-operator/pull/213

Hold until that's merged

### CODE REVIEW

**Comment by aliok** [comment]
/hold 

Bases on https://github.com/openshift-knative/serverless-operator/pull/213

Hold until that's merged

**Comment by aliok** [comment]
/unhold

cc @markusthoemmes

**Comment by aliok** [comment]
/retest

@markusthoemmes can you manually merge this one? I can't do it

**Comment by markusthoemmes** [comment]
@aliok I'll merge once at least some of the e2e tests are happy.

**Pull request merged**
