### PR TITLE
Bump golang version to 1.21

### PR DESCRIPTION
**Pull request by ReToCode**
## Proposed changes
- Bump golang to 1.21
- Discussion https://redhat-internal.slack.com/archives/CD87JDUB0/p1705568471637659

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm

We will probably need to merge manually and verify this after merge as build-image is not reflected until merged

**Comment by pierDipi** [comment]
Hack repo bump https://github.com/openshift-knative/hack/pull/102

**Comment by pierDipi** [comment]
Eventing core bump https://github.com/openshift-knative/eventing/pull/498

**Comment by ReToCode** [comment]
@pierDipi is this ok to merge or more PRs on dependant repos needed?

**Comment by pierDipi** [comment]
There is more

**Comment by pierDipi** [comment]
Eventing PRs merged

**Comment by ReToCode** [comment]
> Eventing PRs merged

Ok, Serving is depending on this being merged, so I'm merging this.

**Pull request merged**
