### PR TITLE
Confirm upgrade of knativeserving version from hard-coded value

### PR DESCRIPTION
**Pull request by rhuss**
1.7 backport for PR #360

@nak3 @markusthoemmes quick review please ?

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm

Is it possible to pick up https://github.com/openshift-knative/serverless-operator/pull/359 to this PR or vice versa to confirm this PR fixes the issue?

**Comment by nak3** [comment]
```
sed: can't read /go/src/github.com/openshift-knative/serverless-operator/knative-operator/vendor/knative.dev/operator/version/version.go: No such file or directory
INFO 13:09:18.202 updating serving version from 0.13.2 to
```

Ugh... release-1.7 branch does not use `knative.dev/operator` so the file path is wrong... It should be `knative-operator/vendor/knative.dev/serving-operator/version/version.go`.

**Comment by rhuss** [comment]
I see. Lemme fix. thanks for the heads up @nak3

**Comment by rhuss** [comment]
@nak3 I think it wouldn't harm anyway and as soon as we merge this PR #359 should then be rebased on this fix, and the re-running CI tests will then tell us.

**Comment by rhuss** [comment]
/retest ci/prow/4.5-e2e-aws-ocp-45 

Looks like the cluster didn't came up ...

**Comment by rhuss** [comment]
@markusthoemmes @jcrossley3 @nak3 

Before I do blindly a retest, could please someone give me some tips how to do the forensics ? I'm staring into the logs but can't spot the errors:

* What should I look/search for ? (keywords)
* How to unroll an error ?
* Can this be done from the overview or do I need to dig into the raw logs ?

There's so much noise in the 11.3 MB logs ...

**Comment by rhuss** [comment]
For the two flow tests, seems to be a timeout, but for the other tests can't find the issue (the one name "template" something)

**Comment by markusthoemmes** [comment]
`ci/prow/4.3-e2e-aws-ocp-43` seems to be `/usr/local/go/pkg/tool/linux_amd64/vet: signal: terminated`. I've never seen that before, it seems to be a flake in `go build` or `go test`. Tests passed fine there though.

`ci/prow/4.4-e2e-aws-ocp-44` is just the test-case failures. The `test` stage just fails with that, but if you have test case failures, that's expected and "right". You can ignore that extra entry.

**Comment by nak3** [comment]
/retest

setup issue.

**Pull request merged**
