### PR TITLE
Tests for Multi Tenancy with Service Mesh

### PR DESCRIPTION
**Pull request by pierDipi**
Based on https://github.com/openshift-knative/serverless-operator/pull/2198

Fixes https://issues.redhat.com/browse/SRVCOM-2522

## Proposed Changes
Partial PR with changes from https://github.com/openshift-knative/serverless-operator/pull/2126:

- Rewrite tests from https://github.com/ReToCode/knative-multitenancy in Golang. They're under test/servinge2e/servicemesh/
- Remove TestKnativeVersusKubeServicesInOneNamespace as it's redundant. Having Knative and k8s service in one namespace is tested with all Eventing tests which now include KSVC in the test scenarios.
- This PR doesn't include any tests for verifying cross-tenant traffic for Eventing. They depend on https://github.com/knative/eventing/pull/7048 to be merged and backported.
- Split the test webhook under serving/metadata-webhook into cluster-resources and namespaced-resources. The second one needs to be applied with `-n <namespace>`. This is to reduce duplication of code because the webhook is now used in two namespaces: serving-tests, serverless-tests.

**TODOs in follow up PRs**

- Eventing MT tests
- Generate authz policies for the tests from the chart container image during `make genarated-files`
- migrate to use `mtls: true` on the SMCP

### CODE REVIEW

**Comment by pierDipi** [comment]
Previous failure due to `POST` method restriction, to be removed in the chart:

```
=== CONT  TestBrokerConformance/Knative_Broker_Specification_-_Data_Plane/Ingress/Assert/Conformance_Brokers_MUST_reject_all_HTTP_produce_requests_with_a_method_other_than_POST_responding_with_HTTP_status_code_`405_Method_Not_Supported`.
    data_plane.go:350: Expected statuscode 405 for sequence 1 got 403
            --- FAIL: TestBrokerConformance/Knative_Broker_Specification_-_Data_Plane/Ingress/Assert/Conformance_Brokers_MUST_reject_all_HTTP_produce_requests_with_a_method_other_than_POST_responding_with_HTTP_status_code_`405_Method_Not_Supported`. (39.36s)
```

**Comment by pierDipi** [comment]
Tests are timing out after 4h

**Comment by pierDipi** [comment]
https://github.com/openshift/release/pull/41818

**Comment by pierDipi** [comment]
Passed on 4.10

/test 4.13-upstream-e2e-mesh-aws-ocp-413

**Comment by pierDipi** [comment]
APIServer was down: 
```
"https://172.30.0.1/api/v1/namespaces/serverless-tests/pods/t1dlq-mrgeuoyk": dial tcp 172.30.0.1:443: connect: connection refused"
```

/test 4.13-upstream-e2e-mesh-aws-ocp-413

**Comment by pierDipi** [comment]
From https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/2199/pull-ci-openshift-knative-serverless-operator-main-4.13-upstream-e2e-mesh-aws-ocp-413/1686285486018007040/artifacts/upstream-e2e-mesh-aws-ocp-413/gather-extra/artifacts/pods/serverless-tests_subject-ifdweahz-f6555bd94-dfpmv_user-container.log

```
2023/08/01 11:15:59 sending cloudevent to http://sink-uzbhnbft.serverless-tests.svc.cluster.local
2023/08/01 11:16:45 failed to send cloudevent: 503:  (10x)
```

**Comment by pierDipi** [comment]
The failures are not related to the authorization policies, generally, those tests are pretty flaky already but one run on 4.10 succeeded https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/2199/pull-ci-openshift-knative-serverless-operator-main-4.10-upstream-e2e-mesh-aws-ocp-410/1686049565687418880, so I think we can merge this PR

/cc @ReToCode @mgencur

**Comment by pierDipi** [comment]
eventing tests flaky reason is that tests' resources are not cleaned up, so the cluster is packed of resources, so sometimes pods just get evicted (we use raw pods in tests).

This will be hopefully fixed by 1.11 and if we really want we can invest some time into backporting the fixes

**Review by ReToCode — APPROVED** [review]
I'm fine with merging [this](https://github.com/openshift-knative/serverless-operator/pull/2199#issuecomment-1661911479). Mesh tests are already pretty flaky and we have to continue to improve them anyway. It might be good to do it before 1.11 to see where we stand with our mesh changes for the 1.31 release (which is 1.10).

I'll (try) to do the backports and do an additional PR on top here to use `mtls: true`, enable the new generation script and see if those back-ports make the tests more stable.

/lgtm
/approve

**Pull request merged**
