### PR TITLE
[WIP] Adjust rollout settings to minimize Kourier rollout impact.

### PR DESCRIPTION
**Pull request by markusthoemmes**
Playing with this to see if it helps our TestProbe flakes (and thus the users during rollout).

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/test 4.4-upgrade-tests-aws-ocp-44
/test 4.5-upgrade-tests-aws-ocp-45

Both passed, let's see if that was just luck.

**Comment by markusthoemmes** [comment]
/test 4.3-upgrade-tests-aws-ocp-43

Infra issues!

**Comment by markusthoemmes** [comment]
/test 4.3-upgrade-tests-aws-ocp-43

Infra issues.

**Comment by markusthoemmes** [comment]
/retest

A few failures, but veeery low failure rates. Let's try to gather more data.

**Comment by nak3** [comment]
I agree that it is worth to use the options. Should we add these options to upstream net-kourie as well? Or we just use it for the workaround of the tests in unsupported grace shutdown?
/cc @jmprusi

**Comment by markusthoemmes** [comment]
@nak3 I was thinking the latter but obviously it doesn't make it 100% tight.

**Comment by nak3** [comment]
I see. Then, let's merge this PR.

/lgtm

**Comment by jmprusi** [comment]
> I agree that it is worth to use the options. Should we add these options to upstream net-kourie as well? Or we just use it for the workaround of the tests in unsupported grace shutdown?
> 
> /cc @jmprusi

In upstream we have a pre stop hook, I was planning on adding some sleep after setting the envoy as not ready and also tweak the rollout process, but I need to run some tests first to avoid making it worse.

**Pull request closed without merging**
