### PR TITLE
Fix upgrade tests with ServiceMesh

### PR DESCRIPTION
**Pull request by mgencur**
This is to test https://issues.redhat.com/browse/SRVKS-1080 and to see if this still happens

Fixes JIRA #

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by mgencur** [comment]
The upgrade test is now passing.
I will remove the alias `test-upgrade: test-upgrade-with-mesh` and get this PR ready for merging with the next commit.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
