### PR TITLE
Run testselect on demand

### PR DESCRIPTION
**Pull request by mgencur**
Not on every sourcing of the testselect.bash script

[Slack discussion](https://redhat-internal.slack.com/archives/CD87JDUB0/p1678950369048289)

## Proposed Changes

-
-
-

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by mgencur** [comment]
Hmm, not resolved yet:
```
 Cloning into bare repository 'openshift-knative/serverless-operator/.git'...
Note: checking out 'fc1359f958d1d0a81ea48ad6d6e2968ae9dc96d2'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b new_branch_name
HEAD is now at fc1359f... Use GOPATH for running testselect (#2003)
fatal: Not a git repository (or any of the parent directories): .git
2023/03/16 13:28:48 Error reading diff failed to run git [fetch https://github.com/openshift-knative/serverless-operator.git a66505acc0bb7a133fcb9702f242010b3eb56eea]: exit status 128
13:28:48.193 ERROR:   🚨 Error (code: 1) occurred at /go/src/github.com/openshift-knative/serverless-operator/hack/lib/testselect.bash:19, with command: "${GOPATH}/bin/testselect" --testsuites="${rootdir}/test/testsuites.yaml" --clonerefs="${ARTIFACT_DIR}/clonerefs.json" --output="${ARTIFACT_DIR}/tests.txt" 
```

**Comment by mgencur** [comment]
The testselect uses `--mirror` for cloning the repo. It clones the repo but when going inside the directory commands such as "git checkout" don't work. It previously worked because the repo was cloned inside "another" git repo. So the git commands worked. Now it runs in a temp directory which is not a git repo in itself. So git commands don't work. This might need a fix in testselect in openshift-knative/hack.

**Comment by mgencur** [comment]
This PR depends on https://github.com/openshift-knative/hack/pull/38

**Comment by mgencur** [comment]
The failures are unrelated to this PR. I can see this:
```
09:03:48.501 INFO:    Tests to be run:
All
```
Which is a sign that the testselect ran successfully.

**Pull request merged**
