### PR TITLE
Add readiness and liveness probes

### PR DESCRIPTION
**Pull request by skonto**
- Follows the approach [here](https://github.com/kubernetes-sigs/controller-runtime/pull/856). Tested with a deployment. Uses the standard paths: `/livez` & `/readyz`, exposed by c-r. 
- We need this especially for integration tests to make sure everything is setup (monitoring is not covered due to the lack of this).
/cc @markusthoemmes @aliok

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/test 4.6-upgrade-tests-aws-ocp-46

For once I'd like to see upgrade test passing.

**Comment by skonto** [comment]
@markusthoemmes all tests passed but it failed again.

**Comment by skonto** [comment]
@markusthoemmes I think we can merge this one.

**Comment by markusthoemmes** [comment]
I'd like the upgrade test to at least run once. Damn infra issues...

/test 4.6-upgrade-tests-aws-ocp-46

**Comment by skonto** [comment]
Right now we are hitting the issue of the leader deadlock when using osdk: new pod passes Become if it becomes a leader but the old pod will not release that lock until the new pod becomes ready which will never happen.

**Comment by skonto** [comment]
```
21:20:04.620 INFO:    Wait for the index pod to be up to avoid inconsistencies with the catalog source.
21:20:04.622 DEBUG:   [[ $(oc get pods -l app=serverless-index -n openshift-marketplace -o name | wc -l) == '0' ]] : Waiting until non-zero (max 300 sec.)
done
21:20:15.764 DEBUG:   [[ $(oc get pods -l app=serverless-index -n openshift-marketplace -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != 'True' ]] : Waiting until non-zero (max 300 sec.)
.............................................................................................................................................................................................................................................................................................................
22:21:47.084 ERROR:   Time out of 300 exceeded```

**Comment by markusthoemmes** [comment]
^^ Is a compile error in eventing, supposed to be fixed via https://github.com/openshift/knative-eventing/pull/957. Sadly we need to wait for this as this hasn't yet tested upgradeability at this point.

**Comment by markusthoemmes** [comment]
/retest

Compile error is hopefully gone.

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

Off you go!

**Pull request merged**
