### PR TITLE
SRVCOM-2356: Use specific labels for Knative gateways to omit conflict

### PR DESCRIPTION
**Pull request by pierDipi**
This is extracting independent changes from https://github.com/openshift-knative/serverless-operator/pull/2183 to help debugging

## Proposed Changes

- Use specific labels for Knative gateways to omit conflict

### CODE REVIEW

**Comment by pierDipi** [comment]
@ReToCode will make a PR with more changes extracted from https://github.com/openshift-knative/serverless-operator/pull/2183

**Comment by ReToCode** [comment]
Here it is: https://github.com/openshift-knative/serverless-operator/pull/2196

**Pull request closed without merging**
