### PR TITLE
[SRVCOM-961] Auto-create serving and eventing namespaces

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title.

Creating the namespaces seems to be relatively low risk as the chance of running into conflicts etc. is much less vs. auto-creating the CRs themselves.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/hold

Until the discussion on the dev list is done and this is actually agreed upon.

**Comment by markusthoemmes** [comment]
/unhold

People seem fine with this.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by markusthoemmes** [comment]
/hold

To figure out if the quickstart guides need to change.

**Pull request merged**
