### PR TITLE
Configure resource requests for Kafka cluster

### PR DESCRIPTION
**Pull request by pierDipi**
Increase Kafka cluster stability.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by pierDipi** [comment]
Unrelated: 
image

/retest

**Comment by mgencur** [comment]
/lgtm
/hold
Hold for tests.

**Comment by pierDipi** [comment]
```
                        "message": "0/6 nodes are available: 3 Insufficient cpu, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }. preemption: 0/6 nodes are available: 3 No preemption victims found for incoming pod, 3 Preemption is not helpful for scheduling.",
```

**Comment by pierDipi** [comment]
Worked, retesting
/test 4.11-upgrade-tests-aws-ocp-411

**Comment by matzew** [comment]
/lgtm

Are these numbers coming from some suggestion?

**Pull request merged**
