### PR TITLE
Ekb bump 1.7

### PR DESCRIPTION
**Pull request by matzew**
Fixes JIRA #

## Proposed Changes

- just EKB 1.7 bump
-
-

### CODE REVIEW

**Comment by matzew** [comment]
Just a test, for isolation /cc @ReToCode

**Comment by matzew** [comment]
`TestSourceToKafkaChanelToKnativeService` (wip...)

/test 4.11-operator-e2e-aws-ocp-411

**Comment by matzew** [comment]
`TestActivatorHAGraceful`

/test 4.11-upstream-e2e-aws-ocp-411

**Comment by ReToCode** [comment]
`TestSourceToKafkaChanelToKnativeService`

/test 4.11-operator-e2e-aws-ocp-411

**Comment by ReToCode** [comment]
TestSourceToKafkaChanelToKnativeService

/test 4.11-operator-e2e-aws-ocp-411

**Comment by ReToCode** [comment]
It should work again (hopefully) after https://github.com/openshift-knative/serverless-operator/pull/1893 is merged.

**Comment by matzew** [comment]
merging manually: errors are _not_ related to failures. Will investigate separately

**Pull request merged**
