### PR TITLE
[release-1.21] Fix eventing post-install jobs

### PR DESCRIPTION
**Pull request by pierDipi**
Backports:
- https://github.com/openshift-knative/serverless-operator/commit/d8e589f8e3e6f8462c07dff7760584c01e1ae0d4
- https://github.com/openshift-knative/serverless-operator/commit/3a492d9c60f91bfcef85191fa95f616f2e52b85f

Bump project and replace versions for the 1.21.1 release.

### CODE REVIEW

**Comment by pierDipi** [comment]
This validate / lint errors isn't related see https://coreos.slack.com/archives/CD87JDUB0/p1649082942219109
```
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
  
  goroutine 1 [running]:
  github.com/go-critic/go-critic/checkers.init.9()
  	github.com/go-critic/go-critic@v0.6.1/checkers/checkers.go:58 +0x4b4
  
  Error: golangci-lint exit with code 2
  Ran golangci-lint in 144[84](https://github.com/openshift-knative/serverless-operator/runs/5829306414?check_suite_focus=true#step:7:84)ms
```

**Comment by pierDipi** [comment]
```
level=error
level=error msg=Error: Provider produced inconsistent result after apply
level=error
level=error msg=When applying changes to module.masters.aws_network_interface.master[0],
level=error msg=provider "registry.terraform.io/-/aws" produced an unexpected new value for
level=error msg=was present, but now absent.
level=error
level=error msg=This is a bug in the provider, which should be reported in the provider's own
level=error msg=issue tracker.
level=error
level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```
/test 4.9-upstream-e2e-aws-ocp-49

**Comment by pierDipi** [comment]
known flake fixed in a later version with Kafka Broker
```
                "finalizers": [
                    "kafka.brokers.eventing.knative.dev/serverless-tests-smoke-test-native-kafka-channel-broker"
                ],
```

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold
let's wait until we are sure this all works and passes CI tests

**Comment by pierDipi** [comment]
The job seems stuck
```
INFO[2022-04-05T13:08:56Z] Tagging ocp/4.5:upi-installer into pipeline:ocp-4.5-upi-installer. 
INFO[2022-04-05T13:08:56Z] Importing release image latest.              
INFO[2022-04-05T13:11:46Z] Imported release 4.8.35 created at 2022-03-14 21:36:22 +0000 UTC with 135 images to tag release:latest 
```
/test 4.8-operator-e2e-aws-ocp-48

**Comment by pierDipi** [comment]
```
Not mergeable. Job Lint has not succeeded.
```
Cherry pick of the fix https://github.com/openshift-knative/serverless-operator/pull/1469

**Comment by maschmid** [comment]
actual tests passed, merging forcefully

**Comment by matzew** [comment]
For the future, let's please bump metadata in separate PRs.  easier to track them that way...

**Pull request merged**
