### PR TITLE
Updated eventing operator 171

### PR DESCRIPTION
**Pull request by matzew**
For 1.7.1  all we need it use the 0.13.3 operator image.

All OTHER images are UNCHANGED - no fix/patch needed!

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Do we  not need to update the checkout target versions in `vars.bash`?

**Comment by matzew** [comment]
/hold

ah, ok - did not know - will check

**Comment by matzew** [comment]
/unhold

@markusthoemmes I've update the location vars, to point to the actual `tag` for the "openshift-v0.13.3" release

**Comment by matzew** [comment]
@markusthoemmes these serving tests failures, are they flake ?

**Comment by markusthoemmes** [comment]
AFAIK quay.io was down causing these issues.

**Comment by matzew** [comment]
ah, right - I heard about it

ok, thanks

**Comment by markusthoemmes** [comment]
Let's ignore the flake. It's a known one.

**Pull request merged**
