### PR TITLE
[SRVKE-1202] Remove KafkaBinding's podspecable ClusterRoleBinding

### PR DESCRIPTION
**Pull request by pierDipi**
This is basically the companion PR for
https://github.com/openshift-knative/eventing-kafka-broker/pull/201

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by pierDipi** [comment]
```
    autoscaler.go:63: Error:  interim scale didn't fulfill constraints: revision "serverless-upgrade-continual-te-nqinvkbc-00001" #replicas: 7, want at least: 9
```
afaik, known flake
/test 4.10-upgrade-tests-aws-ocp-410

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
@pierDipi we need this on 1.22 too

**Pull request merged**
