### PR TITLE
Adding worloadOverride, inherited from upstream, copying over the manifest bits

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes JIRA SRVKE-1205

## Proposed Changes

- adding the `workloads override` from upstream to `KnativeKafka`

### CODE REVIEW

**Comment by matzew** [comment]
PR was tested against OCP 4.12:

```
oc version
Client Version: 4.9.5
Server Version: 4.12.0-0.nightly-2022-10-25-210451
Kubernetes Version: v1.25.2+4bd0702
```

With the given `KnativeKafka` spec:

```yaml
...
spec:
  broker:
    defaultConfig:
      authSecretName: ""
      bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
      numPartitions: 10
      replicationFactor: 3
    enabled: true
  channel:
    authSecretName: ""
    authSecretNamespace: ""
    bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
    enabled: true
  high-availability:
    replicas: 1
  logging:
    level: INFO
  sink:
    enabled: true
  source:
    enabled: true
  workloads:
    - name: kafka-webhook-eventing
      replicas: 3
      labels:
        mylabel: foo
      annotations:
        myannotations: bar
    - name: kafka-controller
      replicas: 3
      labels:
        mylabel: foobar
      annotations:
        myannotations: barfor
    - name: kafka-broker-dispatcher
      replicas: 3
      labels:
        mylabel: zz
      annotations:
        myannotations: top
...
```

Resulting in:

```
➜  ~ oc get pods -n knative-eventing 
NAME                                                  READY   STATUS      RESTARTS   AGE
eventing-controller-f577d4588-2kz52                   2/2     Running     0          27m
eventing-controller-f577d4588-xc6zs                   2/2     Running     0          27m
eventing-webhook-588c8ff596-p6bdm                     2/2     Running     0          27m
eventing-webhook-588c8ff596-r69kd                     2/2     Running     0          27m
imc-controller-7b594796c-6glmj                        2/2     Running     0          27m
imc-controller-7b594796c-gsnwk                        2/2     Running     0          27m
imc-dispatcher-69b44f7499-7xg7k                       2/2     Running     0          27m
imc-dispatcher-69b44f7499-b9sh8                       2/2     Running     0          27m
kafka-broker-dispatcher-8867b4445-4b4cn               2/2     Running     0          40s
kafka-broker-dispatcher-8867b4445-9t97b               2/2     Running     0          4m19s
kafka-broker-dispatcher-8867b4445-qmrkq               2/2     Running     0          4m19s
kafka-broker-receiver-5ddc9cf8c-8kvb5                 2/2     Running     0          27m
kafka-channel-dispatcher-cf4bf4c8c-rvtqb              2/2     Running     0          27m
kafka-channel-receiver-8489b84456-bvwnh               2/2     Running     0          27m
kafka-controller-7d4b48464c-5q8wd                     2/2     Running     0          4m20s
kafka-controller-7d4b48464c-7j8bs                     2/2     Running     0          4m13s
kafka-controller-7d4b48464c-h9qlm                     2/2     Running     0          4m20s
kafka-controller-post-install-1.26.0-qgrjb            1/1     Running     0          6m38s
kafka-sink-receiver-54f7df8567-hzf7h                  2/2     Running     0          27m
kafka-source-dispatcher-86db84db8-rhsm4               2/2     Running     0          27m
kafka-webhook-eventing-cc6cb4878-dzhnm                2/2     Running     0          4m16s
kafka-webhook-eventing-cc6cb4878-g8xlc                2/2     Running     0          4m14s
kafka-webhook-eventing-cc6cb4878-jq594                2/2     Running     0          4m20s
knative-kafka-storage-version-migrator-1.26.0-wxv8n   0/1     Completed   0          7m6s
mt-broker-controller-7cd569688d-4mlnh                 2/2     Running     0          27m
mt-broker-controller-7cd569688d-75ph2                 2/2     Running     0          27m
mt-broker-filter-689b4cd9c-l2dqt                      2/2     Running     0          27m
mt-broker-filter-689b4cd9c-n4s65                      2/2     Running     0          27m
mt-broker-ingress-7ccbdd6c7b-c4xwq                    2/2     Running     0          27m
mt-broker-ingress-7ccbdd6c7b-swqmj                    2/2     Running     0          27m
➜  ~ 
```


and as an example the `deployment`:

```
k get deployments.apps kafka-broker-dispatcher -n knative-eventing -oyaml

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    knativekafkas.operator.serverless.openshift.io/ownerName: knative-kafka
    knativekafkas.operator.serverless.openshift.io/ownerNamespace: knative-eventing
    myannotations: top
  creationTimestamp: "2022-11-04T09:30:41Z"
  generation: 4
  labels:
    app: kafka-broker-dispatcher
    kafka.eventing.knative.dev/release: v1.5
    mylabel: zz
  name: kafka-broker-dispatcher
```

**Comment by pierDipi** [comment]
When I do this:
```
    - name: kafka-broker-dispatcher
      replicas: 3
      labels:
        mylabel: zz
      annotations:
        myannotations: top
```
is `myannotations: top` applied to pod level template?

**Comment by matzew** [comment]
yes, this is same as in upstream, for instance check the `myannotations` annotation or the `mylabel` label

```
k -n knative-eventing get pods kafka-broker-dispatcher-8867b4445-4b4cn -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.131.0.69/23"],"mac_address":"0a:58:0a:83:00:45","gateway_ips":["10.131.0.1"],"ip_address":"10.131.0.69/23","gateway_ip":"10.131.0.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.131.0.69"
          ],
          "mac": "0a:58:0a:83:00:45",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.131.0.69"
          ],
          "mac": "0a:58:0a:83:00:45",
          "default": true,
          "dns": {}
      }]
    myannotations: top
    openshift.io/scc: restricted-v2
    operator.knative.openshift.io/configmap-volume-checksum: 84893a4c
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2022-11-04T09:57:18Z"
  generateName: kafka-broker-dispatcher-8867b4445-
  labels:
    app: kafka-broker-dispatcher
    kafka.eventing.knative.dev/release: v1.5
    mylabel: zz
    pod-template-hash: 8867b4445
```

**Comment by pierDipi** [comment]
Cool, thanks! is this still WIP?

**Comment by pierDipi** [comment]
Cool, thanks! is this still WIP?

**Pull request merged**
