### PR TITLE
Move eventing-kafka-post-install to controller directory

### PR DESCRIPTION
**Pull request by pierDipi**
The `eventing-kafka-post-install` job should be applied when
any "new" broker-based components is used for general migrations,
so I'm moving it to the controller directory.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by pierDipi** [comment]
Flake
```
{Failed  === RUN   TestAutoscaleSustaining
--- FAIL: TestAutoscaleSustaining (257.61s)
}
```
/test 4.10-upstream-e2e-aws-ocp-410

**Comment by pierDipi** [comment]
/test 4.10-upgrade-tests-aws-ocp-410

```
WARN[2022-03-[29](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1442/pull-ci-openshift-knative-serverless-operator-main-4.10-upgrade-tests-aws-ocp-410/1508708953205248000#1:build-log.txt%3A29)T07:40:45Z] Unable to retrieve logs from failed build     error=builds.build.openshift.io "src" not found
INFO[2022-03-29T07:40:45Z] Ran for 7m0s                                 
ERRO[2022-03-29T07:40:45Z] Some steps failed:                           
ERRO[2022-03-29T07:40:45Z] 
  * could not run steps: step src failed: could not get build src: builds.build.openshift.io "src" not found
```
infra

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
