### PR TITLE
[SRVKS-1120] Use webhook context for secret data keys

### PR DESCRIPTION
**Pull request by skonto**
Fixes JIRA #SRVKS-1120

## Proposed Changes

- Similar to the old PR here: https://github.com/openshift-knative/serverless-operator/pull/2148

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

/hold can we now also remove the `USE_OLM_TLS` env? Or do we use that somewhere else (I haven't checked).

**Comment by skonto** [comment]
@ReToCode in order to remove that env var I have opened an upstream PR here: https://github.com/knative/pkg/pull/3006.

**Pull request merged**
