### PR TITLE
[WIP] bump to 1.8.0, but keep images at 0.13

### PR DESCRIPTION
**Pull request by aliok**
New PR for https://github.com/openshift-knative/serverless-operator/pull/296 as I can't add commits to that one.

### CODE REVIEW

**Comment by aliok** [comment]
@markusthoemmes 

Is following familiar?

```
--- FAIL: TestService (73.20s)
    service.go:98: Creating a new Service service service-ppmhhpcv
    crd.go:35:  resource {<nil> <nil> <*>{&TypeMeta{Kind:,APIVersion:,} &ObjectMeta{Name:service-ppmhhpcv,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},} {{&ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},}} {<nil>}} {{0 <nil>} { } {<nil> <nil> <nil>}}} <nil>}
    service.go:113: Waiting for Service to transition to Ready. service service-ppmhhpcv
    service.go:118: Checking to ensure Service Status is populated for Ready service
    service.go:124: Getting latest objects Created by Service
    service.go:127: Successfully created Service service-ppmhhpcv
    util.go:219: Checking to ensure Revision is in desired state with generation 1
    util.go:240: Checking to ensure Configuration is in desired state.
    service_test.go:65: the Configuration service-ppmhhpcv was not updated indicating that the Revision service-ppmhhpcv-qcd5z was created: %!w(<nil>)
    util.go:200: Checking that the endpoint vends the expected text: What a spaceport!
    spoof.go:117: Spoofing service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com -> service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com
    util.go:266: Validate Labels on Revision Object
    util.go:276: Validate Labels on Configuration Object
    util.go:285: Validate Labels on Route Object
    prober.go:176: Starting Route prober for http://service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com.
    service_test.go:85: Updating the Service to use a different image.
    spoof.go:117: Spoofing service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com -> service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com
    crd.go:35:  resource {<nil> <nil> <*>{&TypeMeta{Kind:,APIVersion:,} &ObjectMeta{Name:service-ppmhhpcv,GenerateName:,Namespace:serving-tests,SelfLink:/apis/serving.knative.dev/v1/namespaces/serving-tests/services/service-ppmhhpcv,UID:b0bddf9e-9ae6-4d08-89c6-23e7b759bdd2,ResourceVersion:48275,Generation:1,CreationTimestamp:2020-05-13 19:17:01 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{serving.knative.dev/creator: system:admin,serving.knative.dev/lastModifier: system:admin,},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},} {{&ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},}} {[{   <*>true <*>100 <nil>}]}} {{1 [{ConfigurationsReady True  {2020-05-13 19:17:25 +0000 UTC}  } {Ready True  {2020-05-13 19:17:25 +0000 UTC}  } {RoutesReady True  {2020-05-13 19:17:22 +0000 UTC}  }]} {service-ppmhhpcv-qcd5z service-ppmhhpcv-qcd5z} {<*>http://service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com <*>{<*>http://service-ppmhhpcv.serving-tests.svc.cluster.local} [{ service-ppmhhpcv-qcd5z  <*>true <*>100 <nil>}]}}} <nil>}
    service_test.go:92: Service should reflect new revision created and ready in status.
    service_test.go:98: Waiting for Service to transition to Ready.
    util.go:219: Checking to ensure Revision is in desired state with generation 2
    service_test.go:105: revision service-ppmhhpcv-lztxf did not have an expected annotation with generation 2: expected Revision service-ppmhhpcv-lztxf to be labeled with generation 2 but was 1 instead
    util.go:200: Checking that the endpoint vends the expected text: Re-energize yourself with a slice of pepperoni!
    spoof.go:117: Spoofing service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com -> service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com
    service_test.go:112: Updating labels of the RevisionTemplateSpec for service service-ppmhhpcv.
    crd.go:35:  resource {<nil> <nil> <*>{&TypeMeta{Kind:,APIVersion:,} &ObjectMeta{Name:service-ppmhhpcv,GenerateName:,Namespace:serving-tests,SelfLink:/apis/serving.knative.dev/v1/namespaces/serving-tests/services/service-ppmhhpcv,UID:b0bddf9e-9ae6-4d08-89c6-23e7b759bdd2,ResourceVersion:48275,Generation:1,CreationTimestamp:2020-05-13 19:17:01 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{serving.knative.dev/creator: system:admin,serving.knative.dev/lastModifier: system:admin,},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},} {{&ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{labelX: abc,labelY: def,},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},}} {[{   <*>true <*>100 <nil>}]}} {{1 [{ConfigurationsReady True  {2020-05-13 19:17:25 +0000 UTC}  } {Ready True  {2020-05-13 19:17:25 +0000 UTC}  } {RoutesReady True  {2020-05-13 19:17:22 +0000 UTC}  }]} {service-ppmhhpcv-qcd5z service-ppmhhpcv-qcd5z} {<*>http://service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com <*>{<*>http://service-ppmhhpcv.serving-tests.svc.cluster.local} [{ service-ppmhhpcv-qcd5z  <*>true <*>100 <nil>}]}}} <nil>}
    service_test.go:123: Waiting for the new revision to appear as LatestRevision.
    service_test.go:129: Updating annotations of RevisionTemplateSpec for service service-ppmhhpcv
    crd.go:35:  resource {<nil> <nil> <*>{&TypeMeta{Kind:,APIVersion:,} &ObjectMeta{Name:service-ppmhhpcv,GenerateName:,Namespace:serving-tests,SelfLink:/apis/serving.knative.dev/v1/namespaces/serving-tests/services/service-ppmhhpcv,UID:b0bddf9e-9ae6-4d08-89c6-23e7b759bdd2,ResourceVersion:50921,Generation:3,CreationTimestamp:2020-05-13 19:17:01 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{serving.knative.dev/creator: system:admin,serving.knative.dev/lastModifier: system:admin,},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},} {{&ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{annotationA: 123,annotationB: 456,},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},}} {[{   <*>true <*>100 <nil>}]}} {{2 [{ConfigurationsReady True  {2020-05-13 19:17:48 +0000 UTC}  } {Ready True  {2020-05-13 19:17:51 +0000 UTC}  } {RoutesReady True  {2020-05-13 19:17:51 +0000 UTC}  }]} {service-ppmhhpcv-mc5sm service-ppmhhpcv-mc5sm} {<*>http://service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com <*>{<*>http://service-ppmhhpcv.serving-tests.svc.cluster.local} [{ service-ppmhhpcv-mc5sm  <*>true <*>100 <nil>}]}}} <nil>}
    service_test.go:140: Waiting for the new revision to appear as LatestRevision.
    service_test.go:146: Waiting for Service to transition to Ready.
    util.go:219: Checking to ensure Revision is in desired state with generation 4
    util.go:240: Checking to ensure Configuration is in desired state.
    util.go:254: Checking to ensure Route is in desired state with generation 4
    util.go:200: Checking that the endpoint vends the expected text: Re-energize yourself with a slice of pepperoni!
    spoof.go:117: Spoofing service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com -> service-ppmhhpcv-serving-tests.apps.ci-op-0w6l5vnl-de449.origin-ci-int-aws.dev.rhcloud.com
    prober.go:221: Stopping all probers
...
FAIL	knative.dev/serving/test/conformance/api/v1	358.504s
```

**Comment by markusthoemmes** [comment]
@aliok nope, likely just a flake.

**Comment by markusthoemmes** [comment]
The last failure is interesting. Working on an upstream operator fix to make the HA config more consistent.

**Comment by matzew** [comment]
> The last failure is interesting. Working on an upstream operator fix to make the HA config more consistent.

I saw that a HA pod missed - I was thinking _flake_ ... :thinking:

**Comment by markusthoemmes** [comment]
yeah but in theory, the KnativeServing should only become ready once HA is reached. It could be something to do with the kick that updates certificates and whatnot. Definitely a flake in this case.

**Comment by aliok** [comment]
Cool. let's keep this one as the long running branch for eventing 0.14

cc @matzew

**Pull request merged**
