### PR TITLE
[SRVCOM-1285] Drop unsupported fields from the Eventing CRD

### PR DESCRIPTION
**Pull request by aliok**
Similar to https://github.com/openshift-knative/serverless-operator/pull/1023, for eventing

### CODE REVIEW

**Comment by aliok** [comment]
@markusthoemmes this looks good now

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Comment by markusthoemmes** [comment]
/retest

Infra.

**Comment by markusthoemmes** [comment]
/retest

Infra

**Comment by matzew** [comment]
Thanks, @aliok

**Pull request merged**
