### PR TITLE
[1.9] registry.svc.ci -> registry.ci

### PR DESCRIPTION
**Pull request by aliok**
Similar to https://github.com/openshift-knative/serverless-operator/pull/871

### CODE REVIEW

**Comment by aliok** [comment]
I guess we need to do something like this : https://github.com/openshift-knative/serverless-operator/pull/817/commits/c4a2ed3cf9fb8ebd8bd7373654058ccbb56219db

**Comment by matzew** [comment]
I think there is more needed... on the related fork branches too...

/cc @maschmid

**Comment by matzew** [comment]
@maschmid @aliok what's the status here?   Do we still need this ?

**Comment by aliok** [comment]
I don't know if this is still needed. Leaving it to @maschmid

**Comment by maschmid** [comment]
Let's close this one. It would require changes in the other repos first, and also the latest supported is 1.10, so it is not a priority to fix the older versions now. If anybody wants to make older work, they can open a new one then...

**Pull request closed without merging**
