### PR TITLE
[WIP] Remove redundant Elasticsearch install

### PR DESCRIPTION
**Pull request by mgencur**
Link to the failure that we try to fix with this PR: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-knative-serverless-operator-master-4.6-azure-e2e-azure-ocp-46-continuous/1345520395955998720 (affects weekly tests on Azure, GCP, vSphere)

### CODE REVIEW

**Comment by mgencur** [comment]
The failures looks exactly like https://issues.redhat.com/browse/MAISTRA-1410

**Comment by markusthoemmes** [comment]
@mgencur is this still something we want?

**Comment by mgencur** [comment]
The changes were merged as part of another PR. Closing this one.

**Pull request closed without merging**
