### PR TITLE
Only run Serving encryption tests for kourier

### PR DESCRIPTION
**Pull request by ReToCode**
## Proposed Changes
- Only run Serving encryption tests for Kourier.
- As we run istio tests with mesh enabled and encryption is not supported/needed in that mode.
- And as, encryption for istio downstream is currently not supported in general.
- More context [here](https://redhat-internal.slack.com/archives/CF5ANN61F/p1716965246865489)

### CODE REVIEW

**Comment by ReToCode** [comment]
`system-internal-tls` definitely makes no sense with istio. I'm currently testing if `cluster-local-domain-tls` would work (just to know), even though we do not plan on supporting that with istio either.

**Comment by ReToCode** [comment]
Lint is unrelated, separate PR so

/override "validate/lint"

**Comment by skonto** [comment]
> I'm currently testing if cluster-local-domain-tls would work (just to know), even though we do not plan on supporting that with istio either.

Is this tested by creating a separate gateway and a workload accessing with https the ingress gaetway, with Istio in mesh mode? Is not this a feature RHOAI wanted to solve the tls issue?

**Comment by ReToCode** [comment]
@skonto @mgencur  PTAL

**Comment by mgencur** [comment]
LGTM

**Comment by skonto** [comment]
Maybe get the lint one in first? Then stamp this one?

**Comment by ReToCode** [comment]
Should not matter, but we can 👍

**Pull request merged**
