### PR TITLE
Adding CSV bumps for 1.7.2 release

### PR DESCRIPTION
**Pull request by rhuss**
Supersedes #359 and is rebased on current release-1.7.2 branch

### CODE REVIEW

**Comment by rhuss** [comment]
The upgrade test is failing, but I'm not sure why this line in the logs:

```
INFO 09:21:34.380 updating serving version from 0.13.3 to 0.13.2
```

Where does this 0.13.2 comes from ? // @nak3 @markusthoemmes

**Comment by markusthoemmes** [comment]
https://github.com/openshift-knative/serverless-operator/blob/release-1.7/knative-operator/vendor/knative.dev/serving-operator/version/version.go ... YAY for consistency.

**Comment by markusthoemmes** [comment]
@rhuss I believe this might work https://github.com/markusthoemmes/serverless-operator/commit/306ce2eb6671b91b2f584502b49535c329b5cdff

**Comment by rhuss** [comment]
@markusthoemmes @nak3 Tests are running, but does this sound okish (from the `test.log`) ? 

```
INFO 12:27:59.727 updating serving version from 0.13.3 to 0.13.3
```

Also, do we need to add this dep update to the release notes, too ? (cc: @abrennan89 ). I'm not sure that I understand the update tests still. So, 1.7.2 includes serving 0.13.3 (instead of 0.13.2 in 1.7.1). What is the gap between 0.13.2 and 0.13.3 in serving (i.e. which bugs are fixed here) ? IMO this should become part of the release notes, too.

**Pull request merged**
