### PR TITLE
bump for eventing 1.2x

### PR DESCRIPTION
**Pull request by matzew**
Similar to #1489 but different (no "go dep" were bumped here)

Lets see

### CODE REVIEW

**Comment by matzew** [comment]
```
    tracker.go:137: Failed to clean the resource "eventing-e2e18" : serviceaccounts "eventing-e2e18" not found
    --- PASS: TestServerlessUpgrade/VerifyContinualTests (101.79s)
        --- PASS: TestServerlessUpgrade/VerifyContinualTests/ProbeTest (0.68s)
        --- PASS: TestServerlessUpgrade/VerifyContinualTests/AutoscaleSustainingWithTBCTest (0.89s)
        --- PASS: TestServerlessUpgrade/VerifyContinualTests/AutoscaleSustainingTest (0.79s)
        --- PASS: TestServerlessUpgrade/VerifyContinualTests/EventingContinualTest (22.16s)
        --- PASS: TestServerlessUpgrade/VerifyContinualTests/ChannelContinualTest (18.94s)
        --- PASS: TestServerlessUpgrade/VerifyContinualTests/BrokerBackedByChannelContinualTest (19.80s)
        --- PASS: TestServerlessUpgrade/VerifyContinualTests/KafkaBrokerContinualTest (19.98s)
        --- PASS: TestServerlessUpgrade/VerifyContinualTests/KafkaSinkSourceContinualTest (18.54s)
PASS
```

**Comment by matzew** [comment]
/hold
for now....

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
worked again...

/test 4.10-upgrade-tests-aws-ocp-410

**Comment by matzew** [comment]
/test 4.10-upgrade-tests-aws-ocp-410

Once again... /cc @aliok

**Comment by aliok** [comment]
/test 4.10-upgrade-tests-aws-ocp-410

Failed, trying again

**Comment by aliok** [comment]
/test 4.10-upgrade-tests-aws-ocp-410

Not sure if it is a real problem...
```
build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: initializing source docker://registry.ci.openshift.org/openshift/knative-v1.2.1:knative-eventing-kafka-src: reading manifest knative-eventing-kafka-src in registry.ci.openshift.org/openshift/knative-v1.2.1: manifest unknown: manifest unknown
```

**Comment by matzew** [comment]
> registry.ci.openshift.org/openshift/knative-v1.2.1:knative-eventing-kafka-src

that is a wrong image...

I see: I messed it up here:
https://github.com/openshift/release/commit/d0badcd21d458ea24cda5c2dc55a39707957282d#diff-62f52e1c93d9db6ced2662f229d9b614015de378a99dbac9bbda6dffa3df09f8L183

Working on a fix

**Comment by aliok** [comment]
/test 4.10-upgrade-tests-aws-ocp-410

Fix merged.

**Comment by aliok** [comment]
/test 4.10-upgrade-tests-aws-ocp-410

Image is now available.

**Pull request closed without merging**
