### PR TITLE
[SRVCOM-1666][RELEASE 1.20] Fix version in csv urls and other broken ones

### PR DESCRIPTION
**Pull request by skonto**
Same as in #1396

### CODE REVIEW

**Comment by skonto** [comment]
@maschmid ready.

**Comment by skonto** [comment]
@maschmid should be approved?

**Review by maschmid — APPROVED** [review]

**Comment by maschmid** [comment]
/approve

I don't think  I am an approver though...

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
