### PR TITLE
Add links for arm64 artifacts to consoleclidownload.go

### PR DESCRIPTION
**Pull request by mvinkler**
Fixes JIRA [SRVCOM-3099](https://issues.redhat.com/browse/SRVCOM-3099)

## Proposed Changes

:bug: fix - add missing links for arm64 kn to OCP Command Line Tools page

### CODE REVIEW

**Comment by Kaustubh-pande** [comment]
@mvinkler we need to update the expected number- https://github.com/openshift-knative/serverless-operator/blob/7d60f8643fcaf72e79e8301eef52694e8e06478a/test/servinge2e/verify_deploy_resources_test.go#L26

**Comment by pierDipi** [comment]
```
	0s
{Failed  === RUN   TestKnConsoleCLIDownload
    verify_deploy_resources_test.go:46: Failed to verify kn CCD, kn artifact "https://kn-openshift-serverless.apps.serverless-ocp-4-15-amd64-aws-us-east-1-mms7d.serverless.devcluster.openshift.com/kn-linux-arm64.tar.gz" size 19 less than 10MB
    verify_deploy_resources_test.go:46: Failed to verify kn CCD, kn artifact "https://kn-openshift-serverless.apps.serverless-ocp-4-15-amd64-aws-us-east-1-mms7d.serverless.devcluster.openshift.com/kn-darwin-arm64.tar.gz" size 19 less than 10MB
--- FAIL: TestKnConsoleCLIDownload (0.12s)
}
```

**Comment by mvinkler** [comment]
@dsimansk any idea why the Content-Length header returns 19 bytes for both arm downloads?
```
 === RUN   TestKnConsoleCLIDownload
    verify_deploy_resources_test.go:46: Failed to verify kn CCD, kn artifact "https://kn-openshift-serverless.apps.serverless-ocp-4-15-amd64-aws-us-east-1-mms7d.serverless.devcluster.openshift.com/kn-linux-arm64.tar.gz" size 19 less than 10MB
    verify_deploy_resources_test.go:46: Failed to verify kn CCD, kn artifact "https://kn-openshift-serverless.apps.serverless-ocp-4-15-amd64-aws-us-east-1-mms7d.serverless.devcluster.openshift.com/kn-darwin-arm64.tar.gz" size 19 less than 10MB 
```

**Comment by dsimansk** [comment]
@mvinkler it should pass even the download test with changes made in midstream kn-cli-artifacts. 

https://github.com/openshift-knative/client/pull/378

**Comment by dsimansk** [comment]
In addition we synced with @Kaustubh-pande on the naming scheme. In the cli image we will keep archive names with `kn-macos-*` to keep it consistent.

**Comment by dsimansk** [comment]
Current structure in midstream image:
```
[root@c30a67b9bb13 kn]# ls -lR
.:
total 12
-rw-rw-r--. 1 root root 11357 May 13 19:22 LICENSE
drwxr-xr-x. 2 root root    35 May 13 19:39 linux_amd64
drwxr-xr-x. 2 root root    35 May 13 19:39 linux_arm64
drwxr-xr-x. 2 root root    37 May 13 19:39 linux_ppc64le
drwxr-xr-x. 2 root root    35 May 13 19:39 linux_s390x
drwxr-xr-x. 2 root root    35 May 13 19:39 macos_amd64
drwxr-xr-x. 2 root root    35 May 13 19:39 macos_arm64
drwxr-xr-x. 2 root root    34 May 13 19:39 windows

./linux_amd64:
total 47696
-rw-r--r--. 1 root root 48837246 May 13 19:38 kn-linux-amd64.tar.gz

./linux_arm64:
total 44480
-rw-r--r--. 1 root root 45546738 May 13 19:38 kn-linux-arm64.tar.gz

./linux_ppc64le:
total 44412
-rw-r--r--. 1 root root 45475797 May 13 19:38 kn-linux-ppc64le.tar.gz

./linux_s390x:
total 47040
-rw-r--r--. 1 root root 48165706 May 13 19:38 kn-linux-s390x.tar.gz

./macos_amd64:
total 47408
-rw-r--r--. 1 root root 48542499 May 13 19:38 kn-macos-amd64.tar.gz

./macos_arm64:
total 8
-rw-r--r--. 1 root root 4134 May 13 19:38 kn-macos-arm64.tar.gz

./windows:
total 48084
-rw-r--r--. 1 root root 49236005 May 13 19:39 kn-windows-amd64.zip
```

**Comment by dsimansk** [comment]
/approve
/lgtm

For tests
/hold
/cherry-pick release-1.33

**Comment by dsimansk** [comment]
Pendig update on CI config side first: https://github.com/openshift/release/pull/51996

**Pull request merged**
