### PR TITLE
[release-1.31] bump ocp min version to 4.11

### PR DESCRIPTION
**Pull request by ReToCode**
As in https://github.com/openshift-knative/serverless-operator/pull/2330, but for release-1.31

/assign @pierDipi

### CODE REVIEW

**Comment by ReToCode** [comment]
4.10 tests are probably never going to be successful, as per https://github.com/openshift-knative/serverless-operator/pull/2325#issuecomment-1765725407.

/override "ci/prow/4.10-e2e-kitchensink-ocp-410"

/override "ci/prow/4.10-operator-e2e-aws-ocp-410"

/override "ci/prow/4.10-upgrade-kitchensink-ocp-410"

/override "ci/prow/4.10-upgrade-tests-aws-ocp-410"

/override "ci/prow/4.10-upstream-e2e-aws-ocp-410"

/override "ci/prow/4.10-upstream-e2e-kafka-aws-ocp-410"

/override "ci/prow/4.10-upstream-e2e-mesh-aws-ocp-410"

**Comment by mgencur** [comment]
/lgtm
/hold

Hold for kitchensink tests to pass.

**Pull request merged**
