### PR TITLE
Include workaround for LoadBalancer cleanup on Azure

### PR DESCRIPTION
**Pull request by mgencur**
* workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1798282

### CODE REVIEW

**Comment by nak3** [comment]
So, bz#1798282 is talking about `ingresscontroller`, but `ingresscontroller` is not the main point. 
Strictly speaking, svc with type.LoadBalancer gets stuck when we delete namespace on Azure?

If yes, does Kourier's svc need this workaround as well?

**Comment by mgencur** [comment]
That's right, all services of type LoadBalancer are affected. I'll have to fix this for Kourier. Mmt.

**Comment by mgencur** [comment]
Updated with the Kourier check.

**Comment by mgencur** [comment]
Thanks:)

**Pull request merged**
