### PR TITLE
Set max OCP version to 4.17

### PR DESCRIPTION
**Pull request by creydr**
According to https://docs.google.com/spreadsheets/d/1HTxR37_MM03_JQImW-KmAFk1oEQ83fXzfGxdfWQSX6o/edit?gid=0#gid=0 we'll support 4.17

### CODE REVIEW

**Comment by mgencur** [comment]
The error is:
```
oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
```
We need RHEL8 variant of CLI. Version 4.16 and newer are based on RHEL9 :-/
```
ᐅ podman run -it --authfile=/tmp/t.c registry.ci.openshift.org/ocp/4.17:cli
Trying to pull registry.ci.openshift.org/ocp/4.17:cli...
Getting image source signatures
Copying blob 8ef51801ec3b done   | 
Copying blob 25c75c34b2e2 done   | 
Copying blob 1ec0aa8c1040 done   | 
Copying blob b735d22fcdc5 done   | 
Copying blob 18dd97dc18d3 done   | 
Copying config 1ed420b0d0 done   | 
Writing manifest to image destination
[root@913b1e478833 /]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.4 (Plow)
[root@913b1e478833 /]#
```
Maybe we'll need to stick with 4.15 for the CLI image. Trying to find RHEL8 variant but not success so far.

**Comment by mgencur** [comment]
This will work:
```
diff --git a/openshift/ci-operator/source-image/Dockerfile b/openshift/ci-operator/source-image/Dockerfile
index ef48f39b2..b8f74b16f 100644
--- a/openshift/ci-operator/source-image/Dockerfile
+++ b/openshift/ci-operator/source-image/Dockerfile
@@ -1,8 +1,8 @@
-FROM registry.ci.openshift.org/ocp/4.15:cli AS oc-image
+FROM registry.ci.openshift.org/ocp/4.17:cli-artifacts AS oc-image
 
 FROM src
 
-COPY --from=oc-image /usr/bin/oc /usr/bin/oc
+COPY --from=oc-image /usr/share/openshift/linux_amd64/oc.rhel8 /usr/bin/oc
 COPY --from=registry.ci.openshift.org/openshift/knative-serving-src:knative-v1.15 /go/src/github.com/openshift-knative/serving/ /go/src/knative.dev/serving/
 COPY --from=registry.ci.openshift.org/openshift/knative-eventing-src:knative-v1.15 /go/src/github.com/openshift-knative/eventing/ /go/src/knative.dev/eventing/
 COPY --from=registry.ci.openshift.org/openshift/eventing-kafka-broker-src:knative-v1.15 /go/src/github.com/openshift-knative/eventing-kafka-broker/ /go/src/knative.dev/eventing-kafka-broker/
```
The cli-artifacts image has both variaants: RHEL9 and RHEL8 as can be seen here: https://github.com/openshift/oc/blob/master/images/cli-artifacts/Dockerfile.rhel#L21C80-L21C112

**Comment by creydr** [comment]
Thanks @mgencur for catching it,
updated it, so this is similar to https://github.com/openshift-knative/hack/blob/3761e2312276024aa1d32c069d700085276d4753/cmd/generate/dockerfile-templates/BuildImageDockerfile.template#L10

(`TARGETARCH` is a [predefined build arg](https://docs.docker.com/build/building/variables/#pre-defined-build-arguments))

**Pull request merged**
