### PR TITLE
[SRVKE-1235] Update KafkaChannel dashboards for migration to broker components

### PR DESCRIPTION
**Pull request by pierDipi**
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

Fixes JIRA #SRVKE-1235

## Proposed Changes

- Use the new metric names

Screenshots during manual tests:

image

image

### CODE REVIEW

**Comment by pierDipi** [comment]
Testing this PR in a clusterbot cluster :hourglass_flowing_sand: ...

**Comment by pierDipi** [comment]
and it's not fake :smile: , they actually go down once load ends:

image

**Comment by matzew** [comment]
What's the `NaN` in there? why is there not a number?

**Comment by pierDipi** [comment]
That's how it works :man_shrugging: 

see IMC as well:

image

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
