### PR TITLE
Bumping for 1.7.1

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

As title says: this is only bumping the version on the CSV. 

No images are updated, yet ... that will _follow_ in separate PR(s).

/assign @markusthoemmes

### CODE REVIEW

**Comment by markusthoemmes** [comment]
You might need to disable some upgrade test checks until we actually update operand versions. See @aliok's PR against master for 1.8.0.

**Comment by matzew** [comment]
OK, I will come back to this after the first ride of tests here.

thanks for the heads up, Markus

**Comment by markusthoemmes** [comment]
If the upgrade tests pass, we're good. If not, now you'll know where to look :yum:

**Comment by markusthoemmes** [comment]
/test 4.5-upgrade-tests-aws-ocp-45

Might be a flake.

**Comment by matzew** [comment]
```
TestKnativeServing/create_subscription_and_wait_for_CSV_to_succeed (300.37s)
```
:thinking:

**Pull request merged**
