### PR TITLE
Rename REQUIRED_NAMESPACE to REQUIRED_SERVING_NAMESPACE

### PR DESCRIPTION
**Pull request by aliok**
Didn't touch the CSV files. I would touch the 1.7 CSV but it is not there yet.

### CODE REVIEW

**Comment by aliok** [comment]
cc @markusthoemmes

**Comment by markusthoemmes** [comment]
Yeah let's create the 1.7.0 CSV soon. We'll need it for this to pass the tests.

**Comment by aliok** [comment]
@markusthoemmes ok, I am creating the 1.7 CSV in a separate PR

**Comment by markusthoemmes** [comment]
Already did in https://github.com/openshift-knative/serverless-operator/pull/215. It might be a little tricky because of upgrade testing.

**Comment by aliok** [comment]
/retest

No idea why this fails with that error message...

**Pull request merged**
