### PR TITLE
[SRVKS-955] Allow to override CERTS_SECRET_NAME value via config-network

### PR DESCRIPTION
**Pull request by nak3**
The default ingress certificate name is configurable via IngressController CR from `router-certs-default`.

When users changed the name, Kourier also needs to point to the customized name. So this patch allows users to
point to the name via `"openshift-ingress-default-certificate"` in `config-network`.

### CODE REVIEW

**Comment by skonto** [comment]
Probe test is failing (we already know that) also lint seems timing out.

**Comment by nak3** [comment]
lint was fixed by another PR.

**Comment by skonto** [comment]
Saw the other PR so why lint fails? Needs rebasing?

**Comment by skonto** [comment]
@nak3 So this PR is for setting some cert other than the OCP ingress one to be used by internal encryption. Correct?

**Comment by mgencur** [comment]
I tested this PR locally with my cluster with those specific certificates and it worked!

**Pull request merged**
