### PR TITLE
Bump Eventing to 1.6 

### PR DESCRIPTION
**Pull request by pierDipi**
As per title.

### CODE REVIEW

**Comment by pierDipi** [comment]
```
 Status:{Phase:Pending Message:one or more requirements couldn't be found Reason:RequirementsNotMet LastUpdateTime:2022-11-21 17:06:28 +0000 UTC LastTransitionTime:2022-11-21 17:06:27 +0000 UTC Conditions:[{Phase:Pending Message:requirements not yet checked Reason:RequirementsUnknown LastUpdateTime:2022-11-21 17:06:27 +0000 UTC LastTransitionTime:2022-11-21 17:06:27 +0000 UTC} {Phase:Pending Message:one or more requirements couldn't be found Reason:RequirementsNotMet LastUpdateTime:2022-11-21 17:06:28 +0000 UTC LastTransitionTime:2022-11-21 17:06:27 +0000 UTC}] RequirementStatus:[{Group:operators.coreos.com Version:v1alpha1 Kind:ClusterServiceVersion Name:serverless-operator.v1.26.0 Status:Present Message:CSV minKubeVersion (1.19.0) less than server version (v1.21.11+5cc9227) UUID: Dependents:[]} {Group:apiextensions.k8s.io Version:v1 Kind:CustomResourceDefinition Name:knativeeventings.operator.knative.dev Status:Present Message:CRD is present and Established condition is true UUID:487d8a5b-d22a-4629-a97e-149939702bd4 Dependents:[]} {Group:apiextensions.k8s.io Version:v1 Kind:CustomResourceDefinition Name:knativekafkas.operator.serverless.openshift.io Status:Present Message:CRD is present and Established condition is true UUID:079c4470-57de-483a-959f-5d53fe72d495 Dependents:[]} {Group:apiextensions.k8s.io Version:v1 Kind:CustomResourceDefinition Name:knativeservings.operator.knative.dev Status:Present Message:CRD is present and Established condition is true UUID:f19a9d17-8cde-41f7-81f9-2fda70d8ed35 Dependents:[]} {Group: Version:v1 Kind:ServiceAccount Name:knative-operator Status:NotPresent Message:Service account does not exist UUID: Dependents:[]} {Group: Version:v1 Kind:ServiceAccount Name:knative-openshift-ingress Status:NotPresent Message:Service account does not exist UUID: Dependents:[]}] CertsLastUpdated:<nil> CertsRotateAt:<nil> Cleanup:{PendingDeletion:[]}}}: timed out waiting for the condition
        --- FAIL: TestServerlessDowngrade/DowngradeWith/DowngradeServerless (320.27s)
```

**Comment by skonto** [comment]
OLM logs [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1793/pull-ci-openshift-knative-serverless-operator-main-4.8-upgrade-tests-aws-ocp-48/1594728047443972096/artifacts/upgrade-tests-aws-ocp-48/gather-extra/artifacts/pods/openshift-operator-lifecycle-manager_olm-operator-64d4c4459-6btsb_olm-operator.log). Some msg history for 1.26 (downgrade):

```
time="2022-11-21T17:12:09Z" level=info msg="checking packageserver"
time="2022-11-21T17:12:09Z" level=info msg="checking packageserver"
time="2022-11-21T17:12:09Z" level=info msg="requirements were not met" csv=serverless-operator.v1.26.0 id=jxcm3 namespace=openshift-serverless phase=Pending
time="2022-11-21T17:12:09Z" level=info msg="couldn't ensure RBAC in target namespaces" csv=serverless-operator.v1.26.0 error="no owned roles found" id=Eiff9 namespace=openshift-serverless phase=Pending
E1121 17:12:09.712436       1 queueinformer_operator.go:290] sync {"update" "openshift-serverless/serverless-operator.v1.26.0"} failed: no owned roles found
time="2022-11-21T17:12:09Z" level=error msg="Create for new CSV failed: clusterserviceversions.operators.coreos.com \"serverless-operator.v1.26.0\" is forbidden: unable to create new content in namespace eventing-e2e0 because it is being terminated"
time="2022-11-21T17:12:09Z" level=info msg="requirements were not met" csv=serverless-operator.v1.26.0 id=KW3aL namespace=openshift-serverless phase=Pending
```

**Pull request merged**
