### PR TITLE
[Release 1.15] Fix rbac proxy images for Eventing 

### PR DESCRIPTION
**Pull request by skonto**
* adds rbac proxy image productization support for Eventing.

### CODE REVIEW

**Comment by skonto** [comment]
rebased

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
Tests still fail :(

**Comment by matzew** [comment]
@skonto are we sure this is enough, or is more needed here ?

**Comment by matzew** [comment]
We missed this on the 1.15 branch: https://github.com/openshift-knative/serverless-operator/pull/969

(was only done for `main`)

**Comment by skonto** [comment]
@matzew should I rebase again?

**Comment by markusthoemmes** [comment]
Please don't @skonto. This is almost there :joy:

**Pull request merged**
