### PR TITLE
Bump eventing-kafka to 0.25

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title, let's see what happens.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/hold

Not to be merged yet.

**Comment by devguyio** [comment]
I can't find any reason why the e2e step failed, everything inside is reporting it was successful but the logs are saying 
```
pod ci-op-snjx2tqk/upgrade-tests-aws-ocp-48-serverless-e2e was deleted without completing after 25m18s (failed containers: )
```

so maybe it was unfortunate and got evicted for some reason? I'll retry

/retest

**Pull request merged**
