### PR TITLE
:safety_vest: Add DCO and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by cardil**
## Proposed Changes

- :safety_vest: Add DCO and CONTRIBUTING.md

Related https://github.com/openshift-knative/showcase/pull/22

### CODE REVIEW

**Comment by nak3** [comment]
/cc @rhuss 

I am not sure if I can approve this but LGTM.

**Comment by cardil** [comment]
https://redhat-internal.slack.com/archives/CD87JDUB0/p1681470665707359?thread_ts=1681470665.707359&cid=CD87JDUB0

**Comment by dsimansk** [comment]
Based on the chat conversation, it seems like a very sane thing to do. :)

/approve
/lgtm

**Pull request merged**
