### PR TITLE
[release-1.27]Namespaced broker metrics

### PR DESCRIPTION
**Pull request by aliok**
Cherrypick https://github.com/openshift-knative/serverless-operator/pull/1896

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
/test 4.11-operator-e2e-aws-ocp-411

```
TestKafkaSourceToKnativeService
```

I already took some notes around the issue. 
Will be possibly solved by https://github.com/openshift-knative/eventing-kafka-broker/pull/536

**Review by pierDipi — APPROVED** [review]
/lgtm
/hold for tests

**Comment by pierDipi** [comment]
It's all green! :tada: 

/unhold

**Pull request merged**
