### PR TITLE
Bump serving version to 1.1.2

### PR DESCRIPTION
**Pull request by nak3**
As per title, this patch bumps serving and its family to 1.1.2.

### CODE REVIEW

**Comment by nak3** [comment]
/retest
/hold cancel

All eventing error.

**Comment by nak3** [comment]
It seems culprit is this :thinking: 

```
        Message:Failed to pull image "quay.io/openshift-knative/kafka-consumer:v1.1": rpc error: code = Unknown desc = reading manifest v1.1 in quay.io/openshift-knative/kafka-consumer: manifest unknown: manifest unknown
```

**Comment by nak3** [comment]
Fixing in https://github.com/openshift/release/pull/26707

**Comment by skonto** [comment]
It seems there are timeouts:

```
        Reason:InternalError
        Message:failed to create topic: kafka-sink-eventing-e2e12: dial tcp 10.128.2.15:9092: i/o timeout
        Source:EventSource{Component:kafkasink-controller,Host:,}
        FirstTimestamp:2022-03-03 16:21:20 +0000 UTC
```

Trying once more.

**Comment by skonto** [comment]
Still image pull issue:

```
        Message:Failed to pull image "quay.io/openshift-knative/kafka-consumer:v1.1": rpc error: code = Unknown desc = reading manifest v1.1 in quay.io/openshift-knative/kafka-consumer: manifest unknown: manifest unknown
        Source:EventSource{Component:kubelet,Host:ip-10-0-151-57.ec2.internal,}
```

**Comment by skonto** [comment]
Probably we need Eventing image setup for 4.10? Like the one we have for [4.9](https://github.com/openshift/release/blob/8fca9d47fccfcba0ea80fa43c94311f07386c87b/ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.1__49.yaml).

**Comment by pierDipi** [comment]
> [Still image pull issue](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/1424/pull-ci-openshift-knative-serverless-operator-main-4.10-upgrade-tests-aws-ocp-410/1499440795634110464/artifacts/upgrade-tests-aws-ocp-410/serverless-e2e/build-log.txt):
> 
> ```
>         Message:Failed to pull image "quay.io/openshift-knative/kafka-consumer:v1.1": rpc error: code = Unknown desc = reading manifest v1.1 in quay.io/openshift-knative/kafka-consumer: manifest unknown: manifest unknown
>         Source:EventSource{Component:kubelet,Host:ip-10-0-151-57.ec2.internal,}
> ```

https://github.com/openshift/release/pull/26751

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
