### PR TITLE
Bump dependencies to version 1.7

### PR DESCRIPTION
**Pull request by ReToCode**
## Proposed Changes
- Bump all dependencies to 1.7 in `olm-catalog/serverless-operator/project.yaml` and `hack/update-deps.sh`
- Update dependencies with `make generated-files` and `./hack/update-deps.sh --upgrade`
- Updated the patch `hack/patches/004-disable-manifests-version-match.patch`
- Added another `go mod tidy -compat=1.18`, otherwise go `go mod vendor` did not run
- Updated `go mod tidy` format to `1.18`

### CODE REVIEW

**Comment by ReToCode** [comment]
a) I tried to generate 3 PRs accordingly, but was unable to get the scripts running when only updating operator/serving/eventing. If anyone has a pointer on how to achieve this, I can split this into three PRs.

b) Is anything else needed (see the list what I did in PR)?

/cc @nak3 , @matzew , @skonto , @pierDipi

**Comment by nak3** [comment]
> a) I tried to generate 3 PRs accordingly, but was unable to get the scripts running when only updating operator/serving/eventing. If anyone has a pointer on how to achieve this, I can split this into three PRs.

It seems possible to bump the serving only by modifying serving parts only in `project.yaml` and `hack/update-deps.sh` then running the script as you did. I sent the PR to https://github.com/openshift-knative/serverless-operator/pull/1887 (sorry I was not confident without testing so I opened the PR.)

> b) Is anything else needed (see the list what I did in PR)?

I think you did everything.

**Comment by ReToCode** [comment]
Yeah, I started with just the operator. That partially also updated dependencies of serving and eventing.

**Comment by nak3** [comment]
Ah, I see.
Shall we continue https://github.com/openshift-knative/serverless-operator/pull/1887 to merge serving first?

**Comment by ReToCode** [comment]
I think this https://github.com/openshift/release/pull/34931 was missing. I'll add that to the release manual.

**Pull request closed without merging**
