### PR TITLE
[release-1.33] Bump to 1.33.1

### PR DESCRIPTION
**Pull request by pierDipi**
As per title

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/retest

**Comment by pierDipi** [comment]
@Kaustubh-pande @maschmid do you see what's wrong here? :thinking:

**Comment by maschmid** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-knative_serverless-operator/2748/pull-ci-openshift-knative-serverless-operator-release-1.33-415-upstream-e2e-aws-415/1808107011800305664/artifacts/upstream-e2e-aws-415/openshift-gather-extra/artifacts/pods/openshift-marketplace_serverless-operator-dvk7c_registry-server.log


```time="2024-07-02T12:23:25Z" level=fatal msg="no olm.bundle blobs found in package \"serverless-operator\" for olm.channel entries [serverless-operator.v1.31.0]"```

so maybe the other channels that still reference 1.31.0 are the problem?

https://github.com/openshift-knative/serverless-operator/pull/2748/files#diff-55554988a6ad1a56cfb485f9de15784449897484786cdbfcd8c3ffbb97be92e1R26-R39

**Comment by pierDipi** [comment]
I don't yet understand how this is supposed to work

https://github.com/openshift-knative/serverless-operator/blob/main/olm-catalog/serverless-operator/index/Dockerfile

```
RUN /bin/opm init serverless-operator --default-channel=stable --output yaml >> /configs/index.yaml
RUN /bin/opm render --skip-tls-verify -o yaml registry.ci.openshift.org/knative/openshift-serverless-v1.32.0:serverless-bundle \
      registry.ci.openshift.org/knative/release-1.33.0:serverless-bundle \
      registry.ci.openshift.org/knative/release-1.34.0:serverless-bundle >> /configs/index.yaml || \
    /bin/opm render --skip-tls-verify -o yaml registry.ci.openshift.org/knative/openshift-serverless-v1.32.0:serverless-bundle \
      registry.ci.openshift.org/knative/release-1.33.0:serverless-bundle \
      registry.ci.openshift.org/knative/serverless-bundle:main >> /configs/index.yaml
```

This will always contain 1.33.0 until we merge this PR

**Comment by pierDipi** [comment]
```
opm render --skip-tls-verify -o yaml registry.ci.openshift.org/knative/release-1.33.1:serverless-bundle > index.yaml
```

```yaml
# index.yaml
---
image: registry.ci.openshift.org/knative/release-1.33.1:serverless-bundle
name: serverless-operator.v1.33.0
package: serverless-operator
properties:
- type: olm.gvk
  value:
    group: operator.knative.dev
    kind: KnativeEventing
    version: v1beta1
- type: olm.gvk
  value:
    group: operator.knative.dev
    kind: KnativeServing
    version: v1beta1
- type: olm.gvk
  value:
    group: operator.serverless.openshift.io
    kind: KnativeKafka
    version: v1alpha1
- type: olm.package
  value:
    packageName: serverless-operator
    version: 1.33.0
- type: olm.csv.metadata
  value:
    annotations:
# ...
```

**Comment by pierDipi** [comment]
```
[2/3] STEP 3/5: COPY olm-catalog/serverless-operator/index/configs /configs
error: build error: building at STEP "COPY olm-catalog/serverless-operator/index/configs /configs": checking on sources under "/tmp/build/inputs": copier: stat: "/olm-catalog/serverless-operator/index/configs": no such file or directory
```

**Comment by pierDipi** [comment]
@skonto @ReToCode any idea about the test failure?

**Comment by skonto** [comment]
It seems that on this branch upgrades assume a previous version of 1.33.0 and the test needs the QP image to change which is probably not happening as downstream we have: `registry.ci.openshift.org/openshift/knative-serving-queue:knative-v1.12`.

**Comment by pierDipi** [comment]
@skonto @matzew @maschmid Can you LGTM ? I'll merge it manually given the test error is unrelated

**Comment by pierDipi** [comment]
@maschmid @matzew @skonto a follow up for the errors for patch releases https://github.com/openshift-knative/serverless-operator/pull/2754

**Comment by pierDipi** [comment]
@maschmid @matzew @skonto another follow up to warn people that when we bump patch version we need to first update openshift/release https://github.com/openshift-knative/serverless-operator/pull/2755

**Pull request merged**
