### PR TITLE
Rework the ingress pod in terms of knative/pkg.

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title, this reimplements the ingress pod in terms of knative/pkg as a first step to consolidate our libraries and to see how much work it is to rewrite a controller in knative/pkg to eventually be applied to the serverless-operator itself.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/retest

seems like infra stuff.

**Comment by markusthoemmes** [comment]
/test 4.5-upgrade-tests-aws-ocp-45

```
 2020/09/15 18:18:51 pod didn't start running within 10 minutes: 
* Container artifacts is not ready with reason PodInitializing and message 
* Container test is not ready with reason PodInitializing and message 
2020/09/15 18:19:56 pod didn't start running within 10 minutes: 
* Container artifacts is not ready with reason PodInitializing and message 
* Container test is not ready with reason PodInitializing and message 
2020/09/15 18:20:04 error: artifacts container for pod upgrade-tests-aws-ocp-45-serverless-e2e unready: timed out waiting for the condition
2020/09/15 18:20:34 error: artifacts container for pod upgrade-tests-aws-ocp-45-serverless-e2e unready: timed out waiting for the condition
panic: close of nil channel
```

infra...

**Comment by nak3** [comment]
/retest

infra issue. 

```
  * could not run steps: step upgrade-tests-aws-ocp-45 failed: "upgrade-tests-aws-ocp-45" pre steps failed: "upgrade-tests-aws-ocp-45" pod "upgrade-tests-aws-ocp-45-ipi-install-rbac" failed: the pod ci-op-yqw9l9t6/upgrade-tests-aws-ocp-45-ipi-install-rbac failed after 4s (failed containers: test): ContainerFailed one or more containers exited
```

**Comment by nak3** [comment]
@markusthoemmes Than you. This looks good to me. I don't see any problem. Please unhold if you are ready.

/lgttm
/hold

**Comment by nak3** [comment]
LGTM

I will wait a little bit until @warrenvw takes a look.

**Comment by warrenvw** [comment]
I do not see any problems as it relates to productization.

/lgtm
/approve

**Pull request merged**
