### PR TITLE
:lady_beetle: [UI] Delete application fix for ODC 4.10

### PR DESCRIPTION
**Pull request by cardil**
## Proposed Changes

- :lady_beetle: [UI] Delete application fix for ODC 4.10

/kind bug

Should fix failures like https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-knative-serverless-operator-main-4.10-ui-tests-continuous/1643856281519263744

### CODE REVIEW

**Comment by mgencur** [comment]
/lgtm
/hold

Hold for tests.

**Comment by cardil** [comment]
Tests are passing well

/hold cancel

**Pull request merged**
