### PR TITLE
Move ServiceMonitor and Service setup into OLM bundle

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title, pretty much following what https://github.com/openshift/enhancements/blob/9cee282b58fcf6a14612f21daf53d9b67ed52f59/enhancements/olm/olm-managed-operator-metrics.md suggests. Allows us to drop the operator-sdk dependency completely <3.

/assign @skonto

### CODE REVIEW

**Comment by matzew** [comment]
> operator-sdk dependency completely

NICE!

**Comment by skonto** [comment]
@markusthoemmes there is also space to remove the rbac setup I am doing in code (role and rolebinding) following the instructions here: https://github.com/openshift/enhancements/blob/9cee282b58fcf6a14612f21daf53d9b67ed52f59/enhancements/olm/olm-managed-operator-metrics.md#rbac-requirements

**Comment by markusthoemmes** [comment]
@skonto well, I can't remove the function though, seeing as it's used for other deployments for sources etc. as well. So I kept it, as it's kinda low value to cut that code path in half, might even make things harder to read.

**Comment by skonto** [comment]
Tested it locally the service monitor works as expected.

**Comment by markusthoemmes** [comment]
I guess we have an update issue because the resources already exist... ugh :-1:. I'll take a look at whether or not that's easily fixed.

**Comment by markusthoemmes** [comment]
Nope, investigated, the RBAC rules are somehow dropped on this codepath :thinking:. Chatting with the OLM team on what's going on here.

/hold

**Comment by markusthoemmes** [comment]
I consider this passed but...

/retest

**Comment by markusthoemmes** [comment]
/unhold

This works now!

**Comment by skonto** [comment]
@markusthoemmes I approve it but we need some proper naming and work with OLM team to resolve this.

**Pull request merged**
