### PR TITLE
[WIP] [TEST ONLY] Trigger CI

### PR DESCRIPTION
**Pull request by mgencur**
Looking into failures on OCP 4.15

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by ReToCode** [comment]
fyi: https://github.com/openshift/release/pull/47951

**Comment by mgencur** [comment]
/test 415-upstream-e2e-kafka-aws-ocp-415

Last attempt.

**Comment by mgencur** [comment]
All runs with EKB tests passed. Closing.

**Pull request closed without merging**
