### PR TITLE
[release-1.21] SRVKE-1171: Add `deadLetterSinkUri` to `Channel` CRD

### PR DESCRIPTION
**Pull request by pierDipi**
Backport https://github.com/knative/eventing/commit/19935b19d61e76e853776368cfdbbdc61a0f37f1

See individual commits for details.

SRVKE-1171

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
```

  * could not run steps: step src failed: could not get build src: builds.build.openshift.io "src" not found 
  *
```
flake?
/retest

**Pull request merged**
