### PR TITLE
[RELEASE-1.32] Use the operator-registry image more consistently

### PR DESCRIPTION
**Pull request by ReToCode**
## Proposed Changes
- https://github.com/openshift-knative/serverless-operator/pull/2508 for 1.32

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by dsimansk** [comment]
For the sake of time & scars pool count, should we start overriding some of those check? Once we feel satisfied with the green results.

**Comment by ReToCode** [comment]
Yeah, let's just merge this one once the one on `main` is green (as it is the same thing).

**Comment by ReToCode** [comment]
merging, as relevant tests on https://github.com/openshift-knative/serverless-operator/pull/2508 passed to get rid of one source of CI issues.

**Pull request merged**
