### PR TITLE
Refer to OCP 4.6 docs in CSV - master

### PR DESCRIPTION
**Pull request by mgencur**
* 1.11 is only supported on 4.6 right now

### CODE REVIEW

**Comment by mgencur** [comment]
Sorry. The github action for "template" failed. I had to put the change in the template as well.

**Comment by markusthoemmes** [comment]
Speaking of template: Is this something that we could compute out of our template generation metadata? Maybe put in the lowest supported channel or something?

**Comment by mgencur** [comment]
/hold

@markusthoemmes right, I had the exact same idea about generating this as part of the template. I will send this change here.

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

YAY!

**Pull request merged**
