### PR TITLE
Add failfast option to run e2e to collect logs when failed

### PR DESCRIPTION
**Pull request by nak3**
When `TestKnativeServing()` failed, e2e continues to run tests including `DeleteKnativeServing()`. Due to this, dump_status gets empty result.

For example:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/119/pull-ci-openshift-knative-serverless-operator-master-4.3-e2e-aws-ocp-43/190
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/120/pull-ci-openshift-knative-serverless-operator-master-4.3-e2e-aws-ocp-43/193

To fix it, this PR changes to run e2e with `-failfast` option.

### CODE REVIEW

**Comment by nak3** [comment]
/test 4.3-e2e-aws-ocp-43

Failed on non-expected test...

**Comment by nak3** [comment]
When error happens, we can see the logs:

`[2020-02-17 04:51:04.566][1][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:77] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: route: unknown weighted cluster 'helloworld-go-spkgs/'`

I'm not 100% sure, but let's try to use(revert) the latest kourier gateway image.

**Comment by nak3** [comment]
Although clean up test failed, normal test passed by the kourier's gateway image. https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/121/pull-ci-openshift-knative-serverless-operator-master-4.3-e2e-aws-ocp-43/210
Let's see another try.

**Comment by jmprusi** [comment]
registry failing... aws credentials missing...

**Comment by nak3** [comment]
/retest

`TestKnativeServing` passed "unfortunately"...

```
+ go test -v -race -count=1 -tags=e2e -timeout=30m -parallel=1 ./test/e2e/knative_serving_test.go --kubeconfig /tmp/admin.kubeconfig --kubeconfigs /tmp/admin.kubeconfig,/go/src/github.com/openshift-knative/serverless-operator/user1.kubeconfig,/go/src/github.com/openshift-knative/serverless-operator/user2.kubeconfig,/go/src/github.com/openshift-knative/serverless-operator/user3.kubeconfig
+ tee /tmp/tmp.WLVvmXuG51
=== RUN   TestKnativeServing
...
PASS
ok      command-line-arguments  424.299s
```

**Comment by nak3** [comment]
Again, TestKnativeServing passed...

```
+ go test -v -race -count=1 -tags=e2e -timeout=30m -parallel=1 ./test/e2e/knative_serving_test.go --kubeconfig /tmp/admin.kubeconfig --kubeconfigs /tmp/admin.kubeconfig,/go/src/github.com/openshift-knative/serverless-operator/user1.kubeconfig,/go/src/github.com/openshift-knative/serverless-operator/user2.kubeconfig,/go/src/github.com/openshift-knative/serverless-operator/user3.kubeconfig
=== RUN   TestKnativeServing
  ....
PASS
ok  	command-line-arguments	361.973s

**Comment by nak3** [comment]
/retest
```
release "release-latest" failed: the pod ci-op-75h5k1q6/release-latest failed after 1m21s
```
CI job's issue.

**Comment by jmprusi** [comment]
/test 4.3-e2e-aws-ocp-43

Kourier wasn't deployed? https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/121/pull-ci-openshift-knative-serverless-operator-master-4.3-e2e-aws-ocp-43/269/artifacts/e2e-aws-ocp-43/pods/

**Comment by nak3** [comment]
> Kourier wasn't deployed?

No, the e2e tests calls `DeleteKnativeServing()` and it deletes everything deployed when failed. I am updating the script to fix it.

**Comment by nak3** [comment]
/assign @mgencur @markusthoemmes 

I was using this PR for debugging, but I believe that it is better to have this change in master branch for troubleshooting.

**Pull request merged**
