### PR TITLE
Drop the version in storage-version-migration containers

### LINKED ISSUE #2320: TestServerlessUpgrade timeout
on https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/2312/pull-ci-openshift-knative-serverless-operator-main-4.13-upgrade-tests-aws-ocp-413/1711419060102631424
```
FAIL test/upgrade.TestServerlessUpgradePrePost/PreUpgradeTests/KafkaBrokerPreUpgradeTest/broker_smoke_test/Requirement (-1.00s)
=== RUN   TestServerlessUpgradePrePost/PreUpgradeTests/InMemoryChannelPreUpgradeTest/ChannelChain/Assert
FAIL test/upgrade.TestServerlessUpgradePrePost/PreUpgradeTests/InMemoryChannelPreUpgradeTest/ChannelChain/Assert (-1.00s)
=== RUN   TestServerlessUpgradePrePost/Run/Steps/PostUpgradeTests/Verify_jobs_in_knative-serving
panic: test timed out after 1h30m0s
```

### PR DESCRIPTION
**Pull request by ReToCode**
## Proposed Changes
- Drop the version for the storage-version-migration containers in CSV
- Matches the changed [upstream logic](https://github.com/knative/operator/commit/3d8c3fb001958c018a58f5dd603c1297da0e371a)
- Aligns the env var with the job's [generatedName](https://github.com/openshift-knative/serverless-operator/blob/main/openshift-knative-operator/cmd/operator/kodata/knative-serving/1.11/4-serving-post-install-jobs.yaml#L19), so yes, the `-` at the end has to be there :-) 

Fixes #2320

### CODE REVIEW

**Comment by skonto** [comment]
Do we have checks for the job being complete or not? It would be good so we can catch issues like this in the future.

**Comment by ReToCode** [comment]
I think we have them in `VerifyPostInstallJobs`, but they passed in https://github.com/openshift-knative/serverless-operator/pull/2311 because of the "wrong" yaml we had in 1.31. So probably this happened by a funny combination of stuff...

**Pull request merged**
