### PR TITLE
Default to minAvailable: 1 in Servings PodDisruptionBudgets

### PR DESCRIPTION
**Pull request by ReToCode**
Fixes JIRA https://issues.redhat.com/browse/SRVKS-1022

## Proposed Changes
- Defaults to `minAvailable: 1` in Serving's PodDisruptionBudgets
- Once this is merged, we can drop https://github.com/openshift-knative/serving/blob/main/openshift/patches/005-pdb-minavailable.patch

/assign @skonto

### CODE REVIEW

**Comment by ReToCode** [comment]
```
registry.access.redhat.com: Temporary failure in name resolution
```

**Comment by ReToCode** [comment]
/override "Validate / Generated files are committed"

**Comment by skonto** [comment]
Upgrade test failure:

```
    upgrade.go:15: Serverless upgrade failed: knative kafka upgrade failed: knativekafka knative-kafka is not in desired state, got: &{TypeMeta:{Kind:KnativeKafka APIVersion:operator.serverless.openshift.io/v1alpha1} ObjectMeta:{Name:knative-kafka GenerateName: Namespace:knative-eventing SelfLink: UID:5e3af838-ba1d-4660-92a4-6fcc3ff5a66a ResourceVersion:93565 Generation:2 CreationTimestamp:2024-11-07 09:50:48 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"operator.serverless.openshift.io/v1alpha1","kind":"KnativeKafka","metadata":{"annotations":{},"name":"knative-kafka","namespace":"knative-eventing"},"spec":{"broker":{"defaultConfig":{"bootstrapServers":"my-cluster-kafka-bootstrap.kafka:9092"},"enabled":true},"channel":{"bootstrapServers":"my-cluster-kafka-bootstrap.kafka:9092","enabled":true},"sink":{"enabled":true},"source":{"enabled":true}}}
```

**Comment by skonto** [comment]
If upgrade tests pass I will override the `generated files` thingy.

**Comment by ReToCode** [comment]
```
INFO[2024-11-07T14:11:53Z] Build src-amd64 previously failed from an infrastructure error (OutOfMemoryKilled), retrying... 
```
/retest

**Comment by ReToCode** [comment]
```
error: unable to read image image-registry.openshift-image-registry.svc:5000/openshift-marketplace/serverless-index:latest: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

/test 417-test-upgrade-aws-417

**Pull request merged**
