### PR TITLE
Rename knative-serving-openshift -> knative-openshift

### PR DESCRIPTION
**Pull request by jcrossley3**
Now that eventing is a part of this operator, the name is confusing

### CODE REVIEW

**Comment by jcrossley3** [comment]
> Why not `knative-operator` everywhere? Would make it consistent with the folder name

I considered it, and I agree the folder name is a problem. I like that 'openshift' is a part of the name, because everything the operator does is specific to OpenShift: it's most definitely an "openshift-specific operator". Is renaming the folder to 'knative-openshift' too stupid to bear?

**Comment by markusthoemmes** [comment]
Let's roll with this then and think about renaming the folder separately.

**Comment by markusthoemmes** [comment]
/retest

Failures due to git struggles.

**Pull request merged**
