### PR TITLE
[SRVCOM-2061] Add deployment probe overrides support

### PR DESCRIPTION
**Pull request by skonto**
## Proposed Changes

- Partially backport https://github.com/knative/operator/pull/1247
- In 1.8+ we will have the full fix and addition of workload overrides. 
- Adding this minimal part to avoid large changes and satisfy customer case.

### CODE REVIEW

**Comment by skonto** [comment]
Needs #1779

**Comment by matzew** [comment]
I was thinking that we backport https://github.com/knative/operator/pull/1246  as well,

which than puts these new "overrides" to the workload  (this is a feature we should have on 1.26)

**Comment by skonto** [comment]
> I was thinking that we backport https://github.com/knative/operator/pull/1246 as well,

I just did the part that is urgent for the customer case. Do we need workloads for 1.26?

**Comment by skonto** [comment]
As we discussed on slack I will do the full backport stay tuned.

**Comment by matzew** [comment]
/hold
we want 1782 instead

**Comment by skonto** [comment]
closing this.

**Pull request closed without merging**
