### PR TITLE
[SRVKS-289] Set default domainTemplate to {{.Name}}-{{.Namespace}}.{{Domain}}

### PR DESCRIPTION
**Pull request by nak3**
This patch changes domainTemplate to `{{.Name}}-{{.Namespace}}.{{.Domain}}` from `{{.Name}}.{{.Namespace}}.{{.Domain}}`.

Serving on OpenShift uses OpenShift's cluster wildcard cert for secure route, so the
domain level must have `<sub>.<domain>` instead of `<sub1>.<sub2>.<domain>`.

### CODE REVIEW

**Comment by nak3** [comment]
The failure is due to wrong patch command. The `git apply --directly` does not work with absolute path... We need to backport this or copy entire `name.go` file.

```
+ git apply test/patches/name-length-limit.path --directory /tmp/gopath-LC32qTB89v/src/knative.dev/serving
fatal: invalid path '/tmp/gopath-LC32qTB89v/src/knative.dev/serving/vendor/knative.dev/pkg/test/helpers/name.go'
```

**Comment by markusthoemmes** [comment]
/test 4.3-e2e-aws-ocp-43

Setup issue.

**Comment by markusthoemmes** [comment]
/test 4.3-upgrade-tests-aws-ocp-43

Setup issues.

**Comment by markusthoemmes** [comment]
/test 4.5-upgrade-tests-aws-ocp-45

Setup issues ...grrrrr.

**Comment by markusthoemmes** [comment]
/test 4.4-e2e-aws-ocp-44

Setup issues.

**Comment by markusthoemmes** [comment]
/test 4.4-upgrade-tests-aws-ocp-44

Setup issues.

**Comment by markusthoemmes** [comment]
/retest

Infra, infra, infra.

**Comment by markusthoemmes** [comment]
/test 4.3-upgrade-tests-aws-ocp-43

An actual issue, logged in https://issues.redhat.com/browse/SRVKS-456

**Comment by markusthoemmes** [comment]
/test 4.4-e2e-aws-ocp-44

Infra (failed to scale cluster)

**Comment by markusthoemmes** [comment]
/test 4.4-upgrade-tests-aws-ocp-44

Infra (failed to scale cluster)

**Comment by markusthoemmes** [comment]
/retest

All setup issues.

**Comment by markusthoemmes** [comment]
/retest

Infra..

**Comment by markusthoemmes** [comment]
Almost!

/retest

**Pull request merged**
