### PR TITLE
Rewrite of E2E scripts to open them to hecking need with various enhancements and bugfixes

### PR DESCRIPTION
**Pull request by cardil**
This PR add couple fixes and enhancements:

**Enhancements:**

 * Bash scripts are more Hi-Fi:
   * colorful outout if tty present, 
   * no dump if running in GDK session,
   * more debug messages,
   * proper logger with levels.
 * To enable interactive usage scripts has been rewritten and moved to `hack` directory. In that way it is possible to invoke 3 main scripts:

   * `hack/dependencies.sh`:
     * Scale up cluster to accept serverless,
     * Install Red Hat Service Mesh and it's dependencies,
     * Adds namespace fo Knative Serving and Serverless,
     * Configure Service Mesh Member Roll.
   * `hack/install.sh`:
     * Do everything that `hack/dependencies.sh` do,
     * Install Serverless Operator from this repository,
     * Install Knative Serving custom resource.
   * `hack/teardown.sh`:
     * Remove Knative Serving custom resource,
     * Uninstall Serverless Operator,
     * Remove Catalog Source,
     * Unregister namespaces from Service Mesh and remove them.

**Bug fixes:**

 * Go 1.13+ regression fix for using flags in tests - Issue and walk around is described here: golang/go#31859
 * (SRVKS-297) Incorporating walk around to Istio setup: https://jira.coreos.com/browse/SRVKS-297, and https://issues.jboss.org/browse/MAISTRA-862, 
 * Using `htpass-secret` if present, or creating it - This is to make it work on CI server as well as with cluster deployed by internal CI

### CODE REVIEW

**Comment by cardil** [comment]
I feel like most of this e2e setup code can be placed into some `openshift-knative/test-infra` repository. In that way it can be reused in other repos, and not being copy-pasted. It will increase code quality over time and raise code ownership.

**Comment by mgencur** [comment]
Hi @cardil , thanks for working on this. I'd say I like some things in this PR and don't like other things. Maybe it's a personal opinion so I'd like someone else to review it as well.

I like the following things:
* fix for Go 1.13 and the flags
* fix for htpasswd
* the stuff in `ui` folder, i.e. functions for better visualization

Personally, I'm a little scared of splitting the bash scripts into so many different files. Navigation doesn't work for me in vscode (maybe doing something wrong but I can't navigate from one file to another). Another thing is that some things are better grouped together, like the variables in facts.bash and a lot of other functions that use them. They seem to be tightly coupled and they don't work without one another. Personally, I'd keep the ServiceMesh stuff in one file. Helper functions into another file. And then namespaces.bash, catalogsource.bash, users.bash, facts.bash, lifecycle.bash, tests.bash into one other common file. The things in `ui` folder could be separate as well. We're trying to use bash like a real programming language but I'm not sure it will be much helpful. So, I'd use much fewer files:-)

Having said that, I'd like to hear other opinions as well. @jcrossley3 @markusthoemmes ?

**Comment by markusthoemmes** [comment]
+1 on less files for bash. I do appreciate what you're trying to achieve but I have to agree with @mgencur in that bash doesn't work like a **real** programming language, at least in my experience.

**Comment by cardil** [comment]
@mgencur Your proposition seems reasonable to me. Personally I like to have smaller files, but I also understand your point.

I will fight for separation between declaration and execution. That separation let me reuse some of this scripts in other repository already. I think that's good thing. Best will be if we can put those scripts to separate repository, like: `openshift-knative/test-infra`.

**Comment by cardil** [comment]
Updated. I hope you like this version more.

**Comment by matzew** [comment]
Is the idea that tese scripts than will be used to install things like ServiceMesh, Serverless Operators in:
* serving fork
* eventing fork
* client fork 

?

with fork, I mean our `openshift/knative-xyz` repos

**Comment by matzew** [comment]
A bit related ... recently @alanconway was proposing to 'stash' our script in git submodules, since currently the madness w/ master, and (re)creating branches w/ files from the stash/master has some issues.

**Comment by alanconway** [comment]
> A bit related ... recently @alanconway was proposing to 'stash' our script in git submodules, since currently the madness w/ master, and (re)creating branches w/ files from the stash/master has some issues.

I'm not married to submodules, there could be other solutions. Here's the problem as I see it: 

The CI setup for e.g. knative-eventing involves 4 codebases :

* knative.dev/eventing - upstream
* openshift/knative-eventing/master - CI files
* openshift/knative-eventing/release-branch - patches + CI files
* openshift/release - CI files

Note I put master/release-branch as separate codebases because they have *no shared git history*. The CI files on master and release branches *look* like versions of the same file, but they are not - you can't merge between them.

This is confusing for newcomers, requires a lot of manual copying, and seems to lack traceability and repeatability. 

Maybe we could move all CI files into openshift/release (in per-repo directories) so that openshift/knative-eventing is a normal fork of upstream for patches only and all the CI scripts and generators are in one place.

**Comment by cardil** [comment]
Ok. Here is a rewrite to enable usage from hack directory for development needs.

Showcase: https://asciinema.org/a/276973

To enable interactive usage scripts has been rewritten and moved to `hack` directory. In that way it is possible to invoke 3 main scripts:

 * `hack/dependencies.sh`:
   * Scale up cluster to accept serverless,
   * Install Red Hat Service Mesh and it's dependencies,
   * Adds namespace fo Knative Serving and Serverless,
   * Configure Service Mesh Member Roll.
 * `hack/install.sh`:
   * Do everything that `hack/dependencies.sh` do,
   * Install Serverless Operator from this repository,
   * Install Knative Serving custom resource.
 * `hack/teardown.sh`:
   * Remove Knative Serving custom resource,
   * Uninstall Serverless Operator,
   * Remove Catalog Source,
   * Unregister namespaces from Service Mesh and remove them.

**Pull request merged**
