### PR TITLE
Update dependencies of the serving-ingress component to match upstream.

### PR DESCRIPTION
**Pull request by markusthoemmes**
This heavily bumps the dependencies of operator-sdk and controller-runtime to be on kubernetes-1.16.x, which is what upstream currently uses.

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm

/hold
defer to @jcrossley3

**Comment by jcrossley3** [comment]
I'm surprised this compiles, much less works at runtime. :)

If it does work, and those test failures aren't flakes, then you just accidentally fixed SRVCOM-776 for me. Thanks!

**Comment by markusthoemmes** [comment]
@jcrossley3 I have to let you down here. This is the ingress component, not knative-operator.

**Comment by jcrossley3** [comment]
> @jcrossley3 I have to let you down here. This is the ingress component, not knative-operator.

Doh! Duh.

**Comment by nak3** [comment]
@jcrossley3 @markusthoemmes Do we wait for OCP4.5's CI fix? Or can we `/unhold` this?

**Comment by markusthoemmes** [comment]
@nak3 we can unhold this. I'm mostly waiting for us releasing to not clutter things too much unnecessarily.

**Pull request merged**
