### PR TITLE
Add DowngradePodDisruptionBudget to modify API version of PodDisruptionBudget

### PR DESCRIPTION
**Pull request by nak3**
Part of [SRVCOM-1855](https://issues.redhat.com/browse/SRVCOM-1855).

### CODE REVIEW

**Comment by nak3** [comment]
Hmm... There are no trigger to run 4.6 CI :sweat_smile:

**Comment by nak3** [comment]
Note, the notable change for PodDisruptionBudget does not effect on the usage in serverless -  
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125

**Comment by skonto** [comment]
Does this work for cluster upgrades?

**Pull request closed without merging**
