### PR TITLE
Update target Knative version to 0.20 in Golang deps

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title, the types seem compatible and this frontloads a bit of the enormous diff that is upgrading those versions. Also unblocks work on next-gen upgrade tests.

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by markusthoemmes** [comment]
/retest

Infra....

**Comment by markusthoemmes** [comment]
/hold

to see everything pass

**Pull request merged**
