### PR TITLE
[WIP] Override images for Kafka resources in the CSV

### PR DESCRIPTION
**Pull request by aliok**
With this PR, the image override is implemented for Kafka components.

To help you follow what is going on:

- 283d3b643fff5e795439631b03fe262061956427: Just copy&paste the image override mechanism from upstream **as is**. It would be nice to use it as a library, but it is not possible because `KnativeKafka` doesn't support overrides with CR spec.
- 558193448b5cef1ffe1d4be68cf9c580185e472f: Modify the *as is* image override mechanism to get rid of default registry and image cache. Also use the transform in the controller
- 0b4036af41e728fd4be111f3c025a387f714ba44: Make the necessary changes in the CSV with actual image overrides. Naming clash in `DISPATCHER_IMAGE` env var override.
- 51090440cad7caedecd6df9e6e8a9df7a0b35f07: Add scopes to image overrides. "DISPATCHER_IMAGE" is now "KAFKA_DISPATCHER_IMAGE" and "EVENTING_DISPATCHER_IMAGE".
- 3800dc06552e5c35dde3dadc5d2b3f8c393857f4: Have upstream images in manifests

About "scoping" image overrides:
- There is an env var which we should override: `DISPATCHER_IMAGE` of `kafka-ch-controller` deployment. However, we already have an override for that env var in Knative Eventing.
- The copied upstream image override mechanism doesn't check the deployment or container name when it is done with env vars.
- Thus, I created "scopes" for image overrides

Chat with Markus: https://coreos.slack.com/archives/CD87JDUB0/p1601892394404600

### CODE REVIEW

**Comment by aliok** [comment]
Ignore for now

**Comment by aliok** [comment]
/test 4.5-upstream-e2e-aws-ocp-45

not sure if this is related, but let's retest anyway

```
kubelogs.go:197: I 20:56:17.729 autoscaler-5ff678f996-sf5p4 [scaling/autoscaler.go:208] [serving-tests/activator-overload-csrofhxb-xznpp] PANICKING.
    kubelogs.go:197: D 20:56:17.729 autoscaler-5ff678f996-sf5p4 [scaling/autoscaler.go:230] [serving-tests/activator-overload-csrofhxb-xznpp] Operating in panic mode.
```

**Comment by aliok** [comment]
This was green, now I just rebased it onto a more "recent" branch.

**Comment by matzew** [comment]
because of #581 
/close

**Pull request closed without merging**
